// Drift detection for the memory-curation skill foreign-runtime copies.
//
// Source of truth: sdk/prismer-cloud/built-in-skills/memory-curation/SKILL.md
//
// Runtime TS (sdk/prismer-cloud/runtime/src/skills/memory-curation.ts) is NO
// LONGER a drift target — it reads the canonical SKILL.md from disk via the
// `runtime/built-in-skills/` tarball mirror at startup. Drift between the
// runtime TS and the canonical is structurally impossible.
//
// Foreign-runtime copies (regenerated by scripts/regenerate-memory-curation-skill.cjs):
//   1. openclaw-channel/src/memory-curation-skill.ts (TS, used by OpenClaw)
//   2. python/prismer/_memory_curation_skill.py     (Python, used by Hermes)
//   3. claude-code-plugin/skills/memory-curation/SKILL.md (direct copy, CC)
//
// CI guard: if any copy drifts from canonical, this test fails with a
// pointer to the regen script. Stops "I edited skill but forgot to
// regenerate" from leaking to a release.

import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
// runtime/test/ → runtime/ → prismer-cloud/ → sdk/ → repoRoot
const REPO_ROOT = join(__dirname, '..', '..', '..', '..');

function readCanonical(): string {
  return readFileSync(
    join(REPO_ROOT, 'sdk/prismer-cloud/built-in-skills/memory-curation/SKILL.md'),
    'utf8',
  );
}

function readPython(): string {
  // Extract the triple-quoted string from the Python module — keeps the test
  // independent of any Python interpreter being installed in CI.
  const py = readFileSync(
    join(REPO_ROOT, 'sdk/prismer-cloud/python/prismer/_memory_curation_skill.py'),
    'utf8',
  );
  // Match the ``MEMORY_CURATION_SKILL_TEXT = """<content>"""`` assignment.
  // Use [\s\S] to span newlines without enabling the `s` flag (Node 18+ only).
  const match = py.match(/MEMORY_CURATION_SKILL_TEXT = """([\s\S]*?)"""/);
  if (!match) throw new Error('could not find MEMORY_CURATION_SKILL_TEXT in Python module');
  return match[1] ?? '';
}

function readOpenclawTs(): string {
  // Same trick for the openclaw TS embedded copy — match the template literal.
  const ts = readFileSync(
    join(REPO_ROOT, 'sdk/prismer-cloud/openclaw-channel/src/memory-curation-skill.ts'),
    'utf8',
  );
  const match = ts.match(/MEMORY_CURATION_SKILL_TEXT = `([\s\S]*?)`;/);
  if (!match) throw new Error('could not find MEMORY_CURATION_SKILL_TEXT in OpenClaw TS module');
  // Un-escape the template-literal backtick escapes that the regen script applied.
  return (match[1] ?? '').replace(/\\`/g, '`');
}

function readCcPluginSkill(): string {
  return readFileSync(
    join(REPO_ROOT, 'sdk/prismer-cloud/claude-code-plugin/skills/memory-curation/SKILL.md'),
    'utf8',
  );
}

describe('memory-curation skill — drift detection', () => {
  const canonical = readCanonical();
  const REGEN_HINT =
    '\nRun: node sdk/prismer-cloud/runtime/scripts/regenerate-memory-curation-skill.cjs';

  it('canonical SKILL.md is non-empty and well-formed', () => {
    expect(canonical.length).toBeGreaterThan(1000);
    expect(canonical).toMatch(/^---\nname: memory-curation\n/);
    expect(canonical).toMatch(/^# Memory Curation Skill$/m);
  });

  it('OpenClaw TS embedded copy === canonical', () => {
    const openclaw = readOpenclawTs();
    expect(openclaw, `openclaw-channel/src/memory-curation-skill.ts drifted.${REGEN_HINT}`).toBe(
      canonical,
    );
  });

  it('Python embedded copy === canonical', () => {
    const python = readPython();
    expect(python, `python/prismer/_memory_curation_skill.py drifted.${REGEN_HINT}`).toBe(
      canonical,
    );
  });

  it('Claude Code plugin SKILL.md === canonical', () => {
    const cc = readCcPluginSkill();
    expect(cc, `claude-code-plugin/skills/memory-curation/SKILL.md drifted.${REGEN_HINT}`).toBe(
      canonical,
    );
  });
});
