import { Command } from 'commander';
import {
  createHash,
  createHmac,
} from 'node:crypto';
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { homedir } from 'node:os';
import { join, relative, resolve, sep } from 'node:path';
import { execFileSync } from 'node:child_process';
import { PrismerClient } from '../index';

type ClientFactory = () => PrismerClient;

// release201/09 §9.7.1 — agent transfer manifest shape.
//
// Generated by `prismer agent export` and consumed by `prismer agent import`
// + cloud POST /api/im/agent-bindings/transfer。Signature 是 HMAC_SHA256
// over `sha256` field,用 daemon api_key 作 key — 信任源 device 持有 key
// 即代表持有 agent。v2.1+ cloud 维护 expected hash 后再补严格校验。
interface AgentTransferManifest {
  version: 1;
  agentId: string;
  fromDaemonId: string;
  exportedAt: string; // ISO 8601
  includes: string[];
  excludes: string[];
  sha256: string; // merkle of all included file:hash lines
  signature: string; // HMAC-SHA256(apiKey, sha256)
}

// Resolution of $PRISMER_HOME / ~/.prismer — must mirror runtime/src/config.ts.
function resolvePrismerRoot(): string {
  return process.env.PRISMER_HOME
    ? resolve(process.env.PRISMER_HOME)
    : join(homedir(), '.prismer');
}

interface DaemonConfigSnapshot {
  daemonId: string;
  apiKey: string;
}

function readDaemonConfig(): DaemonConfigSnapshot {
  const path = join(resolvePrismerRoot(), 'config.toml');
  if (!existsSync(path)) {
    throw new Error(`${path} not found. Run \`prismer setup\` first.`);
  }
  const raw = readFileSync(path, 'utf8');
  // Lightweight TOML probe — config has flat key=value pairs; full parse
  // already happens in runtime. We only need daemon_id + api_key here.
  const idMatch = raw.match(/^daemon_id\s*=\s*"([^"]+)"/m);
  const keyMatch = raw.match(/^api_key\s*=\s*"([^"]+)"/m);
  if (!idMatch || !keyMatch) {
    throw new Error(`config.toml missing daemon_id or api_key (${path})`);
  }
  return { daemonId: idMatch[1]!, apiKey: keyMatch[1]! };
}

function resolveAgentDir(daemonId: string, agentId: string): string {
  return join(resolvePrismerRoot(), 'devices', daemonId, 'agents', agentId);
}

// Walk all files under a directory, collecting relative path + sha256.
// Files in `excludeNames` (basename) are skipped. Returns sorted list for
// deterministic merkle root.
function collectFiles(root: string, excludeBasenames: Set<string>): Array<{ rel: string; sha: string; size: number }> {
  const out: Array<{ rel: string; sha: string; size: number }> = [];
  function walk(dir: string): void {
    let entries: string[];
    try {
      entries = readdirSync(dir);
    } catch {
      return;
    }
    for (const name of entries) {
      if (excludeBasenames.has(name)) continue;
      const full = join(dir, name);
      let st: ReturnType<typeof statSync>;
      try {
        st = statSync(full);
      } catch {
        continue;
      }
      if (st.isDirectory()) walk(full);
      else if (st.isFile()) {
        const buf = readFileSync(full);
        const sha = createHash('sha256').update(buf).digest('hex');
        out.push({
          rel: relative(root, full).split(sep).join('/'),
          sha,
          size: buf.byteLength,
        });
      }
    }
  }
  walk(root);
  out.sort((a, b) => a.rel.localeCompare(b.rel));
  return out;
}

function computeMerkle(files: Array<{ rel: string; sha: string }>): string {
  const lines = files.map((f) => `${f.rel}:${f.sha}`).join('\n');
  return createHash('sha256').update(lines).digest('hex');
}


export function register(parent: Command, getIMClient: ClientFactory, _getAPIClient: ClientFactory): void {
  const agent = parent
    .command('agent')
    .description('Manage agent specs, snapshots, publish, and fork');

  agent
    .command('spec <agent-id>')
    .description('Read an AgentSpec 4-tuple')
    .option('--workspace-id <id>', 'Workspace scope')
    .option('--json', 'Output raw JSON response')
    .action(async (agentId: string, opts: { workspaceId?: string; json?: boolean }) => {
      const res = await getIMClient().im.agents.spec(agentId, opts.workspaceId);
      printOrExit(res, opts.json, (data) => {
        console.log(`AgentSpec ${agentId}`);
        console.log(`  identity: ${data.identity.displayName} (${data.identity.imUserId})`);
        console.log(`  role:     ${data.definition.roleTemplateSlug ?? 'custom'}`);
        console.log(`  skills:   ${data.skills.length}`);
        console.log(`  memory:   ${data.memory.scope}`);
      });
    });

  agent
    .command('snapshot <agent-id>')
    .description('Create an agent-level snapshot')
    .option('--include-memory', 'Include memory dump reference')
    .option('--label <label>', 'Snapshot label')
    .option('--json', 'Output raw JSON response')
    .action(async (agentId: string, opts: { includeMemory?: boolean; label?: string; json?: boolean }) => {
      const res = await getIMClient().im.agents.snapshot(agentId, {
        includeMemory: Boolean(opts.includeMemory),
        label: opts.label,
      });
      printOrExit(res, opts.json, (data) => {
        console.log(`Snapshot created: ${data.id}`);
        console.log(`  agent:  ${data.agentImUserId}`);
        console.log(`  memory: ${data.includeMemory ? 'included' : 'stripped'}`);
        console.log(`  size:   ${data.sizeBytes ?? 0} bytes`);
      });
    });

  agent
    .command('snapshots <agent-id>')
    .description('List agent snapshots')
    .option('-n, --limit <n>', 'Max snapshots', '20')
    .option('--json', 'Output raw JSON response')
    .action(async (agentId: string, opts: { limit: string; json?: boolean }) => {
      const res = await getIMClient().im.agents.snapshots(agentId, { limit: parseInt(opts.limit, 10) || 20 });
      printOrExit(res, opts.json, (data) => {
        const rows = data.items ?? [];
        if (rows.length === 0) {
          console.log('No snapshots.');
          return;
        }
        for (const item of rows) {
          console.log(`${item.id}\t${item.createdAt}\tmemory=${item.includeMemory ? 'yes' : 'no'}\tsize=${item.sizeBytes ?? 0}`);
        }
      });
    });

  agent
    .command('restore <agent-id> <snapshot-id>')
    .description('Restore agent definition and skills from a snapshot')
    .option('--override-memory', 'Restore memory reference when available')
    .option('--json', 'Output raw JSON response')
    .action(async (agentId: string, snapshotId: string, opts: { overrideMemory?: boolean; json?: boolean }) => {
      const res = await getIMClient().im.agents.restore(agentId, {
        snapshotId,
        overrideMemory: Boolean(opts.overrideMemory),
      });
      printOrExit(res, opts.json, () => {
        console.log(`Restored ${agentId} from ${snapshotId}`);
      });
    });

  agent
    .command('publish <agent-id>')
    .description('Publish an agent as an Agent Pack')
    .requiredOption('--slug <slug>', 'Agent Pack slug')
    .option('--version <version>', 'Package version', '1.0.0')
    .option('--license <license>', 'Package license', 'proprietary')
    .option('--title <title>', 'Display title metadata')
    .option('--description <description>', 'Description metadata')
    .option('--json', 'Output raw JSON response')
    .action(async (agentId: string, opts: { slug: string; version?: string; license?: string; title?: string; description?: string; json?: boolean }) => {
      const res = await getIMClient().im.agents.publish(agentId, {
        slug: opts.slug,
        version: opts.version,
        license: opts.license,
        metadata: {
          ...(opts.title ? { title: opts.title } : {}),
          ...(opts.description ? { description: opts.description } : {}),
        },
        stripMemory: true,
      });
      printOrExit(res, opts.json, (data) => {
        console.log(`Agent Pack published: ${data.slug}@${data.version}`);
        console.log(`  id:        ${data.id}`);
        console.log(`  publisher: ${data.publisherDid}`);
      });
    });

  agent
    .command('packs')
    .description('List published Agent Packs')
    .option('-q, --query <query>', 'Search query')
    .option('-n, --limit <n>', 'Max packs', '20')
    .option('--json', 'Output raw JSON response')
    .action(async (opts: { query?: string; limit: string; json?: boolean }) => {
      const res = await getIMClient().im.agents.listPacks({
        q: opts.query,
        limit: parseInt(opts.limit, 10) || 20,
      });
      printOrExit(res, opts.json, (data) => {
        const rows = data.items ?? [];
        if (rows.length === 0) {
          console.log('No Agent Packs.');
          return;
        }
        for (const item of rows) {
          console.log(`${item.slug}@${item.version}\t${item.id}\t${item.license}\t${item.publisherDid}`);
        }
      });
    });

  // release201/09 §9.7 — Phase 3 agent transfer CLI.
  //
  // export <agentId> --output <file.tar.gz> [--force]:
  //   1. quiesce: POST /api/im/agents/:id/pause (cloud stops dispatch)
  //   2. compute manifest sha256 over included files + write transfer-manifest.json
  //   3. tar -czf <output> devices/<did>/agents/<aid>/
  //
  // import <file.tar.gz>:
  //   1. extract to a temp dir, verify manifest signature
  //   2. refuse if devices/<本机 did>/agents/<aid>/ 已存在
  //   3. tar -xzf 到 devices/<本机 did>/agents/<aid>/
  //   4. POST /api/im/agent-bindings/transfer { agentId, fromDaemonId, toDaemonId, manifestSha256 }
  //   5. POST /api/im/agents/:id/resume

  agent
    .command('export <agent-id>')
    .description('release201/09 §9.7 — quiesce + tar an agent directory for transfer')
    .requiredOption('--output <file>', 'Output tar.gz path')
    .option('--force', 'Skip cloud pause (use when source device is offline)')
    .option('--json', 'Output raw JSON result')
    .action(async (agentId: string, opts: { output: string; force?: boolean; json?: boolean }) => {
      const { daemonId, apiKey } = readDaemonConfig();
      const agentDir = resolveAgentDir(daemonId, agentId);
      if (!existsSync(agentDir)) {
        process.stderr.write(`Error: agent dir not found at ${agentDir}\n`);
        process.exit(1);
      }

      // Step 1 — quiesce (unless --force)
      if (!opts.force) {
        const res = await getIMClient().im.agents.pause(agentId);
        if (!res.ok) {
          process.stderr.write(
            `Error: pause failed (${res.error?.message ?? 'unknown'}); pass --force to export anyway\n`,
          );
          process.exit(1);
        }
      }

      // Step 2 — write manifest BEFORE tar so it's included.
      // Forbidden: cache/ + local.db never enter transfer unit (§9.7.1 D10).
      // Those live at ~/.prismer/{cache,local.db}, not inside agentDir — so
      // they're naturally excluded by the agentDir scope. We still exclude
      // any stale transfer-manifest.json from prior exports.
      const excludeBasenames = new Set(['transfer-manifest.json']);
      const files = collectFiles(agentDir, excludeBasenames);
      const sha256 = computeMerkle(files);
      const signature = createHmac('sha256', apiKey).update(sha256).digest('hex');
      const manifest: AgentTransferManifest = {
        version: 1,
        agentId,
        fromDaemonId: daemonId,
        exportedAt: new Date().toISOString(),
        includes: ['profile.json', 'skills/**', 'memory/**', 'outbox/*'],
        excludes: ['cache/ (daemon-level blob pool)', 'local.db (daemon-level)'],
        sha256,
        signature,
      };
      writeFileSync(join(agentDir, 'transfer-manifest.json'), JSON.stringify(manifest, null, 2) + '\n', 'utf8');

      // Step 3 — tar -czf using system tar. -C parent so archive root is `agents/<aid>/`
      // (importer recovers original layout via -C devices/<targetDid>/).
      const parentOfAgents = join(resolvePrismerRoot(), 'devices', daemonId);
      const outputAbs = resolve(opts.output);
      try {
        execFileSync('tar', ['-czf', outputAbs, '-C', parentOfAgents, join('agents', agentId)], { stdio: 'inherit' });
      } catch (err) {
        process.stderr.write(`Error: tar failed: ${(err as Error).message}\n`);
        process.exit(1);
      }

      const result = {
        agentId,
        fromDaemonId: daemonId,
        output: outputAbs,
        manifestSha256: sha256,
        filesIncluded: files.length,
        totalBytes: files.reduce((s, f) => s + f.size, 0),
        paused: !opts.force,
      };
      if (opts.json) {
        process.stdout.write(JSON.stringify(result, null, 2) + '\n');
      } else {
        console.log(`Exported agent ${agentId}`);
        console.log(`  output:        ${result.output}`);
        console.log(`  files:         ${result.filesIncluded}`);
        console.log(`  total bytes:   ${result.totalBytes}`);
        console.log(`  manifestSha:   ${result.manifestSha256.slice(0, 16)}…`);
        console.log(`  cloud paused:  ${result.paused ? 'yes' : 'no (--force)'}`);
        console.log('');
        console.log('Next: copy the tar.gz to the target device and run:');
        console.log(`  prismer agent import ${result.output}`);
      }
    });

  agent
    .command('import <tar-file>')
    .description('release201/09 §9.7 — extract + rebind an agent transferred from another device')
    .option('--json', 'Output raw JSON result')
    .action(async (tarFile: string, opts: { json?: boolean }) => {
      const tarAbs = resolve(tarFile);
      if (!existsSync(tarAbs)) {
        process.stderr.write(`Error: tar file not found: ${tarAbs}\n`);
        process.exit(1);
      }
      const { daemonId: toDaemonId, apiKey } = readDaemonConfig();

      // Step 1 — extract to a temp dir so we can read manifest before
      // committing into the live devices/ tree.
      const tmpRoot = join(resolvePrismerRoot(), '.transfer-staging', `${Date.now()}`);
      mkdirSync(tmpRoot, { recursive: true });
      try {
        execFileSync('tar', ['-xzf', tarAbs, '-C', tmpRoot], { stdio: 'inherit' });
      } catch (err) {
        rmSync(tmpRoot, { recursive: true, force: true });
        process.stderr.write(`Error: tar extract failed: ${(err as Error).message}\n`);
        process.exit(1);
      }

      // Locate agents/<aid>/ inside extracted tree (single agent expected).
      const agentsRoot = join(tmpRoot, 'agents');
      if (!existsSync(agentsRoot)) {
        rmSync(tmpRoot, { recursive: true, force: true });
        process.stderr.write('Error: tar layout invalid — no agents/ root inside archive\n');
        process.exit(1);
      }
      const entries = readdirSync(agentsRoot);
      if (entries.length !== 1) {
        rmSync(tmpRoot, { recursive: true, force: true });
        process.stderr.write(`Error: expected exactly 1 agent in archive, got ${entries.length}\n`);
        process.exit(1);
      }
      const agentId = entries[0]!;
      const stagedAgentDir = join(agentsRoot, agentId);
      const manifestPath = join(stagedAgentDir, 'transfer-manifest.json');
      if (!existsSync(manifestPath)) {
        rmSync(tmpRoot, { recursive: true, force: true });
        process.stderr.write('Error: transfer-manifest.json missing from archive\n');
        process.exit(1);
      }
      let manifest: AgentTransferManifest;
      try {
        manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as AgentTransferManifest;
      } catch (err) {
        rmSync(tmpRoot, { recursive: true, force: true });
        process.stderr.write(`Error: manifest parse failed: ${(err as Error).message}\n`);
        process.exit(1);
      }

      // Step 2 — verify HMAC signature using local apiKey.
      // Source device uses the same workspace key (transfer must stay within
      // same workspace = same key), so local verification works for the
      // common case. v2.1+ moves to cloud-side expected hash.
      const expectedSig = createHmac('sha256', apiKey).update(manifest.sha256).digest('hex');
      if (expectedSig !== manifest.signature) {
        rmSync(tmpRoot, { recursive: true, force: true });
        process.stderr.write(
          'Error: manifest signature verification failed — refusing to import (different workspace, or tampered archive)\n',
        );
        process.exit(1);
      }
      if (manifest.agentId !== agentId) {
        rmSync(tmpRoot, { recursive: true, force: true });
        process.stderr.write(
          `Error: manifest agentId (${manifest.agentId}) != extracted dir name (${agentId})\n`,
        );
        process.exit(1);
      }
      if (manifest.fromDaemonId === toDaemonId) {
        rmSync(tmpRoot, { recursive: true, force: true });
        process.stderr.write(
          `Error: fromDaemonId == toDaemonId (${toDaemonId}); nothing to transfer.\n`,
        );
        process.exit(1);
      }

      // Step 3 — refuse if target dir already exists.
      const targetAgentDir = resolveAgentDir(toDaemonId, agentId);
      if (existsSync(targetAgentDir)) {
        rmSync(tmpRoot, { recursive: true, force: true });
        process.stderr.write(
          `Error: target dir already exists at ${targetAgentDir}. Run \`prismer agent remove ${agentId}\` (TODO) or move it aside first.\n`,
        );
        process.exit(1);
      }

      // Step 4 — move staged dir into devices/<toDaemonId>/agents/<aid>/
      mkdirSync(join(resolvePrismerRoot(), 'devices', toDaemonId, 'agents'), { recursive: true });
      // execFileSync mv is fine on POSIX; fallback to cp -r + rm if cross-device.
      try {
        execFileSync('mv', [stagedAgentDir, targetAgentDir]);
      } catch {
        try {
          execFileSync('cp', ['-R', stagedAgentDir, targetAgentDir]);
          rmSync(stagedAgentDir, { recursive: true, force: true });
        } catch (err) {
          rmSync(tmpRoot, { recursive: true, force: true });
          process.stderr.write(`Error: failed to install agent dir: ${(err as Error).message}\n`);
          process.exit(1);
        }
      }
      rmSync(tmpRoot, { recursive: true, force: true });

      // Step 5 — cloud rebind
      const rebind = await getIMClient().im.agents.transfer({
        agentId,
        fromDaemonId: manifest.fromDaemonId,
        toDaemonId,
        manifestSha256: manifest.sha256,
      });
      if (!rebind.ok || !rebind.data) {
        process.stderr.write(
          `Warning: cloud rebind failed (${rebind.error?.message ?? 'unknown'}). Agent files are on disk at ${targetAgentDir} but cloud still routes to ${manifest.fromDaemonId}.\n` +
            `        Manual fix: POST /api/im/agent-bindings/transfer or rebind via the Devices UI.\n`,
        );
        process.exit(2);
      }
      // Step 6 — resume dispatch (transfer endpoint already clears pausedAt, but
      // call resume explicitly to be idempotent if the target wasn't paused).
      await getIMClient().im.agents.resume(agentId);

      const result = {
        agentId,
        fromDaemonId: manifest.fromDaemonId,
        toDaemonId,
        targetDir: targetAgentDir,
        manifestSha256: manifest.sha256,
        boundDaemonId: rebind.data.boundDaemonId,
        boundBy: rebind.data.boundBy,
      };
      if (opts.json) {
        process.stdout.write(JSON.stringify(result, null, 2) + '\n');
      } else {
        console.log(`Imported agent ${agentId}`);
        console.log(`  from device:  ${result.fromDaemonId}`);
        console.log(`  to device:    ${result.toDaemonId}`);
        console.log(`  target dir:   ${result.targetDir}`);
        console.log(`  cloud bound:  ${result.boundDaemonId} (${result.boundBy})`);
      }
    });

  agent
    .command('cleanup-orphan')
    .description('release201/09 §9.7.3 — list devices/*/agents/* dirs whose cloud binding points elsewhere')
    .option('--delete', 'Actually remove orphan dirs (default: dry-run)')
    .option('--json', 'Output raw JSON list')
    .action(async (opts: { delete?: boolean; json?: boolean }) => {
      const { daemonId } = readDaemonConfig();
      const devicesRoot = join(resolvePrismerRoot(), 'devices');
      if (!existsSync(devicesRoot)) {
        if (opts.json) process.stdout.write('[]\n');
        else console.log('No devices/ dir yet.');
        return;
      }
      const orphans: Array<{ daemonId: string; agentId: string; dir: string; sizeBytes: number }> = [];
      for (const did of readdirSync(devicesRoot)) {
        if (did === daemonId) continue;
        const agentsRoot = join(devicesRoot, did, 'agents');
        if (!existsSync(agentsRoot)) continue;
        for (const aid of readdirSync(agentsRoot)) {
          const dir = join(agentsRoot, aid);
          try {
            const st = statSync(dir);
            if (!st.isDirectory()) continue;
            const files = collectFiles(dir, new Set());
            const sizeBytes = files.reduce((s, f) => s + f.size, 0);
            orphans.push({ daemonId: did, agentId: aid, dir, sizeBytes });
          } catch {
            /* skip */
          }
        }
      }
      if (opts.delete) {
        for (const o of orphans) {
          rmSync(o.dir, { recursive: true, force: true });
        }
      }
      if (opts.json) {
        process.stdout.write(JSON.stringify({ orphans, deleted: Boolean(opts.delete) }, null, 2) + '\n');
      } else {
        if (orphans.length === 0) {
          console.log('No orphan agent dirs.');
        } else {
          console.log(`Found ${orphans.length} orphan agent dir(s)${opts.delete ? ' (DELETED)' : ' (dry-run; pass --delete to remove)'}:`);
          for (const o of orphans) {
            console.log(`  ${o.daemonId}/${o.agentId}  ${o.sizeBytes} bytes  ${o.dir}`);
          }
        }
      }
    });

  agent
    .command('fork <pack-id-or-slug>')
    .description('Fork an Agent Pack into a workspace')
    .requiredOption('--workspace-id <id>', 'Target workspace id')
    .option('--display-name <name>', 'New agent display name')
    .option('--json', 'Output raw JSON response')
    .action(async (packId: string, opts: { workspaceId: string; displayName?: string; json?: boolean }) => {
      const res = await getIMClient().im.agents.forkPack(packId, {
        targetWorkspaceId: opts.workspaceId,
        displayName: opts.displayName,
      });
      printOrExit(res, opts.json, (data) => {
        console.log(`Forked Agent Pack ${packId}`);
        console.log(`  new agent: ${data.newImUserId}`);
        console.log(`  did:       ${data.newDid ?? 'not issued'}`);
      });
    });
}

function printOrExit<T>(res: { ok: boolean; data?: T; error?: { message?: string } }, json: boolean | undefined, print: (data: T) => void): void {
  if (!res.ok || !res.data) {
    process.stderr.write(`Error: ${res.error?.message || 'request failed'}\n`);
    process.exit(1);
  }
  if (json) {
    process.stdout.write(JSON.stringify(res.data, null, 2) + '\n');
    return;
  }
  print(res.data);
}
