// Memory-curation skill content provider for the Codex adapter.
//
// Source of truth: `sdk/prismer-cloud/built-in-skills/memory-curation/SKILL.md`.
// The build pipeline (runtime/scripts/prebuild-copy-built-in-skills.cjs)
// mirrors `sdk/prismer-cloud/built-in-skills/` into `runtime/built-in-skills/`
// so the npm tarball ships the SKILL.md file alongside dist/. At runtime we
// read it via `readFileSync` instead of inlining markdown into a TS template
// literal — keeping the single source of truth honest.
//
// Hosts that cannot share filesystem with the runtime tarball (Python,
// claude-code-plugin, openclaw-channel) still ship their own embedded copy,
// regenerated by scripts/regenerate-memory-curation-skill.cjs and guarded by
// test/skill-memory-curation-sync.test.ts.

import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export const MEMORY_CURATION_SKILL_NAME = 'memory-curation';
export const MEMORY_CURATION_SKILL_VERSION = 1;

/**
 * Resolve the on-disk path to the canonical memory-curation SKILL.md.
 *
 * Identical strategy to hermes/index.ts `resolveBuiltInSkillPath`:
 *   1. npm tarball / dist layout — `<package>/built-in-skills/memory-curation/SKILL.md`
 *   2. vitest / dev — `<repo>/sdk/prismer-cloud/built-in-skills/memory-curation/SKILL.md`
 *
 * Returns `null` if no candidate exists.
 */
function resolveCanonicalPath(): string | null {
  let here: string;
  try {
    here = dirname(fileURLToPath(import.meta.url));
  } catch {
    here = typeof __dirname !== 'undefined' ? __dirname : process.cwd();
  }

  // Anchors:
  //   tarball:  /node_modules/@prismer/runtime/dist/index.js
  //             -> ../built-in-skills/memory-curation/SKILL.md
  //   src dev:  /sdk/prismer-cloud/runtime/src/skills/memory-curation.ts
  //             -> ../../built-in-skills/memory-curation/SKILL.md (post-prebuild,
  //             relative from src/skills)
  //   canonical /sdk/prismer-cloud/runtime/src/skills/memory-curation.ts
  //             -> ../../../../built-in-skills/memory-curation/SKILL.md
  const slug = 'memory-curation';
  const candidates = [
    join(here, '..', 'built-in-skills', slug, 'SKILL.md'),                  // dist anchor
    join(here, '..', '..', 'built-in-skills', slug, 'SKILL.md'),            // src/skills → runtime/built-in-skills (post-prebuild mirror)
    join(here, '..', '..', '..', '..', 'built-in-skills', slug, 'SKILL.md'),// src/skills → sdk/prismer-cloud/built-in-skills (canonical, dev/vitest fallback)
  ];

  for (const candidate of candidates) {
    if (existsSync(candidate)) return candidate;
  }
  return null;
}

let cached: string | null = null;
function readSkillText(): string {
  if (cached !== null) return cached;
  const skillPath = resolveCanonicalPath();
  if (!skillPath) {
    throw new Error(
      `[memory-curation] cannot locate built-in skill SKILL.md on disk. ` +
        `Expected at one of the tarball/canonical mirror locations relative to ` +
        `this module. Did the runtime prebuild script run?`,
    );
  }
  cached = readFileSync(skillPath, 'utf8');
  return cached;
}

/**
 * Read the memory-curation skill text from the canonical SKILL.md on disk.
 * Lazily cached after first call.
 *
 * Throws if the file is missing — the codex adapter relies on it as a
 * system-prompt preamble and silently dropping it would change agent
 * behaviour invisibly.
 */
export function getMemoryCurationSkillText(): string {
  return readSkillText();
}

/**
 * Backwards-compatible string export so existing
 * `MEMORY_CURATION_SKILL_TEXT.trim()` call sites (codex adapter) keep
 * working without a rename. Computed at module-load time; if the canonical
 * SKILL.md is missing the codex adapter import itself fails — preferable to
 * silently shipping an empty preamble.
 */
export const MEMORY_CURATION_SKILL_TEXT: string = readSkillText();
