-- 031_v180_community.sql
-- v1.8.0 P8: Evolution Community Forum

CREATE TABLE IF NOT EXISTS im_community_posts (
  id              VARCHAR(36) PRIMARY KEY,
  boardId         VARCHAR(30) NOT NULL,
  authorId        VARCHAR(36) NOT NULL,
  authorType      VARCHAR(10) NOT NULL DEFAULT 'human',
  title           VARCHAR(200) NOT NULL,
  content         TEXT NOT NULL,
  contentHtml     TEXT,
  contentJson     LONGTEXT,
  tags            JSON,
  postType        VARCHAR(20) NOT NULL DEFAULT 'discussion',
  status          VARCHAR(20) NOT NULL DEFAULT 'active',
  linkedGeneIds   JSON,
  linkedSkillIds  JSON,
  linkedAgentId   VARCHAR(36),
  linkedCapsuleId VARCHAR(36),
  attachments     JSON,
  upvotes         INT NOT NULL DEFAULT 0,
  downvotes       INT NOT NULL DEFAULT 0,
  commentCount    INT NOT NULL DEFAULT 0,
  viewCount       INT NOT NULL DEFAULT 0,
  bookmarkCount   INT NOT NULL DEFAULT 0,
  solvedAt        DATETIME,
  bestAnswerId    VARCHAR(36),
  deletedAt       DATETIME,
  deletedBy       VARCHAR(100),
  pinned          BOOLEAN NOT NULL DEFAULT FALSE,
  featured        BOOLEAN NOT NULL DEFAULT FALSE,
  autoGenerated   BOOLEAN NOT NULL DEFAULT FALSE,
  scope           VARCHAR(50) NOT NULL DEFAULT 'global',
  createdAt       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  INDEX idx_board_created (boardId, createdAt),
  INDEX idx_board_upvotes (boardId, upvotes),
  INDEX idx_author (authorId, createdAt),
  INDEX idx_status_board (status, boardId),
  INDEX idx_linked_agent (linkedAgentId),
  INDEX idx_deleted (deletedAt),
  FULLTEXT INDEX ft_post_search (title, content)
);

CREATE TABLE IF NOT EXISTS im_community_comments (
  id              VARCHAR(36) PRIMARY KEY,
  postId          VARCHAR(36) NOT NULL,
  parentId        VARCHAR(36),
  authorId        VARCHAR(36) NOT NULL,
  authorType      VARCHAR(10) NOT NULL DEFAULT 'human',
  content         TEXT NOT NULL,
  contentHtml     TEXT,
  commentType     VARCHAR(10) NOT NULL DEFAULT 'reply',
  upvotes         INT NOT NULL DEFAULT 0,
  downvotes       INT NOT NULL DEFAULT 0,
  isBestAnswer    BOOLEAN NOT NULL DEFAULT FALSE,
  autoGenerated   BOOLEAN NOT NULL DEFAULT FALSE,
  linkedGeneIds   JSON,
  metrics         JSON,
  deletedAt       DATETIME,
  deletedBy       VARCHAR(100),
  createdAt       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  INDEX idx_post_created (postId, createdAt),
  INDEX idx_post_votes (postId, upvotes),
  INDEX idx_post_best (postId, isBestAnswer),
  INDEX idx_comment_author (authorId),
  INDEX idx_comment_deleted (deletedAt)
);

CREATE TABLE IF NOT EXISTS im_community_votes (
  id          VARCHAR(36) PRIMARY KEY,
  userId      VARCHAR(36) NOT NULL,
  targetType  VARCHAR(10) NOT NULL,
  targetId    VARCHAR(36) NOT NULL,
  value       INT NOT NULL,
  createdAt   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uk_vote (userId, targetType, targetId),
  INDEX idx_target (targetType, targetId)
);

CREATE TABLE IF NOT EXISTS im_community_bookmarks (
  id      VARCHAR(36) PRIMARY KEY,
  userId  VARCHAR(36) NOT NULL,
  postId  VARCHAR(36) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uk_bookmark (userId, postId),
  INDEX idx_user_bookmarks (userId, createdAt)
);

CREATE TABLE IF NOT EXISTS im_community_follows (
  id              VARCHAR(36) PRIMARY KEY,
  followerId      VARCHAR(36) NOT NULL,
  followingId     VARCHAR(36) NOT NULL,
  followingType   VARCHAR(10) NOT NULL DEFAULT 'user',
  createdAt       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uk_follow (followerId, followingId, followingType),
  INDEX idx_following (followingId, followingType)
);

CREATE TABLE IF NOT EXISTS im_community_tags (
  id          VARCHAR(36) PRIMARY KEY,
  name        VARCHAR(50) NOT NULL,
  postCount   INT NOT NULL DEFAULT 0,
  trending    BOOLEAN NOT NULL DEFAULT FALSE,
  createdAt   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  UNIQUE KEY uk_tag_name (name),
  INDEX idx_post_count (postCount)
);

CREATE TABLE IF NOT EXISTS im_community_post_tags (
  id      VARCHAR(36) PRIMARY KEY,
  postId  VARCHAR(36) NOT NULL,
  tagId   VARCHAR(36) NOT NULL,

  UNIQUE KEY uk_post_tag (postId, tagId),
  INDEX idx_tag (tagId)
);

-- ── v1.5: Dynamic Boards ────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS im_community_boards (
  id              VARCHAR(30) PRIMARY KEY,
  slug            VARCHAR(50) NOT NULL,
  name            VARCHAR(100) NOT NULL,
  description     TEXT,
  icon            VARCHAR(50),
  creatorId       VARCHAR(36) NOT NULL,
  isSystem        BOOLEAN NOT NULL DEFAULT FALSE,
  rules           TEXT,
  postCount       INT NOT NULL DEFAULT 0,
  subscriberCount INT NOT NULL DEFAULT 0,
  status          VARCHAR(20) NOT NULL DEFAULT 'active',
  createdAt       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  UNIQUE KEY uk_board_slug (slug),
  INDEX idx_board_status (status, postCount),
  INDEX idx_board_creator (creatorId)
);

CREATE TABLE IF NOT EXISTS im_community_board_admins (
  id        VARCHAR(30) PRIMARY KEY,
  boardId   VARCHAR(30) NOT NULL,
  userId    VARCHAR(36) NOT NULL,
  role      VARCHAR(15) NOT NULL DEFAULT 'moderator',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE KEY uk_board_admin (boardId, userId),
  INDEX idx_admin_user (userId)
);

-- Seed system boards
INSERT IGNORE INTO im_community_boards (id, slug, name, description, icon, creatorId, isSystem, status) VALUES
  ('board_showcase',  'showcase',  'Showcase',  'Agent 战报与里程碑展示',   '🏆', 'system', TRUE, 'active'),
  ('board_genelab',   'genelab',   'Gene Lab',  '基因讨论、复盘与学术分享', '🧬', 'system', TRUE, 'active'),
  ('board_helpdesk',  'helpdesk',  'Help Desk', '技术问答与疑难解答',       '❓', 'system', TRUE, 'active'),
  ('board_ideas',     'ideas',     'Ideas',     '功能建议与产品改进',       '💡', 'system', TRUE, 'active'),
  ('board_changelog', 'changelog', 'Changelog', '版本更新与变更记录',       '📋', 'system', TRUE, 'active');

-- ── v1.5: User Profile ─────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS im_community_profiles (
  id             VARCHAR(36) PRIMARY KEY,
  bio            VARCHAR(300),
  website        VARCHAR(200),
  postCount      INT NOT NULL DEFAULT 0,
  commentCount   INT NOT NULL DEFAULT 0,
  karmaTotal     INT NOT NULL DEFAULT 0,
  followerCount  INT NOT NULL DEFAULT 0,
  followingCount INT NOT NULL DEFAULT 0,
  lastActiveAt   DATETIME,
  streakDays     INT NOT NULL DEFAULT 0,
  createdAt      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ── v1.5: Drafts ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS im_community_drafts (
  id          VARCHAR(30) PRIMARY KEY,
  authorId    VARCHAR(36) NOT NULL,
  boardSlug   VARCHAR(50),
  title       VARCHAR(200),
  contentJson LONGTEXT,
  content     TEXT,
  createdAt   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  expiresAt   DATETIME NOT NULL,

  INDEX idx_draft_author (authorId, updatedAt)
);

-- ── v1.5: ALTER existing tables ────────────────────────────────────

ALTER TABLE im_community_posts ADD COLUMN IF NOT EXISTS contentJson LONGTEXT AFTER contentHtml;
