-- v2.0 07-C.6: append-only IM asset revision snapshots.
-- Each IMAsset.revision value gets a point-in-time metadata/storage snapshot.

CREATE TABLE IF NOT EXISTS im_asset_revisions (
  id VARCHAR(30) NOT NULL PRIMARY KEY,
  assetId VARCHAR(30) NOT NULL,
  workspaceId VARCHAR(30) NOT NULL,
  revision INT NOT NULL,
  contentHash CHAR(64) NOT NULL,
  storageUri VARCHAR(512) NOT NULL,
  sizeBytes BIGINT NULL,
  mime VARCHAR(128) NULL,
  kind VARCHAR(32) NOT NULL,
  ownerImUserId VARCHAR(30) NOT NULL,
  sourceAgentImUserId VARCHAR(30) NULL,
  sourceTaskId VARCHAR(30) NULL,
  metadata TEXT NOT NULL,
  parentAssetId VARCHAR(30) NULL,
  derivationKind VARCHAR(32) NULL,
  ingestStatus VARCHAR(32) NOT NULL,
  ingestVersion INT NOT NULL,
  ingestError TEXT NULL,
  cdnUrl VARCHAR(500) NULL,
  thumbnailUrl VARCHAR(500) NULL,
  previewUrls JSON NULL,
  previewAssetId VARCHAR(30) NULL,
  folderPath VARCHAR(700) NULL,
  filename VARCHAR(500) NULL,
  sourceRef VARCHAR(500) NULL,
  sourceKind VARCHAR(32) NULL,
  sourceMetadata TEXT NULL,
  visibility VARCHAR(50) NOT NULL,
  aclJson TEXT NULL,
  description VARCHAR(500) NULL,
  deletedAt DATETIME(3) NULL,
  createdByImUserId VARCHAR(30) NULL,
  reason VARCHAR(64) NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_im_asset_revisions_asset
    FOREIGN KEY (assetId) REFERENCES im_assets(id)
    ON DELETE CASCADE,
  UNIQUE KEY uq_im_asset_revisions_asset_revision (assetId, revision),
  KEY idx_im_asset_revisions_ws_asset_revision (workspaceId, assetId, revision),
  KEY idx_im_asset_revisions_ws_created (workspaceId, createdAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
