import type {
  ContainerInfo,
  DaemonDispatchArgs,
  DaemonDispatchResult,
  InstallAgentArgs,
  InstallAgentResult,
  ProvisionContainerArgs,
  ProvisionedContainer,
  RunCmdArgs,
  RunCmdResult,
} from '@/lib/k8s-sandbox';
import type { SandboxStatus } from './state-machine';

/**
 * Release 200 §4.4 — snapshot contract (canonicalised here, not in k8s-sandbox).
 *
 * v200 defaults to `fs-manifest` (daemon-first file digest list); `image`
 * is reserved for the Kaniko commit path (deferred, see 08 §9.2 B1).
 */
export type SnapshotKind = 'image' | 'fs-manifest';

export interface SnapshotRequest {
  /** Default 'fs-manifest' in v200. Use 'image' to request Kaniko commit. */
  kind?: SnapshotKind;
  /** Image-mode only: tag suffix appended to the repo. Ignored for fs-manifest. */
  tag?: string;
  /** Image-mode only: optional human-readable annotation persisted on the row. */
  comment?: string;
  /** Image-mode only: target registry repo. Defaults to pod name. */
  repo?: string;
  /**
   * fs-manifest-mode only (advisory — v200 daemon ignores these and
   * always walks `snapshotRoot`; future daemon versions will respect them).
   */
  includeGlobs?: string[];
  excludeGlobs?: string[];
  /** fs-manifest-mode only (advisory) — override the walk root. */
  root?: string;
}

export interface FsManifestEntry {
  /** Relative path from the manifest root. */
  path: string;
  /** Hex-encoded SHA-256 of the file bytes. */
  sha256: string;
  sizeBytes: number;
  /** Unix epoch ms (matches daemon mtime field). */
  mtime?: number;
}

export interface SnapshotResult {
  /** Cuid generated by the adapter — caller persists this as IMContainerSnapshot.id. */
  snapshotId: string;
  kind: SnapshotKind;
  /** image-mode: full image ref (`repo:tag`). */
  imageRef?: string;
  /** image-mode: registry digest. */
  digest?: string;
  /** image-mode: pushed image size. fs-manifest: sum of file sizes. */
  sizeBytes?: number;
  /** fs-manifest-mode: walked entries + aggregate stats. */
  manifest?: {
    rootPath: string;
    files: FsManifestEntry[];
    count: number;
    totalBytes: number;
    generatedAt: string;
  };
}

export type SandboxProviderKind = 'k8s' | 'e2b' | 'docker-host';
export type SandboxRuntimeModel = 'ephemeral' | 'persistent';

export interface SandboxProviderCapabilities {
  readonly runtimeModel: SandboxRuntimeModel;
  readonly supportsSnapshots: boolean;
  readonly supportsDaemonDispatch: boolean;
  readonly supportsAgentInstall: boolean;
  readonly supportsLogs: boolean;
  readonly supportsPortForwarding: boolean;
}

export interface ExecutionEnvironment {
  readonly id: string;
  readonly provider: SandboxProviderKind;
  readonly status: SandboxStatus;
  readonly gatewayUrl?: string | null;
  readonly metadata?: Record<string, unknown>;
}

export interface ProvisionEnvironmentInput {
  id: string;
  image?: string;
  environment?: Record<string, string>;
  cpuRequest?: string;
  cpuLimit?: string;
  memoryRequest?: string;
  memoryLimit?: string;
}

export interface SandboxProvider {
  readonly kind: SandboxProviderKind;
  readonly capabilities: SandboxProviderCapabilities;
  getEnvironment(id: string): Promise<ExecutionEnvironment | null>;
  removeEnvironment(id: string): Promise<void>;
}

/**
 * Release 200 §4.3 — ephemeral run contract.
 *
 * `RunRequest` is the input to `EphemeralExecutor.run()` (T10). It targets
 * the "fire one container, get stdout/stderr/exitCode back" flow used by
 * `POST /api/runs`. The richer `inputs`/`outputs`/`stream` fields described
 * in 08 §4.3 are reserved for future versions — v200 docker-host rejects
 * them with `ProviderError('invalid_config')`.
 */
export interface RunRequest {
  /** OCI image ref. Defaults to 'alpine:latest' for docker-host when omitted. */
  image?: string;
  /** Command + args (argv). Must be non-empty. */
  command: string[];
  /** Env vars injected into the container. */
  env?: Record<string, string>;
  /** WORKDIR inside the container. */
  workingDir?: string;
  /** Hard timeout for the run. Defaults to 60s. */
  timeoutMs?: number;
  /** UTF-8 string fed to the container's stdin (closed afterwards). */
  stdin?: string;
}

/**
 * Result of a single ephemeral run. `runId` is generated by the executor
 * (24-char alphanum cuid-shape to fit `im_sandbox_runs.id varchar(30)`).
 */
export interface RunResult {
  runId: string;
  exitCode: number | null;
  stdout: string;
  stderr: string;
  durationMs: number;
  /** Provider-native references for debug (containerName, image, sandboxId, …). */
  providerRefs?: Record<string, unknown>;
}

export interface EphemeralExecutor extends SandboxProvider {
  readonly capabilities: SandboxProviderCapabilities & { readonly runtimeModel: 'ephemeral' };
  /**
   * Legacy v190 path — provision-then-exec on a pre-existing environment.
   * Kept for compatibility with the original interface shape. v200 docker-host
   * and e2b implementations do not use this path (they throw); the live path
   * is `run()`.
   */
  execute(input: ProvisionEnvironmentInput, command: RunCmdArgs): Promise<RunCmdResult>;
  /**
   * Release 200 §4.3 / T10 — one-shot ephemeral run. Spawns a container,
   * runs `command`, returns stdout/stderr/exitCode + duration. The container
   * is destroyed after the run (docker `--rm`, e2b `sandbox.close()`).
   */
  run(request: RunRequest): Promise<RunResult>;
  /**
   * Optional liveness probe — used by `/api/runs` for graceful degradation
   * checks. Implementations should NOT throw on unhealthy; return ok=false.
   */
  ping?(): Promise<{ ok: boolean; latencyMs: number; error?: string }>;
}

/**
 * Release 200 §5.4 — daemon health probe result.
 *
 * `healthy` is the graceful-degrade Ready judgment (status==='ok' AND
 * (readyForDispatch===undefined OR readyForDispatch===true)). Adapters
 * MUST NOT throw on probe failure — they return `healthy=false` with
 * `error` populated. Throws are reserved for structural conditions
 * (pod missing → ProviderError('not_found'), exec API unavailable →
 * ProviderError('daemon_unreachable')).
 */
export interface ProbeDaemonResult {
  /** True iff the daemon reports it can dispatch tasks. */
  healthy: boolean;
  /** Wall-clock ms between probe start and probe response. */
  latencyMs: number;
  /** Daemon's self-reported id (when known). */
  daemonId?: string;
  /** Daemon binary version (Release 200 — new field). */
  daemonVersion?: string;
  /** Per-Release-200 Ready signal; undefined on legacy daemons. */
  readyForDispatch?: boolean;
  /** Raw /healthz response body for caller-side debug logging. */
  raw?: unknown;
  /** Failure reason when `healthy=false`; absent on success. */
  error?: string;
}

export interface PersistentRuntime extends SandboxProvider {
  readonly capabilities: SandboxProviderCapabilities & { readonly runtimeModel: 'persistent' };
  provisionEnvironment(input: ProvisionEnvironmentInput): Promise<ExecutionEnvironment>;
  /**
   * Scoped-key provisioning path. Used by `POST /api/sandboxes` which mints
   * a per-task API key + injects CLOUD_API_BASE/WORKSPACE_ID/USER_ID into
   * the daemon env. The K8s adapter delegates to `k8sSandbox.provisionContainer`.
   * Non-K8s providers (e2b/docker-host) may reject this with a
   * `ProviderError(code='invalid_config')` if scoped-key minting isn't
   * meaningful for their runtime model.
   */
  provisionContainer(args: ProvisionContainerArgs): Promise<{ container: ProvisionedContainer }>;
  /**
   * Raw container inspection — returns the provider-native `ContainerInfo`
   * (raw status string, gateway URL) without going through the
   * normalised `ExecutionEnvironment` shape. Returns `null` when the
   * underlying container does not exist. Used by `GET /api/sandboxes/:id`
   * to surface the live raw status alongside the DB row.
   */
  inspect(id: string): Promise<{ container: ContainerInfo } | null>;
  startEnvironment(id: string): Promise<ExecutionEnvironment>;
  stopEnvironment(id: string): Promise<ExecutionEnvironment>;
  runCommand(id: string, command: RunCmdArgs): Promise<RunCmdResult>;
  dispatchDaemon(id: string, payload: DaemonDispatchArgs): Promise<DaemonDispatchResult>;
  installAgent(id: string, payload: InstallAgentArgs): Promise<InstallAgentResult>;
  snapshot(id: string, payload?: SnapshotRequest): Promise<SnapshotResult>;
  getLogs(id: string, options?: { tailLines?: number }): Promise<string>;
  /**
   * Release 200 §5.4 — actively probe the daemon's `/healthz`.
   *
   * Returns a structured `ProbeDaemonResult` (does NOT throw for
   * daemon-unhealthy). Reconciler (S5) consumes this every 30s to drive
   * `IMContainer.daemonHealthMisses` / `lastDaemonHealthAt`. Probe-time
   * structural failures (pod missing, provider unreachable) surface as
   * `ProviderError`.
   */
  probeDaemon(id: string): Promise<ProbeDaemonResult>;
}
