/**
 * @prismer/wire — PARA TypeScript types
 *
 * Exported TS types inferred from Zod schemas (where possible) plus
 * hand-written interfaces for shapes that are awkward to infer.
 *
 * D12 canonical types (PermissionMode, PermissionRule, PermissionRuleSource)
 * are re-exported from @prismer/sandbox-runtime — the single source of truth
 * per docs/version190/04-sandbox-permissions.md §5.1.1.
 */

import { z } from 'zod';
import {
  AgentDescriptorSchema,
  ParaEventSchema,
  PermissionBehaviorSchema,
  SkillSourceSchema,
} from './schemas.js';

// ─── D12 canonical types — imported from @prismer/sandbox-runtime ─────────

/** PermissionMode enum type (6 values). Single source of truth: sandbox-runtime. */
export type { PermissionMode } from '@prismer/sandbox-runtime';

/** PermissionRuleSource enum type (8 values). Single source of truth: sandbox-runtime. */
export type { PermissionRuleSource } from '@prismer/sandbox-runtime';

/** PermissionRule — structured value { tool, pattern? }. Single source of truth: sandbox-runtime. */
export type { PermissionRule } from '@prismer/sandbox-runtime';

// ─── Inferred types from schemas ──────────────────────────────────────────

/** All 47 PARA events as a discriminated union type. */
export type ParaEvent = z.infer<typeof ParaEventSchema>;

/** PermissionBehavior enum type (allow | deny | ask). */
export type PermissionBehavior = z.infer<typeof PermissionBehaviorSchema>;

// ─── SkillSource — 6 variants per §4.3 ───────────────────────────────────

/**
 * SkillSource — tagged union with 6 variants.
 *
 * Resolution priority (highest to lowest):
 *   workspace > project > user > plugin > bundled > registry
 */
export type SkillSource = z.infer<typeof SkillSourceSchema>;

// ─── AgentDescriptor — hand-written interface (more readable) ─────────────

/**
 * AgentDescriptor — stable per-agent identity registered at session start.
 * Matches the spec interface at §4.3 lines 214-222.
 */
export interface AgentDescriptor {
  /** Stable identifier generated by the adapter (e.g. "claude-code@MacBook-Pro"). */
  id: string;
  /** Adapter identifier (e.g. "claude-code" | "codex" | "luminclaw"). */
  adapter: string;
  /** Adapter version string. */
  version: string;
  /** PARA Tier numbers supported, e.g. [1, 2, 3, 4, 5, 6, 7]. */
  tiersSupported: number[];
  /** Capability tags, e.g. ["code", "shell", "mcp", "approval"]. */
  capabilityTags: string[];
  /** Absolute workspace path; virtual path when sandboxed. */
  workspace: string;
  /** Optional workspace group (introduced in Round 3 for luminpulse). */
  workspaceGroup?: string;
}

// Verify the hand-written interface is compatible with the Zod schema
type _AgentDescriptorCheck = z.infer<typeof AgentDescriptorSchema> extends AgentDescriptor
  ? AgentDescriptor extends z.infer<typeof AgentDescriptorSchema>
    ? true
    : false
  : false;
const _check: _AgentDescriptorCheck = true;
void _check;

// ─── Convenience per-event types ──────────────────────────────────────────

export type AgentRegisterEvent = Extract<ParaEvent, { type: 'agent.register' }>;
export type AgentSessionStartedEvent = Extract<ParaEvent, { type: 'agent.session.started' }>;
export type AgentSessionResetEvent = Extract<ParaEvent, { type: 'agent.session.reset' }>;
export type AgentSessionEndedEvent = Extract<ParaEvent, { type: 'agent.session.ended' }>;
export type AgentSubagentStartedEvent = Extract<ParaEvent, { type: 'agent.subagent.started' }>;
export type AgentSubagentEndedEvent = Extract<ParaEvent, { type: 'agent.subagent.ended' }>;
export type AgentStateEvent = Extract<ParaEvent, { type: 'agent.state' }>;
export type AgentTiersUpdateEvent = Extract<ParaEvent, { type: 'agent.tiers.update' }>;
export type AgentPromptSubmitEvent = Extract<ParaEvent, { type: 'agent.prompt.submit' }>;
export type AgentLlmPreEvent = Extract<ParaEvent, { type: 'agent.llm.pre' }>;
export type AgentLlmPostEvent = Extract<ParaEvent, { type: 'agent.llm.post' }>;
export type AgentTurnStepEvent = Extract<ParaEvent, { type: 'agent.turn.step' }>;
export type AgentTurnEndEvent = Extract<ParaEvent, { type: 'agent.turn.end' }>;
export type AgentTurnFailureEvent = Extract<ParaEvent, { type: 'agent.turn.failure' }>;
export type AgentMessageEvent = Extract<ParaEvent, { type: 'agent.message' }>;
export type AgentChannelInboundEvent = Extract<ParaEvent, { type: 'agent.channel.inbound' }>;
export type AgentChannelOutboundSentEvent = Extract<ParaEvent, { type: 'agent.channel.outbound.sent' }>;
export type AgentChannelTranscribedEvent = Extract<ParaEvent, { type: 'agent.channel.transcribed' }>;
export type AgentChannelPreprocessedEvent = Extract<ParaEvent, { type: 'agent.channel.preprocessed' }>;
export type AgentToolPreEvent = Extract<ParaEvent, { type: 'agent.tool.pre' }>;
export type AgentToolPostEvent = Extract<ParaEvent, { type: 'agent.tool.post' }>;
export type AgentToolFailureEvent = Extract<ParaEvent, { type: 'agent.tool.failure' }>;
export type AgentElicitationRequestEvent = Extract<ParaEvent, { type: 'agent.elicitation.request' }>;
export type AgentElicitationResultEvent = Extract<ParaEvent, { type: 'agent.elicitation.result' }>;
export type AgentApprovalRequestEvent = Extract<ParaEvent, { type: 'agent.approval.request' }>;
export type AgentApprovalResultEvent = Extract<ParaEvent, { type: 'agent.approval.result' }>;
export type AgentApprovalDeniedEvent = Extract<ParaEvent, { type: 'agent.approval.denied' }>;
export type AgentTaskCreatedEvent = Extract<ParaEvent, { type: 'agent.task.created' }>;
export type AgentTaskCompletedEvent = Extract<ParaEvent, { type: 'agent.task.completed' }>;
export type AgentTeammateIdleEvent = Extract<ParaEvent, { type: 'agent.teammate.idle' }>;
export type AgentCommandEvent = Extract<ParaEvent, { type: 'agent.command' }>;
export type AgentCompactPreEvent = Extract<ParaEvent, { type: 'agent.compact.pre' }>;
export type AgentCompactPostEvent = Extract<ParaEvent, { type: 'agent.compact.post' }>;
export type AgentInstructionsLoadedEvent = Extract<ParaEvent, { type: 'agent.instructions.loaded' }>;
export type AgentBootstrapInjectedEvent = Extract<ParaEvent, { type: 'agent.bootstrap.injected' }>;
export type AgentFsOpEvent = Extract<ParaEvent, { type: 'agent.fs.op' }>;
export type AgentFileWatchedEvent = Extract<ParaEvent, { type: 'agent.file.watched' }>;
export type AgentCwdChangedEvent = Extract<ParaEvent, { type: 'agent.cwd.changed' }>;
export type AgentConfigChangedEvent = Extract<ParaEvent, { type: 'agent.config.changed' }>;
export type AgentWorktreeCreatedEvent = Extract<ParaEvent, { type: 'agent.worktree.created' }>;
export type AgentWorktreeRemovedEvent = Extract<ParaEvent, { type: 'agent.worktree.removed' }>;
export type AgentNotificationEvent = Extract<ParaEvent, { type: 'agent.notification' }>;
export type AgentSkillActivatedEvent = Extract<ParaEvent, { type: 'agent.skill.activated' }>;
export type AgentSkillDeactivatedEvent = Extract<ParaEvent, { type: 'agent.skill.deactivated' }>;
export type AgentSkillProposedEvent = Extract<ParaEvent, { type: 'agent.skill.proposed' }>;
export type AgentSkillInstalledEvent = Extract<ParaEvent, { type: 'agent.skill.installed' }>;
export type AgentSkillUninstalledEvent = Extract<ParaEvent, { type: 'agent.skill.uninstalled' }>;

/** Union of all event type string literals. */
export type ParaEventType = ParaEvent['type'];
