/**
 * ChuangLan 253.com SMS Service — Chinese mainland template SMS
 *
 * Env vars (both naming schemes accepted for portability — luminpulse style
 * `SMS_*` takes priority, falls back to `CHUANGLAN_*`):
 *   SMS_ACCOUNT     | CHUANGLAN_API_USER     account username
 *   SMS_PASSWORD    | CHUANGLAN_API_KEY      account password/key
 *   SMS_TEMPLATE_ID | CHUANGLAN_TEMPLATE_ID  template ID (default 1020380677)
 *   SMS_API_URL     | CHUANGLAN_API_URL      override endpoint
 */

import { createModuleLogger } from '@/lib/logger';

const log = createModuleLogger('SMS');

/** Validate Chinese mainland mobile number (11 digits starting with 1[3-9]) */
export function isValidChinesePhone(phone: string): boolean {
  return /^1[3-9]\d{9}$/.test(normalizePhone(phone));
}

/** Strip +86 prefix, spaces, dashes → bare 11-digit number */
export function normalizePhone(phone: string): string {
  let p = phone.replace(/[\s\-()]/g, '');
  if (p.startsWith('+86')) p = p.slice(3);
  if (p.startsWith('86') && p.length === 13) p = p.slice(2);
  if (p.startsWith('0086')) p = p.slice(4);
  return p;
}

interface SmsResult {
  success: boolean;
  error?: string;
  msgId?: string;
}

/**
 * Send a 6-digit verification code to a Chinese mobile via ChuangLan.
 * The CODE itself is GENERATED by the caller (local-auth.generateSmsCode);
 * this function only delivers it via the SMS provider.
 */
export async function sendSmsCode(phone: string, code: string): Promise<SmsResult> {
  const account = process.env.SMS_ACCOUNT ?? process.env.CHUANGLAN_API_USER;
  const password = process.env.SMS_PASSWORD ?? process.env.CHUANGLAN_API_KEY;
  const apiUrl =
    process.env.SMS_API_URL ?? process.env.CHUANGLAN_API_URL ?? 'https://smssh.253.com/msg/sms/v2/tpl/send';
  const templateId = process.env.SMS_TEMPLATE_ID ?? process.env.CHUANGLAN_TEMPLATE_ID ?? '1020380677';

  if (!account || !password) {
    log.error('SMS credentials not configured (set SMS_ACCOUNT/SMS_PASSWORD or CHUANGLAN_API_USER/CHUANGLAN_API_KEY)');
    return { success: false, error: 'SMS service not configured' };
  }

  const normalized = normalizePhone(phone);
  if (!isValidChinesePhone(normalized)) {
    return { success: false, error: 'Invalid phone number' };
  }

  const body = {
    account,
    password,
    templateId,
    templateParamJson: JSON.stringify([{ param1: code }]),
    phoneNumbers: normalized,
  };

  log.info({ phone: normalized, templateId }, 'Sending SMS');

  try {
    const res = await fetch(apiUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      log.error({ status: res.status, body: text.slice(0, 200) }, 'SMS API HTTP error');
      return { success: false, error: `HTTP ${res.status}` };
    }

    const data = (await res.json()) as { code?: string; msgId?: string; msg?: string; errorMsg?: string };

    if (String(data.code) === '000000') {
      log.info({ phone: normalized, msgId: data.msgId }, 'SMS sent successfully');
      return { success: true, msgId: data.msgId };
    }

    log.error({ code: data.code, msg: data.msg, errorMsg: data.errorMsg }, 'SMS API returned error');
    return { success: false, error: data.errorMsg || data.msg || `SMS error code: ${data.code}` };
  } catch (err) {
    log.error({ err }, 'SMS send failed');
    return { success: false, error: err instanceof Error ? err.message : 'SMS send failed' };
  }
}
