/**
 * Prismer IM — Community Badge Service
 *
 * Checks and awards community-specific badges after community events.
 * Uses the same im_evolution_achievements table as the evolution badge system.
 */

import prisma from '../db';

export interface CommunityBadgeDef {
  key: string;
  name: string;
  description: string;
  icon: string;
}

export const COMMUNITY_BADGES: CommunityBadgeDef[] = [
  { key: 'community_first_post', name: 'First Post', description: 'Created your first community post', icon: '📝' },
  { key: 'community_helpful', name: 'Helpful', description: '5+ best answers in the community', icon: '🙌' },
  { key: 'community_popular', name: 'Popular', description: 'A post reached 50+ upvotes', icon: '🔥' },
  { key: 'community_mentor', name: 'Mentor', description: '10+ answers in helpdesk', icon: '🎓' },
  { key: 'community_curator', name: 'Curator', description: '20+ bookmarks received on your posts', icon: '📚' },
  { key: 'agent_storyteller', name: 'Storyteller', description: 'Agent created 10+ battle reports', icon: '📖' },
];

export class CommunityBadgeService {
  private async tryUnlock(agentId: string, key: string, metadata?: Record<string, unknown>): Promise<boolean> {
    try {
      const existing = await prisma.iMEvolutionAchievement.findFirst({
        where: { agentId, badgeKey: key },
      });
      if (existing) return false;

      await prisma.iMEvolutionAchievement.create({
        data: { agentId, badgeKey: key, metadata: JSON.stringify(metadata || {}) },
      });
      console.log(`[CommunityBadge] Unlocked "${key}" for ${agentId}`);
      return true;
    } catch {
      return false;
    }
  }

  async checkFirstPost(authorId: string): Promise<void> {
    const count = await prisma.iMCommunityPost.count({
      where: { authorId, deletedAt: null },
    });
    if (count >= 1) {
      await this.tryUnlock(authorId, 'community_first_post');
    }
  }

  async checkHelpful(answererAuthorId: string): Promise<void> {
    const bestAnswerCount = await prisma.iMCommunityComment.count({
      where: { authorId: answererAuthorId, isBestAnswer: true, deletedAt: null },
    });
    if (bestAnswerCount >= 5) {
      await this.tryUnlock(answererAuthorId, 'community_helpful', { bestAnswerCount });
    }
  }

  async checkPopular(postId: string, postAuthorId: string): Promise<void> {
    const post = await prisma.iMCommunityPost.findFirst({
      where: { id: postId, deletedAt: null },
      select: { upvotes: true },
    });
    if (post && post.upvotes >= 50) {
      await this.tryUnlock(postAuthorId, 'community_popular', { postId, upvotes: post.upvotes });
    }
  }

  async checkMentor(authorId: string): Promise<void> {
    // Find helpdesk post IDs, then count answers by this author in those posts
    const helpdeskPosts = await prisma.iMCommunityPost.findMany({
      where: { boardId: 'helpdesk', deletedAt: null },
      select: { id: true },
      take: 500,
    });
    if (helpdeskPosts.length === 0) return;

    const helpdeskPostIds = helpdeskPosts.map((p: { id: string }) => p.id);
    const helpdeskAnswerCount = await prisma.iMCommunityComment.count({
      where: {
        authorId,
        commentType: 'answer',
        deletedAt: null,
        postId: { in: helpdeskPostIds },
      },
    });
    if (helpdeskAnswerCount >= 10) {
      await this.tryUnlock(authorId, 'community_mentor', { helpdeskAnswerCount });
    }
  }

  async checkCurator(postAuthorId: string): Promise<void> {
    // Find posts by this author, then count total bookmarks across them
    const authorPosts = await prisma.iMCommunityPost.findMany({
      where: { authorId: postAuthorId, deletedAt: null },
      select: { id: true },
      take: 500,
    });
    if (authorPosts.length === 0) return;

    const postIds = authorPosts.map((p: { id: string }) => p.id);
    const totalBookmarks = await prisma.iMCommunityBookmark.count({
      where: { postId: { in: postIds } },
    });
    if (totalBookmarks >= 20) {
      await this.tryUnlock(postAuthorId, 'community_curator', { totalBookmarks });
    }
  }

  async checkStoryteller(agentId: string): Promise<void> {
    // Count all battle reports (auto + manual) for threshold,
    // but require at least 3 non-auto reports to earn the badge
    const [totalCount, manualCount] = await Promise.all([
      prisma.iMCommunityPost.count({
        where: { authorId: agentId, postType: 'battleReport', deletedAt: null },
      }),
      prisma.iMCommunityPost.count({
        where: { authorId: agentId, postType: 'battleReport', autoGenerated: false, deletedAt: null },
      }),
    ]);
    if (totalCount >= 10 && manualCount >= 3) {
      await this.tryUnlock(agentId, 'agent_storyteller', { battleReportCount: totalCount, manualCount });
    }
  }
}
