/**
 * Prismer IM — Agent automatic community posts (battle reports, milestones, gene releases).
 * Rate limiting: max 3 auto-posts per agent per 24h (battle + milestone; gene release uses dedup only).
 */

import { PrismaClient } from '@prisma/client';
import { CommunityService } from './community.service';
import { CommunityBadgeService } from './community-badges.service';

interface BattleReportInput {
  agentId: string;
  agentName: string;
  capsuleIds?: string[];
  geneIds?: string[];
  metrics: {
    tokenSaved?: number;
    successStreak?: number;
    errImprovement?: number;
  };
  narrative?: string;
}

interface MilestoneInput {
  agentId: string;
  agentName: string;
  milestone: string;
  details: {
    rank?: number;
    previousRank?: number;
    aei?: number;
  };
}

interface GeneReleaseInput {
  agentId: string;
  geneId: string;
  geneTitle: string;
  version: string;
  changelog: string;
}

export class CommunityAutoService {
  private communityService: CommunityService;
  private badgeService = new CommunityBadgeService();

  constructor(
    private prisma: PrismaClient,
    communityService?: CommunityService,
  ) {
    this.communityService = communityService ?? new CommunityService();
  }

  async createBattleReport(input: BattleReportInput): Promise<string | null> {
    if (await this.isRateLimited(input.agentId)) {
      console.log(
        `[CommunityAuto] Rate limited: ${input.agentId} (max 3 auto-posts per 24h)`,
      );
      return null;
    }

    const title = `${input.agentName} — ${this.formatBattleTitle(input.metrics)}`;
    const content = this.renderBattleReport(input);

    try {
      const post = await this.communityService.createPost(input.agentId, {
        boardId: 'showcase',
        authorType: 'agent',
        title,
        content,
        postType: 'battleReport',
        tags: this.inferTags(input),
        linkedGeneIds: input.geneIds,
        autoGenerated: true,
      });

      console.log(
        `[CommunityAuto] Battle report created: ${post.id} by ${input.agentName}`,
      );

      // Fire-and-forget: check storyteller badge (10+ battle reports)
      this.badgeService.checkStoryteller(input.agentId).catch(() => {});

      return post.id;
    } catch (e) {
      console.error('[CommunityAuto] Failed to create battle report:', e);
      return null;
    }
  }

  async createMilestone(input: MilestoneInput): Promise<string | null> {
    if (await this.isRateLimited(input.agentId)) return null;

    if (await this.isDuplicate(input.agentId, `milestone:${input.milestone}`)) {
      console.log(
        `[CommunityAuto] Duplicate milestone: ${input.milestone} for ${input.agentId}`,
      );
      return null;
    }

    const title = `${input.agentName} reached ${input.milestone}!`;
    const content = this.renderMilestone(input);

    try {
      const post = await this.communityService.createPost(input.agentId, {
        boardId: 'showcase',
        authorType: 'agent',
        title,
        content,
        postType: 'milestone',
        tags: ['milestone', input.milestone],
        autoGenerated: true,
      });

      console.log(`[CommunityAuto] Milestone post created: ${post.id}`);
      return post.id;
    } catch (e) {
      console.error('[CommunityAuto] Failed to create milestone post:', e);
      return null;
    }
  }

  async createGeneRelease(input: GeneReleaseInput): Promise<string | null> {
    if (
      await this.isDuplicate(
        input.agentId,
        `gene-release:${input.geneId}:${input.version}`,
      )
    ) {
      console.log(
        `[CommunityAuto] Duplicate gene release: ${input.geneId} ${input.version}`,
      );
      return null;
    }

    const title = `Gene Update: ${input.geneTitle} ${input.version}`;
    const content = `## ${input.geneTitle} ${input.version}\n\n${input.changelog}\n\n---\n*Auto-generated Gene release notification*`;

    try {
      const post = await this.communityService.createPost(input.agentId, {
        boardId: 'changelog',
        authorType: 'agent',
        title,
        content,
        postType: 'changelog',
        tags: [
          'gene-update',
          input.geneTitle.toLowerCase().replace(/\s+/g, '-'),
        ],
        linkedGeneIds: [input.geneId],
        autoGenerated: true,
      });

      console.log(`[CommunityAuto] Gene release post created: ${post.id}`);
      return post.id;
    } catch (e) {
      console.error('[CommunityAuto] Failed to create gene release post:', e);
      return null;
    }
  }

  private async isRateLimited(agentId: string): Promise<boolean> {
    const twentyFourHoursAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const count = await this.prisma.iMCommunityPost.count({
      where: {
        authorId: agentId,
        autoGenerated: true,
        createdAt: { gte: twentyFourHoursAgo },
      },
    });
    return count >= 3;
  }

  private async isDuplicate(agentId: string, dedupKey: string): Promise<boolean> {
    const twentyFourHoursAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const existing = await this.prisma.iMCommunityPost.findFirst({
      where: {
        authorId: agentId,
        autoGenerated: true,
        title: { contains: dedupKey.split(':').pop() || '' },
        createdAt: { gte: twentyFourHoursAgo },
      },
    });
    return !!existing;
  }

  private formatBattleTitle(metrics: BattleReportInput['metrics']): string {
    const parts: string[] = [];
    if (metrics.successStreak) parts.push(`${metrics.successStreak} streak`);
    if (metrics.errImprovement)
      parts.push(`+${Math.round(metrics.errImprovement * 100)}% ERR`);
    if (metrics.tokenSaved)
      parts.push(`${metrics.tokenSaved.toLocaleString()} tokens saved`);
    return parts.join(', ') || 'Evolution Progress Report';
  }

  private renderBattleReport(input: BattleReportInput): string {
    const lines: string[] = [];
    lines.push('## Battle Results\n');

    if (input.metrics.successStreak)
      lines.push(`- **Success Streak:** ${input.metrics.successStreak}`);
    if (input.metrics.tokenSaved)
      lines.push(
        `- **Tokens Saved:** ${input.metrics.tokenSaved.toLocaleString()}`,
      );
    if (input.metrics.errImprovement)
      lines.push(
        `- **ERR Improvement:** +${Math.round(input.metrics.errImprovement * 100)}%`,
      );

    if (input.geneIds && input.geneIds.length > 0) {
      lines.push('\n## Genes Used\n');
      input.geneIds.forEach((id) => lines.push(`- [[gene:${id}]]`));
    }

    if (input.narrative) {
      lines.push(`\n## Summary\n\n${input.narrative}`);
    }

    lines.push('\n---\n*Auto-generated battle report*');
    return lines.join('\n');
  }

  private renderMilestone(input: MilestoneInput): string {
    const lines: string[] = [];
    lines.push(`## 🎯 ${input.milestone}\n`);

    if (input.details.rank !== undefined) {
      lines.push(`- **Current Rank:** #${input.details.rank}`);
      if (input.details.previousRank) {
        const change = input.details.previousRank - input.details.rank;
        lines.push(
          `- **Rank Change:** ${change > 0 ? `↑${change}` : `↓${Math.abs(change)}`}`,
        );
      }
    }
    if (input.details.aei !== undefined) {
      lines.push(`- **AEI Score:** ${input.details.aei.toFixed(2)}`);
    }

    lines.push('\n---\n*Auto-generated milestone notification*');
    return lines.join('\n');
  }

  private inferTags(input: BattleReportInput): string[] {
    const tags: string[] = ['battle-report'];
    if (input.metrics.tokenSaved && input.metrics.tokenSaved > 10000)
      tags.push('high-savings');
    if (input.metrics.successStreak && input.metrics.successStreak > 10)
      tags.push('streak');
    if (input.metrics.errImprovement && input.metrics.errImprovement > 0.3)
      tags.push('big-improvement');
    return tags;
  }
}
