/**
 * Prismer IM — Community Karma Service
 *
 * Trust-tiered reputation: vote/adoption events settle karma with actor-weighted
 * multipliers. Tier is derived from account age + published genes (not IMUser.trustTier).
 */

import type { PrismaClient } from "@prisma/client";
import { safeJsonParse } from "../utils/safe-json";

export type KarmaAction =
  | "post_upvote"
  | "post_downvote"
  | "comment_upvote"
  | "comment_downvote"
  | "best_answer"
  | "featured"
  | "gene_adopted";

export interface KarmaEvent {
  userId: string;
  action: KarmaAction;
  actorId: string;
  targetId: string;
  autoGenerated?: boolean;
}

const KARMA_VALUES: Record<KarmaAction, number> = {
  post_upvote: 5,
  post_downvote: -2,
  comment_upvote: 3,
  comment_downvote: -1,
  best_answer: 10,
  featured: 15,
  gene_adopted: 20,
};

const COMMUNITY_KARMA_KEY = "communityKarma";
const COMMUNITY_KARMA_PENDING_KEY = "communityKarmaPending";

interface PendingKarmaEntry {
  karma: number;
  action: KarmaAction;
  actorId: string;
  targetId: string;
  settleAfter: string; // ISO date string
}

export class CommunityKarmaService {
  constructor(private prisma: PrismaClient) {}

  async settleKarma(event: KarmaEvent): Promise<void> {
    const baseKarma = KARMA_VALUES[event.action] ?? 0;
    if (baseKarma === 0) return;

    const actorTier = await this.getTrustTier(event.actorId);
    const { weight, delay } = this.getSettlementConfig(actorTier);
    const ringMultiplier = await this.detectVoteRing(event.actorId, event.userId);
    // Reduce karma for auto-generated content (agent battle reports etc.)
    const autoMultiplier = event.autoGenerated ? 0.5 : 1;
    const effectiveKarma = Math.round(baseKarma * weight * ringMultiplier * autoMultiplier);
    if (effectiveKarma === 0) return;

    if (delay > 0) {
      await this.queueDeferredKarma(event.userId, {
        karma: effectiveKarma,
        action: event.action,
        actorId: event.actorId,
        targetId: event.targetId,
        settleAfter: new Date(Date.now() + delay * 24 * 60 * 60 * 1000).toISOString(),
      });
      console.log(
        `[CommunityKarma] Deferred karma: ${effectiveKarma} for ${event.userId} (actor tier ${actorTier}, delay ${delay}d)`,
      );
      return;
    }

    await this.applyKarma(event.userId, effectiveKarma);
    console.log(
      `[CommunityKarma] Settled ${effectiveKarma} karma for ${event.userId} (action: ${event.action}, actor tier: ${actorTier})`,
    );
  }

  private async applyKarma(userId: string, karma: number): Promise<void> {
    try {
      const user = await this.prisma.iMUser.findUnique({
        where: { id: userId },
        select: { metadata: true },
      });
      if (!user) return;

      const meta = safeJsonParse<Record<string, unknown>>(user.metadata, {});
      const current = Number(meta[COMMUNITY_KARMA_KEY]);
      const nextKarma = (Number.isFinite(current) ? current : 0) + karma;
      const nextMeta = { ...meta, [COMMUNITY_KARMA_KEY]: nextKarma };

      await this.prisma.iMUser.update({
        where: { id: userId },
        data: { metadata: JSON.stringify(nextMeta) },
      });
    } catch (e) {
      console.error("[CommunityKarma] Failed to apply karma:", e);
    }
  }

  private async queueDeferredKarma(userId: string, entry: PendingKarmaEntry): Promise<void> {
    try {
      const user = await this.prisma.iMUser.findUnique({
        where: { id: userId },
        select: { metadata: true },
      });
      if (!user) return;

      const meta = safeJsonParse<Record<string, unknown>>(user.metadata, {});
      const pending = Array.isArray(meta[COMMUNITY_KARMA_PENDING_KEY])
        ? (meta[COMMUNITY_KARMA_PENDING_KEY] as PendingKarmaEntry[])
        : [];
      pending.push(entry);
      const nextMeta = { ...meta, [COMMUNITY_KARMA_PENDING_KEY]: pending };

      await this.prisma.iMUser.update({
        where: { id: userId },
        data: { metadata: JSON.stringify(nextMeta) },
      });
    } catch (e) {
      console.error("[CommunityKarma] Failed to queue deferred karma:", e);
    }
  }

  /**
   * Settle all pending deferred karma entries whose settleAfter has passed.
   * Call this periodically (e.g. from the scheduler).
   */
  async settlePendingKarma(): Promise<number> {
    const now = new Date().toISOString();
    let settled = 0;

    try {
      const users = await this.prisma.iMUser.findMany({
        where: {
          metadata: { contains: COMMUNITY_KARMA_PENDING_KEY },
        },
        select: { id: true, metadata: true },
        take: 200,
      });

      for (const user of users) {
        const meta = safeJsonParse<Record<string, unknown>>(user.metadata, {});
        const pending = Array.isArray(meta[COMMUNITY_KARMA_PENDING_KEY])
          ? (meta[COMMUNITY_KARMA_PENDING_KEY] as PendingKarmaEntry[])
          : [];
        if (pending.length === 0) continue;

        const due = pending.filter((e) => e.settleAfter <= now);
        const remaining = pending.filter((e) => e.settleAfter > now);

        if (due.length === 0) continue;

        const totalKarma = due.reduce((sum, e) => sum + e.karma, 0);
        const current = Number(meta[COMMUNITY_KARMA_KEY]);
        const nextKarma = (Number.isFinite(current) ? current : 0) + totalKarma;
        const nextMeta = {
          ...meta,
          [COMMUNITY_KARMA_KEY]: nextKarma,
          [COMMUNITY_KARMA_PENDING_KEY]: remaining.length > 0 ? remaining : undefined,
        };
        if (remaining.length === 0) delete nextMeta[COMMUNITY_KARMA_PENDING_KEY];

        await this.prisma.iMUser.update({
          where: { id: user.id },
          data: { metadata: JSON.stringify(nextMeta) },
        });

        settled += due.length;
        console.log(
          `[CommunityKarma] Settled ${due.length} deferred karma entries for ${user.id} (total: ${totalKarma})`,
        );
      }
    } catch (e) {
      console.error("[CommunityKarma] settlePendingKarma error:", e);
    }

    return settled;
  }

  /**
   * Karma settlement tier from account tenure + published gene count.
   */
  async getTrustTier(userId: string): Promise<number> {
    try {
      const user = await this.prisma.iMUser.findUnique({
        where: { id: userId },
        select: { createdAt: true },
      });
      if (!user) return 0;

      const daysSinceCreation =
        (Date.now() - new Date(user.createdAt).getTime()) / (1000 * 60 * 60 * 24);

      const geneCount = await this.prisma.iMGene.count({
        where: { ownerAgentId: userId, visibility: "published" },
      });

      if (daysSinceCreation >= 90 && geneCount >= 1) return 3;
      if (daysSinceCreation >= 30 && geneCount >= 1) return 2;
      if (daysSinceCreation >= 7 && geneCount >= 1) return 1;
      return 0;
    } catch {
      return 0;
    }
  }

  private getSettlementConfig(tier: number): { weight: number; delay: number } {
    switch (tier) {
      case 0:
        return { weight: 0.3, delay: 7 };
      case 1:
        return { weight: 0.7, delay: 0 };
      case 2:
        return { weight: 1.0, delay: 0 };
      case 3:
        return { weight: 1.0, delay: 0 };
      default:
        return { weight: 0.3, delay: 7 };
    }
  }

  /**
   * Detect vote ring: if actorId has upvoted 5+ items by the same target author
   * within the last hour, halve the karma multiplier to discourage coordinated voting.
   */
  private async detectVoteRing(actorId: string, targetAuthorId: string): Promise<number> {
    try {
      const oneHourAgo = new Date(Date.now() - 60 * 60 * 1000);

      // Fetch recent upvotes by this actor
      const recentVotes = await this.prisma.iMCommunityVote.findMany({
        where: { userId: actorId, value: 1, createdAt: { gte: oneHourAgo } },
        select: { targetType: true, targetId: true },
        take: 50,
      });

      if (recentVotes.length < 5) return 1.0;

      // Resolve authors of voted-on items
      const postIds = recentVotes.filter((v) => v.targetType === 'post').map((v) => v.targetId);
      const commentIds = recentVotes.filter((v) => v.targetType === 'comment').map((v) => v.targetId);

      let matchCount = 0;

      if (postIds.length > 0) {
        matchCount += await this.prisma.iMCommunityPost.count({
          where: { id: { in: postIds }, authorId: targetAuthorId },
        });
      }
      if (commentIds.length > 0) {
        matchCount += await this.prisma.iMCommunityComment.count({
          where: { id: { in: commentIds }, authorId: targetAuthorId },
        });
      }

      if (matchCount >= 5) {
        console.log(
          `[CommunityKarma] Vote ring detected: ${actorId} → ${targetAuthorId} (${matchCount} upvotes in 1h)`,
        );
        return 0.5;
      }
    } catch {
      // Best-effort — fall through to normal multiplier
    }
    return 1.0;
  }

  async getUserKarma(userId: string): Promise<number> {
    try {
      const user = await this.prisma.iMUser.findUnique({
        where: { id: userId },
        select: { metadata: true },
      });
      if (user?.metadata == null) return 0;
      const meta = safeJsonParse<Record<string, unknown>>(user.metadata, {});
      const v = meta[COMMUNITY_KARMA_KEY];
      const n = typeof v === "number" ? v : Number(v);
      return Number.isFinite(n) ? n : 0;
    } catch {
      return 0;
    }
  }
}

export { KARMA_VALUES };
