/**
 * Prismer IM — Community Service
 *
 * Core service for the Evolution Community Forum.
 * Handles posts, comments, voting, bookmarks, tags, and board stats.
 *
 * Boards: showcase, genelab, helpdesk, ideas, changelog
 */

import { prisma } from '@/lib/prisma';
import { renderCommunityContent } from './community-markdown';
import { CommunityKarmaService } from './community-karma.service';
import { CommunityBadgeService } from './community-badges.service';
import { CommunityNotificationService } from './community-notification.service';
import type { RoomManager } from '../ws/rooms';
import { ServerEvents } from '../ws/events';
import { createModuleLogger } from '../../lib/logger';

const log = createModuleLogger('Community');

// ─── Types ──────────────────────────────────────────────────

interface CreatePostInput {
  boardId?: string;
  authorId: string;
  authorType?: string;
  title: string;
  content: string;
  contentHtml?: string;
  contentJson?: string;
  postType?: string;
  tags?: string[];
  linkedGeneIds?: string[];
  linkedSkillIds?: string[];
  linkedAgentId?: string;
  linkedCapsuleId?: string;
  attachments?: any[];
  autoGenerated?: boolean;
}

interface UpdatePostInput {
  title?: string;
  content?: string;
  contentHtml?: string;
  contentJson?: string;
  tags?: string[];
  postType?: string;
  status?: string;
  linkedGeneIds?: string[];
  linkedSkillIds?: string[];
  linkedAgentId?: string;
  linkedCapsuleId?: string;
  attachments?: any[];
  pinned?: boolean;
  featured?: boolean;
}

interface ListPostsOptions {
  boardId?: string;
  sort?: 'hot' | 'new' | 'top' | 'featured' | 'unsolved';
  period?: 'day' | 'week' | 'month' | 'all';
  authorType?: 'human' | 'agent' | 'all';
  postType?: string;
  tag?: string;
  authorId?: string;
  geneId?: string;
  q?: string;
  cursor?: string;
  page?: number;
  limit?: number;
}

interface CreateCommentInput {
  authorId: string;
  authorType?: string;
  content: string;
  contentHtml?: string;
  parentId?: string;
  commentType?: string;
  linkedGeneIds?: string[];
  metrics?: any;
  autoGenerated?: boolean;
}

interface ListCommentsOptions {
  sort?: 'time' | 'votes' | 'best_first';
  commentType?: 'all' | 'answer' | 'reply';
  cursor?: string;
  limit?: number;
}

interface CommunityStats {
  totalPosts: number;
  totalComments: number;
  activeAuthors7d: number;
  postsToday: number;
  trendingTags: { name: string; postCount: number }[];
}

// ─── Helpers ────────────────────────────────────────────────

function hotnessScore(upvotes: number, downvotes: number, createdAt: Date, autoGenerated: boolean): number {
  const score = upvotes - downvotes;
  const ageHours = (Date.now() - createdAt.getTime()) / (1000 * 60 * 60);
  const hotness = score / Math.pow(ageHours + 2, 1.5);
  return autoGenerated ? hotness * 0.7 : hotness;
}

function normalizeTags(tags: string[]): string[] {
  return [...new Set(tags.map((t) => t.toLowerCase().trim()).filter(Boolean))];
}

function periodToDate(period: string): Date | null {
  const now = new Date();
  switch (period) {
    case 'day':
      return new Date(now.getTime() - 24 * 60 * 60 * 1000);
    case 'week':
      return new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    case 'month':
      return new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    default:
      return null;
  }
}

// Board-aware default sort for comments
function defaultCommentSort(boardId: string): 'time' | 'votes' | 'best_first' {
  switch (boardId) {
    case 'helpdesk':
      return 'best_first';
    case 'genelab':
    case 'ideas':
      return 'votes';
    default:
      return 'time';
  }
}

// ─── Service ────────────────────────────────────────────────

export class CommunityService {
  private karmaService = new CommunityKarmaService(prisma as any);
  private badgeService = new CommunityBadgeService();
  private notificationService = new CommunityNotificationService();

  constructor(private readonly rooms: RoomManager | null = null) {}

  private async enrichWithAuthors<T extends { authorId: string }>(items: T[]): Promise<(T & { author?: any })[]> {
    if (items.length === 0) return items;
    const authorIds = [...new Set(items.map((i) => i.authorId))];
    const users = await prisma.iMUser.findMany({
      where: { id: { in: authorIds } },
      select: { id: true, username: true, displayName: true, role: true, avatarUrl: true },
    });
    type UserInfo = {
      id: string;
      username: string;
      displayName: string | null;
      role: string;
      avatarUrl: string | null;
    };
    const userMap = new Map<string, UserInfo>(users.map((u: UserInfo) => [u.id, u]));
    return items.map((item) => {
      const user = userMap.get(item.authorId);
      return {
        ...item,
        author: user
          ? { id: user.id, name: user.displayName || user.username, type: user.role, avatarUrl: user.avatarUrl }
          : undefined,
      };
    });
  }

  // ==================== Posts ====================

  async createPost(authorId: string, input: Omit<CreatePostInput, 'authorId'>) {
    const effectiveAuthorId = authorId;
    const tags = input.tags ? normalizeTags(input.tags) : [];

    const contentHtml = input.contentHtml ?? (await renderCommunityContent(input.content));

    const post = await prisma.iMCommunityPost.create({
      data: {
        boardId: input.boardId ?? null,
        authorId: effectiveAuthorId,
        authorType: input.authorType ?? 'human',
        title: input.title,
        content: input.content,
        contentHtml,
        contentJson: input.contentJson ?? null,
        postType: input.postType ?? 'discussion',
        tags: tags.length > 0 ? tags : undefined,
        linkedGeneIds: input.linkedGeneIds ?? undefined,
        linkedSkillIds: input.linkedSkillIds ?? undefined,
        linkedAgentId: input.linkedAgentId ?? null,
        linkedCapsuleId: input.linkedCapsuleId ?? null,
        attachments: input.attachments ?? undefined,
        autoGenerated: input.autoGenerated ?? false,
      },
    });

    if (tags.length > 0) {
      await this.linkTagsToPost(post.id, tags);
    }

    log.info(`Post created: ${post.id} in board=${input.boardId}`);

    // Fire-and-forget badge checks
    this.badgeService.checkFirstPost(effectiveAuthorId).catch(() => {});

    const [enriched] = await this.enrichWithAuthors([post]);
    return enriched;
  }

  async getPost(id: string) {
    const post = await prisma.iMCommunityPost.findFirst({
      where: { id, deletedAt: null },
    });
    if (!post) return null;

    prisma.iMCommunityPost.update({ where: { id }, data: { viewCount: { increment: 1 } } }).catch(() => {});

    const needsRerender =
      post.content && /^\|.+\|/m.test(post.content) && post.contentHtml && !post.contentHtml.includes('<table');
    if (needsRerender) {
      const freshHtml = await renderCommunityContent(post.content);
      (post as any).contentHtml = freshHtml;
      prisma.iMCommunityPost.update({ where: { id }, data: { contentHtml: freshHtml } }).catch(() => {});
    }

    const [enriched] = await this.enrichWithAuthors([post]);
    return enriched;
  }

  async listPosts(opts: ListPostsOptions = {}) {
    const limit = Math.min(opts.limit ?? 20, 50);
    const where: any = { deletedAt: null };

    if (opts.boardId) where.boardId = opts.boardId;
    if (opts.authorType && opts.authorType !== 'all') {
      where.authorType = opts.authorType;
    }
    if (opts.postType) where.postType = opts.postType;
    if (opts.authorId) where.authorId = opts.authorId;

    // Period filter
    if (opts.period && opts.period !== 'all') {
      const since = periodToDate(opts.period);
      if (since) where.createdAt = { gte: since };
    }

    // Tag filter — check tags JSON array
    // array_contains is MySQL/PG only; SQLite falls back to JS filtering after query
    const isMySQL = (process.env.DATABASE_URL || '').startsWith('mysql://');
    const jsTagFilter = opts.tag?.toLowerCase();
    const jsGeneFilter = opts.geneId;
    if (opts.tag && isMySQL) {
      where.tags = { path: '$', array_contains: opts.tag.toLowerCase() };
    }

    // Gene filter — search linkedGeneIds JSON
    if (opts.geneId && isMySQL) {
      where.linkedGeneIds = { path: '$', array_contains: opts.geneId };
    }

    // Text search — basic title/content contains
    if (opts.q) {
      where.OR = [{ title: { contains: opts.q } }, { content: { contains: opts.q } }];
    }

    // Sort-specific filters
    if (opts.sort === 'featured') {
      where.featured = true;
    } else if (opts.sort === 'unsolved') {
      where.status = 'active';
      where.postType = 'help';
    }

    // Determine ordering
    let orderBy: any;
    switch (opts.sort) {
      case 'new':
        orderBy = { createdAt: 'desc' as const };
        break;
      case 'top':
        orderBy = { upvotes: 'desc' as const };
        break;
      case 'featured':
        orderBy = { createdAt: 'desc' as const };
        break;
      case 'unsolved':
        orderBy = { createdAt: 'desc' as const };
        break;
      case 'hot':
      default:
        // Fetch extra then sort by hotness in JS
        orderBy = { createdAt: 'desc' as const };
        break;
    }

    // SQLite fallback: filter JSON arrays in JS after query
    const needsJsFilter = !isMySQL && (jsTagFilter || jsGeneFilter);
    const jsFilterFn = (post: any): boolean => {
      if (jsTagFilter) {
        const tags = typeof post.tags === 'string' ? JSON.parse(post.tags || '[]') : post.tags || [];
        if (!Array.isArray(tags) || !tags.some((t: string) => t?.toLowerCase() === jsTagFilter)) return false;
      }
      if (jsGeneFilter) {
        const gids =
          typeof post.linkedGeneIds === 'string' ? JSON.parse(post.linkedGeneIds || '[]') : post.linkedGeneIds || [];
        if (!Array.isArray(gids) || !gids.includes(jsGeneFilter)) return false;
      }
      return true;
    };

    const isHotSort = opts.sort === 'hot' || !opts.sort;

    if (isHotSort) {
      const page = Math.max(opts.page ?? 0, 0);
      let pool = await prisma.iMCommunityPost.findMany({
        where,
        orderBy,
        take: needsJsFilter ? (limit * 3 + 1) * 3 : limit * 3 + 1,
        skip: page * limit,
      });
      if (needsJsFilter) pool = pool.filter(jsFilterFn);
      pool.sort(
        (
          a: { upvotes: number; downvotes: number; createdAt: Date; autoGenerated: boolean },
          b: { upvotes: number; downvotes: number; createdAt: Date; autoGenerated: boolean },
        ) =>
          hotnessScore(b.upvotes, b.downvotes, b.createdAt, b.autoGenerated) -
          hotnessScore(a.upvotes, a.downvotes, a.createdAt, a.autoGenerated),
      );
      const sliced = pool.slice(0, limit);
      const hasMore = pool.length > limit;
      return {
        posts: await this.enrichWithAuthors(sliced),
        nextCursor: hasMore ? String(page + 1) : null,
      };
    }

    // Cursor-based pagination for deterministic sorts
    const cursorClause = opts.cursor ? { id: opts.cursor } : undefined;
    let posts = await prisma.iMCommunityPost.findMany({
      where,
      orderBy,
      take: needsJsFilter ? (limit + 1) * 3 : limit + 1,
      ...(cursorClause ? { cursor: cursorClause, skip: 1 } : {}),
    });
    if (needsJsFilter) posts = posts.filter(jsFilterFn);

    const hasMore = posts.length > limit;
    const result = hasMore ? posts.slice(0, limit) : posts;
    return {
      posts: await this.enrichWithAuthors(result),
      nextCursor: hasMore ? result[result.length - 1]?.id : null,
    };
  }

  async updatePost(id: string, authorId: string, input: UpdatePostInput) {
    const post = await prisma.iMCommunityPost.findFirst({
      where: { id, deletedAt: null },
    });
    if (!post) throw new Error('Post not found');
    if (post.authorId !== authorId) throw new Error('Only the author can update this post');

    const data: any = {};
    if (input.title !== undefined) data.title = input.title;
    if (input.content !== undefined) {
      data.content = input.content;
      data.contentHtml = input.contentHtml ?? (await renderCommunityContent(input.content));
    }
    if (input.contentJson !== undefined) data.contentJson = input.contentJson;
    if (input.postType !== undefined) data.postType = input.postType;
    if (input.status !== undefined) data.status = input.status;
    if (input.linkedGeneIds !== undefined) data.linkedGeneIds = input.linkedGeneIds;
    if (input.linkedSkillIds !== undefined) data.linkedSkillIds = input.linkedSkillIds;
    if (input.linkedAgentId !== undefined) data.linkedAgentId = input.linkedAgentId;
    if (input.linkedCapsuleId !== undefined) data.linkedCapsuleId = input.linkedCapsuleId;
    if (input.attachments !== undefined) data.attachments = input.attachments;
    if (input.pinned !== undefined) data.pinned = input.pinned;
    if (input.featured !== undefined) data.featured = input.featured;

    // Handle tag updates: replace old tags with new ones
    if (input.tags !== undefined) {
      const newTags = normalizeTags(input.tags);
      data.tags = newTags.length > 0 ? newTags : [];

      // Decrement old tag counts, remove old post-tag links, then re-link
      const oldTags = (Array.isArray(post.tags) ? post.tags : []) as string[];
      await this.unlinkTagsFromPost(post.id, oldTags);
      if (newTags.length > 0) {
        await this.linkTagsToPost(post.id, newTags);
      }
    }

    const updated = await prisma.iMCommunityPost.update({ where: { id }, data });
    log.info(`Post updated: ${id}`);
    const [enriched] = await this.enrichWithAuthors([updated]);
    return enriched;
  }

  async deletePost(id: string, deletedBy: string, role?: string): Promise<boolean> {
    const post = await prisma.iMCommunityPost.findFirst({
      where: { id, deletedAt: null },
    });
    if (!post) return false;
    if (post.authorId !== deletedBy && role !== 'admin') return false;

    await prisma.iMCommunityPost.update({
      where: { id },
      data: { deletedAt: new Date(), deletedBy },
    });

    const tags = (Array.isArray(post.tags) ? post.tags : []) as string[];
    if (tags.length > 0) {
      await this.unlinkTagsFromPost(id, tags);
    }

    log.info(`Post soft-deleted: ${id} by ${deletedBy}`);
    return true;
  }

  // ==================== Comments ====================

  async createComment(postId: string, authorId: string, input: Omit<CreateCommentInput, 'authorId'>) {
    const effectiveAuthorId = authorId;
    const post = await prisma.iMCommunityPost.findFirst({
      where: { id: postId, deletedAt: null },
    });
    if (!post) throw new Error('Post not found');

    if (input.parentId) {
      const parent = await prisma.iMCommunityComment.findFirst({
        where: { id: input.parentId, postId, deletedAt: null },
      });
      if (!parent) throw new Error('Parent comment not found');
    }

    const commentHtml = input.contentHtml ?? (await renderCommunityContent(input.content));

    const [comment] = await prisma.$transaction([
      prisma.iMCommunityComment.create({
        data: {
          postId,
          authorId: effectiveAuthorId,
          authorType: input.authorType ?? 'human',
          content: input.content,
          contentHtml: commentHtml,
          parentId: input.parentId ?? null,
          commentType: input.commentType ?? 'reply',
          linkedGeneIds: input.linkedGeneIds ?? undefined,
          metrics: input.metrics ?? undefined,
          autoGenerated: input.autoGenerated ?? false,
        },
      }),
      prisma.iMCommunityPost.update({
        where: { id: postId },
        data: { commentCount: { increment: 1 } },
      }),
    ]);

    log.info(`Comment created: ${comment.id} on post=${postId}`);

    // Notify post author about the reply (fire-and-forget)
    if (post.authorId !== effectiveAuthorId) {
      this.notificationService
        .notify(post.authorId, {
          type: 'reply',
          postId,
          postTitle: post.title,
          commentId: comment.id,
          actorId: effectiveAuthorId,
          actorName: effectiveAuthorId,
        })
        .catch((err: any) => log.error({ err }, 'Community async operation failed'));
      if (this.rooms) {
        this.rooms.sendToUser(
          post.authorId,
          ServerEvents.communityReply({
            postId,
            postTitle: post.title,
            commentId: comment.id,
            actorId: effectiveAuthorId,
          }),
        );
      }
    }

    // Push to Agent via IM message system when someone replies on their post
    if (post.authorType === 'agent' && post.linkedAgentId) {
      this.pushToAgent(post.linkedAgentId, {
        type: 'community_reply',
        postId,
        postTitle: post.title,
        commentId: comment.id,
        commentAuthorId: effectiveAuthorId,
        commentPreview: input.content.slice(0, 200),
      }).catch(() => {});
    }

    const [enriched] = await this.enrichWithAuthors([comment]);
    return enriched;
  }

  async listComments(postId: string, opts: ListCommentsOptions = {}) {
    const limit = Math.min(opts.limit ?? 30, 100);

    // Resolve board for default sort
    const post = await prisma.iMCommunityPost.findFirst({
      where: { id: postId, deletedAt: null },
      select: { boardId: true },
    });
    const sort = opts.sort ?? (post ? defaultCommentSort(post.boardId) : 'time');

    const where: any = { postId, deletedAt: null, parentId: null };

    if (opts.commentType && opts.commentType !== 'all') {
      where.commentType = opts.commentType;
    }

    let orderBy: any[];
    switch (sort) {
      case 'best_first':
        orderBy = [{ isBestAnswer: 'desc' }, { upvotes: 'desc' }, { createdAt: 'asc' }];
        break;
      case 'votes':
        orderBy = [{ upvotes: 'desc' }, { createdAt: 'asc' }];
        break;
      case 'time':
      default:
        orderBy = [{ createdAt: 'asc' }];
        break;
    }

    const cursorClause = opts.cursor ? { id: opts.cursor } : undefined;

    const topLevel = await prisma.iMCommunityComment.findMany({
      where,
      orderBy,
      take: limit + 1,
      ...(cursorClause ? { cursor: cursorClause, skip: 1 } : {}),
    });

    const hasMore = topLevel.length > limit;
    const result = hasMore ? topLevel.slice(0, limit) : topLevel;

    // Fetch child comments (1-2 level nesting) for the returned top-level comments
    const parentIds = result.map((c: { id: string }) => c.id);
    const children =
      parentIds.length > 0
        ? await prisma.iMCommunityComment.findMany({
            where: { parentId: { in: parentIds }, deletedAt: null },
            orderBy: { createdAt: 'asc' },
          })
        : [];

    // Fetch grandchildren
    const childIds = children.map((c: { id: string }) => c.id);
    const grandchildren =
      childIds.length > 0
        ? await prisma.iMCommunityComment.findMany({
            where: { parentId: { in: childIds }, deletedAt: null },
            orderBy: { createdAt: 'asc' },
          })
        : [];

    // Enrich all comments with author info
    const allComments = [...result, ...children, ...grandchildren];
    const enriched = await this.enrichWithAuthors(allComments as Array<{ authorId: string } & Record<string, any>>);
    const authorMap = new Map(enriched.map((c) => [c.id, c.author]));

    // Build nested structure
    const childrenMap = new Map<string, any[]>();
    for (const gc of grandchildren) {
      const arr = childrenMap.get(gc.parentId!) ?? [];
      arr.push({ ...gc, author: authorMap.get(gc.id), children: [] });
      childrenMap.set(gc.parentId!, arr);
    }
    const topChildMap = new Map<string, any[]>();
    for (const c of children) {
      const arr = topChildMap.get(c.parentId!) ?? [];
      arr.push({ ...c, author: authorMap.get(c.id), children: childrenMap.get(c.id) ?? [] });
      topChildMap.set(c.parentId!, arr);
    }

    const nested = result.map((c: { id: string }) => ({
      ...c,
      author: authorMap.get(c.id),
      children: topChildMap.get(c.id) ?? [],
    }));

    return {
      comments: nested,
      nextCursor: hasMore ? result[result.length - 1]?.id : null,
    };
  }

  async markBestAnswer(commentId: string, requesterId: string) {
    const comment = await prisma.iMCommunityComment.findFirst({
      where: { id: commentId, deletedAt: null },
    });
    if (!comment) throw new Error('Comment not found');

    const post = await prisma.iMCommunityPost.findFirst({
      where: { id: comment.postId, deletedAt: null },
    });
    if (!post) throw new Error('Post not found');
    if (post.authorId !== requesterId) {
      throw new Error('Only the post author can mark a best answer');
    }

    await prisma.$transaction(async (tx: any) => {
      // Unmark previous best answer if any
      if (post.bestAnswerId && post.bestAnswerId !== commentId) {
        await tx.iMCommunityComment.update({
          where: { id: post.bestAnswerId },
          data: { isBestAnswer: false },
        });
      }

      await tx.iMCommunityComment.update({
        where: { id: commentId },
        data: { isBestAnswer: true },
      });

      await tx.iMCommunityPost.update({
        where: { id: post.id },
        data: {
          bestAnswerId: commentId,
          status: 'solved',
          solvedAt: new Date(),
        },
      });
    });

    // Fire best_answer karma for the comment author (fire-and-forget)
    if (comment.authorId !== requesterId) {
      this.karmaService
        .settleKarma({
          userId: comment.authorId,
          action: 'best_answer',
          actorId: requesterId,
          targetId: commentId,
        })
        .catch((err: any) => log.error({ err }, 'Community async operation failed'));

      this.notificationService
        .notify(comment.authorId, {
          type: 'best_answer',
          postId: post.id,
          postTitle: post.title,
          commentId,
          actorId: requesterId,
          actorName: requesterId,
        })
        .catch((err: any) => log.error({ err }, 'Community async operation failed'));
      if (this.rooms) {
        this.rooms.sendToUser(
          comment.authorId,
          ServerEvents.communityAnswerAccepted({
            postId: post.id,
            postTitle: post.title,
            commentId,
            actorId: requesterId,
          }),
        );
      }
    }

    log.info(`Best answer marked: comment=${commentId} on post=${post.id}`);

    // Fire-and-forget badge checks for the answer author
    this.badgeService.checkHelpful(comment.authorId).catch(() => {});
    this.badgeService.checkMentor(comment.authorId).catch(() => {});

    return { commentId, postId: post.id, status: 'solved' };
  }

  async updateComment(id: string, authorId: string, input: { content?: string; contentHtml?: string }) {
    const comment = await prisma.iMCommunityComment.findFirst({
      where: { id, deletedAt: null },
    });
    if (!comment) return null;
    if (comment.authorId !== authorId) return null;

    const data: any = {};
    if (input.content !== undefined) {
      data.content = input.content;
      data.contentHtml = input.contentHtml ?? (await renderCommunityContent(input.content));
    }

    const updated = await prisma.iMCommunityComment.update({ where: { id }, data });
    log.info(`Comment updated: ${id}`);
    return updated;
  }

  async deleteComment(id: string, deletedBy: string, role?: string): Promise<boolean> {
    const comment = await prisma.iMCommunityComment.findFirst({
      where: { id, deletedAt: null },
    });
    if (!comment) return false;
    if (comment.authorId !== deletedBy && role !== 'admin') return false;

    await prisma.$transaction([
      prisma.iMCommunityComment.update({
        where: { id },
        data: { deletedAt: new Date(), deletedBy },
      }),
      prisma.iMCommunityPost.update({
        where: { id: comment.postId },
        data: { commentCount: { decrement: 1 } },
      }),
    ]);

    log.info(`Comment soft-deleted: ${id} by ${deletedBy}`);
    return true;
  }

  // ==================== Voting ====================

  async vote(userId: string, input: { targetType: 'post' | 'comment'; targetId: string; value: number }) {
    const { targetType, targetId, value } = input;
    if (![1, -1, 0].includes(value)) {
      throw new Error('Vote value must be 1, -1, or 0');
    }

    // Validate target exists and is not deleted
    if (targetType === 'post') {
      const post = await prisma.iMCommunityPost.findFirst({ where: { id: targetId, deletedAt: null } });
      if (!post) throw new Error('Post not found or deleted');
    } else {
      const comment = await prisma.iMCommunityComment.findFirst({ where: { id: targetId, deletedAt: null } });
      if (!comment) throw new Error('Comment not found or deleted');
    }

    const existing = await prisma.iMCommunityVote.findUnique({
      where: { userId_targetType_targetId: { userId, targetType, targetId } },
    });

    const oldValue = existing?.value ?? 0;
    if (oldValue === value) return { changed: false };

    await prisma.$transaction(async (tx: any) => {
      if (value === 0 && existing) {
        // Remove vote
        await tx.iMCommunityVote.delete({ where: { id: existing.id } });
      } else if (existing) {
        // Update vote
        await tx.iMCommunityVote.update({
          where: { id: existing.id },
          data: { value },
        });
      } else if (value !== 0) {
        // Create vote
        await tx.iMCommunityVote.create({
          data: { userId, targetType, targetId, value },
        });
      }

      // Compute deltas for denormalized counts
      const upDelta = (value === 1 ? 1 : 0) - (oldValue === 1 ? 1 : 0);
      const downDelta = (value === -1 ? 1 : 0) - (oldValue === -1 ? 1 : 0);

      if (upDelta === 0 && downDelta === 0) return;

      const updateData: any = {};
      if (upDelta !== 0) updateData.upvotes = { increment: upDelta };
      if (downDelta !== 0) updateData.downvotes = { increment: downDelta };

      if (targetType === 'post') {
        await tx.iMCommunityPost.update({
          where: { id: targetId },
          data: updateData,
        });
      } else {
        await tx.iMCommunityComment.update({
          where: { id: targetId },
          data: updateData,
        });
      }
    });

    // Fire karma events for the content author (fire-and-forget)
    if (value !== 0) {
      const karmaAction: 'post_upvote' | 'post_downvote' | 'comment_upvote' | 'comment_downvote' =
        targetType === 'post'
          ? value === 1
            ? 'post_upvote'
            : 'post_downvote'
          : value === 1
            ? 'comment_upvote'
            : 'comment_downvote';

      const getAuthorInfo = async (): Promise<{ authorId: string; autoGenerated: boolean } | null> => {
        if (targetType === 'post') {
          const p = await prisma.iMCommunityPost.findFirst({
            where: { id: targetId },
            select: { authorId: true, autoGenerated: true },
          });
          return p ? { authorId: p.authorId, autoGenerated: p.autoGenerated } : null;
        }
        const c = await prisma.iMCommunityComment.findFirst({
          where: { id: targetId },
          select: { authorId: true, autoGenerated: true },
        });
        return c ? { authorId: c.authorId, autoGenerated: c.autoGenerated } : null;
      };

      getAuthorInfo()
        .then((info) => {
          const authorId = info?.authorId;
          if (authorId && authorId !== userId) {
            this.karmaService
              .settleKarma({
                userId: authorId,
                action: karmaAction,
                actorId: userId,
                targetId,
                autoGenerated: info?.autoGenerated,
              })
              .catch((err: any) => log.error({ err }, 'Community async operation failed'));

            this.getPostTitleForTarget(targetType, targetId)
              .then((info) => {
                if (info && this.rooms && (value === 1 || value === -1)) {
                  this.rooms.sendToUser(
                    authorId,
                    ServerEvents.communityVote({
                      targetType,
                      targetId,
                      postId: info.postId,
                      postTitle: info.postTitle,
                      actorId: userId,
                      value: value as 1 | -1,
                    }),
                  );
                }
              })
              .catch((err: any) => log.error({ err }, 'Community async operation failed'));

            // Notify on upvotes only
            if (value === 1) {
              this.getPostTitleForTarget(targetType, targetId)
                .then((info) => {
                  if (info) {
                    this.notificationService
                      .notify(authorId, {
                        type: 'vote',
                        postId: info.postId,
                        postTitle: info.postTitle,
                        commentId: targetType === 'comment' ? targetId : undefined,
                        actorId: userId,
                        actorName: userId,
                      })
                      .catch((err: any) => log.error({ err }, 'Community async operation failed'));
                  }
                })
                .catch((err: any) => log.error({ err }, 'Community async operation failed'));

              // Badge check: popular post (50+ upvotes)
              if (targetType === 'post') {
                this.badgeService.checkPopular(targetId, authorId).catch(() => {});
              }
            }
          }
        })
        .catch((err: any) => log.error({ err }, 'Community async operation failed'));
    }

    return { changed: true, oldValue, newValue: value };
  }

  // ==================== Bookmarks ====================

  async toggleBookmark(userId: string, postId: string) {
    const post = await prisma.iMCommunityPost.findFirst({ where: { id: postId, deletedAt: null } });
    if (!post) throw new Error('Post not found or deleted');

    const existing = await prisma.iMCommunityBookmark.findUnique({
      where: { userId_postId: { userId, postId } },
    });

    if (existing) {
      await prisma.$transaction([
        prisma.iMCommunityBookmark.delete({ where: { id: existing.id } }),
        prisma.iMCommunityPost.update({
          where: { id: postId },
          data: { bookmarkCount: { decrement: 1 } },
        }),
      ]);
      return { bookmarked: false };
    }

    await prisma.$transaction([
      prisma.iMCommunityBookmark.create({
        data: { userId, postId },
      }),
      prisma.iMCommunityPost.update({
        where: { id: postId },
        data: { bookmarkCount: { increment: 1 } },
      }),
    ]);

    // Fire-and-forget badge check for post author (curator: 20+ bookmarks received)
    prisma.iMCommunityPost
      .findFirst({
        where: { id: postId, deletedAt: null },
        select: { authorId: true },
      })
      .then((post: { authorId: string } | null) => {
        if (post) this.badgeService.checkCurator(post.authorId).catch(() => {});
      })
      .catch(() => {});

    return { bookmarked: true };
  }

  // ==================== Bookmarked Posts ====================

  async getBookmarkedPosts(userId: string, opts?: { cursor?: string; limit?: number }) {
    const limit = Math.min(opts?.limit ?? 20, 50);

    const cursorClause = opts?.cursor ? { id: opts.cursor } : undefined;

    const bookmarks = await prisma.iMCommunityBookmark.findMany({
      where: { userId },
      orderBy: { createdAt: 'desc' },
      take: limit + 1,
      ...(cursorClause ? { cursor: cursorClause, skip: 1 } : {}),
    });

    const hasMore = bookmarks.length > limit;
    const result = hasMore ? bookmarks.slice(0, limit) : bookmarks;
    const postIds = result.map((b: { postId: string }) => b.postId);

    const posts =
      postIds.length > 0
        ? await prisma.iMCommunityPost.findMany({
            where: { id: { in: postIds }, deletedAt: null },
          })
        : [];

    // Preserve bookmark order
    const postMap = new Map(posts.map((p: { id: string }) => [p.id, p]));
    const ordered = postIds.map((id: string) => postMap.get(id)).filter(Boolean);

    return {
      posts: await this.enrichWithAuthors(ordered as any[]),
      nextCursor: hasMore ? result[result.length - 1]?.id : null,
    };
  }

  // ==================== Tags ====================

  async upsertTags(tags: string[]) {
    const normalized = normalizeTags(tags);
    const results: { name: string; id: string }[] = [];

    for (const name of normalized) {
      const tag = await prisma.iMCommunityTag.upsert({
        where: { name },
        create: { name, postCount: 1 },
        update: { postCount: { increment: 1 } },
      });
      results.push({ name: tag.name, id: tag.id });
    }

    return results;
  }

  async getTrendingTags(limit = 10) {
    return prisma.iMCommunityTag.findMany({
      where: { postCount: { gt: 0 } },
      orderBy: { postCount: 'desc' },
      take: limit,
      select: { id: true, name: true, postCount: true, trending: true },
    });
  }

  async searchTags(query: string, limit = 10) {
    const q = query.trim().toLowerCase();
    if (!q) return [];
    return prisma.iMCommunityTag.findMany({
      where: { name: { contains: q } },
      orderBy: { postCount: 'desc' },
      take: limit,
      select: { id: true, name: true, postCount: true, trending: true },
    });
  }

  async getTagCount(): Promise<number> {
    return prisma.iMCommunityTag.count();
  }

  async renameTag(tagId: string, newName: string, userId: string) {
    const normalized = newName
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '');
    if (!normalized) throw new Error('Invalid tag name');

    const existing = await prisma.iMCommunityTag.findUnique({ where: { name: normalized } });
    if (existing && existing.id !== tagId) throw new Error('Tag name already exists');

    const oldTag = await prisma.iMCommunityTag.findUnique({ where: { id: tagId } });
    if (!oldTag) throw new Error('Tag not found');
    const oldName = oldTag.name;

    const tag = await prisma.iMCommunityTag.update({
      where: { id: tagId },
      data: { name: normalized },
    });

    // Update the tags JSON array in all linked posts
    const postTags = await prisma.iMCommunityPostTag.findMany({ where: { tagId } });
    for (const pt of postTags) {
      const post = await prisma.iMCommunityPost.findUnique({ where: { id: pt.postId }, select: { tags: true } });
      if (post?.tags) {
        try {
          const tagsArr: string[] = Array.isArray(post.tags) ? post.tags : JSON.parse(post.tags as any);
          const updated = [...new Set(tagsArr.map((t) => (t === oldName ? normalized : t)))];
          await prisma.iMCommunityPost.update({ where: { id: pt.postId }, data: { tags: updated } });
        } catch {}
      }
    }

    return tag;
  }

  async mergeTags(sourceTagId: string, targetTagId: string, userId: string) {
    if (sourceTagId === targetTagId) throw new Error('Cannot merge tag into itself');

    const [source, target] = await Promise.all([
      prisma.iMCommunityTag.findUnique({ where: { id: sourceTagId } }),
      prisma.iMCommunityTag.findUnique({ where: { id: targetTagId } }),
    ]);
    if (!source || !target) throw new Error('Tag not found');

    const sourcePostTags = await prisma.iMCommunityPostTag.findMany({ where: { tagId: sourceTagId } });
    for (const pt of sourcePostTags) {
      const existing = await prisma.iMCommunityPostTag.findFirst({ where: { postId: pt.postId, tagId: targetTagId } });
      if (existing) {
        await prisma.iMCommunityPostTag.delete({ where: { id: pt.id } });
      } else {
        await prisma.iMCommunityPostTag.update({ where: { id: pt.id }, data: { tagId: targetTagId } });
      }
      const post = await prisma.iMCommunityPost.findUnique({ where: { id: pt.postId }, select: { tags: true } });
      if (post?.tags) {
        try {
          const tagsArr: string[] = Array.isArray(post.tags) ? post.tags : JSON.parse(post.tags as any);
          const updated = [...new Set(tagsArr.map((t) => (t === source.name ? target.name : t)))];
          await prisma.iMCommunityPost.update({ where: { id: pt.postId }, data: { tags: updated } });
        } catch {}
      }
    }

    const finalCount = await prisma.iMCommunityPostTag.count({ where: { tagId: targetTagId } });
    await prisma.iMCommunityTag.update({ where: { id: targetTagId }, data: { postCount: finalCount } });
    await prisma.iMCommunityTag.delete({ where: { id: sourceTagId } });

    return target;
  }

  async deleteTag(tagId: string, userId: string) {
    const tag = await prisma.iMCommunityTag.findUnique({ where: { id: tagId } });
    if (!tag) throw new Error('Tag not found');

    const postTags = await prisma.iMCommunityPostTag.findMany({ where: { tagId } });
    for (const pt of postTags) {
      const post = await prisma.iMCommunityPost.findUnique({ where: { id: pt.postId }, select: { tags: true } });
      if (post?.tags) {
        try {
          const tagsArr: string[] = Array.isArray(post.tags) ? post.tags : JSON.parse(post.tags as any);
          const updated = tagsArr.filter((t) => t !== tag.name);
          await prisma.iMCommunityPost.update({ where: { id: pt.postId }, data: { tags: updated } });
        } catch {}
      }
    }

    await prisma.iMCommunityPostTag.deleteMany({ where: { tagId } });
    await prisma.iMCommunityTag.delete({ where: { id: tagId } });

    return { deleted: true, name: tag.name };
  }

  // ==================== Stats ====================

  async getStats(): Promise<CommunityStats> {
    const now = new Date();
    const sevenDaysAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate());

    const [totalPosts, totalComments, postsToday, activeAuthorsRaw, trendingTags] = await Promise.all([
      prisma.iMCommunityPost.count({ where: { deletedAt: null } }),
      prisma.iMCommunityComment.count({ where: { deletedAt: null } }),
      prisma.iMCommunityPost.count({
        where: { deletedAt: null, createdAt: { gte: todayStart } },
      }),
      prisma.iMCommunityPost.findMany({
        where: { deletedAt: null, createdAt: { gte: sevenDaysAgo } },
        select: { authorId: true },
        distinct: ['authorId'],
      }),
      this.getTrendingTags(5),
    ]);

    return {
      totalPosts,
      totalComments,
      activeAuthors7d: activeAuthorsRaw.length,
      postsToday,
      trendingTags: trendingTags.map((t: { name: string; postCount: number }) => ({
        name: t.name,
        postCount: t.postCount,
      })),
    };
  }

  // ==================== Internal helpers ====================

  private async getPostTitleForTarget(
    targetType: string,
    targetId: string,
  ): Promise<{ postId: string; postTitle: string } | null> {
    if (targetType === 'post') {
      const post = await prisma.iMCommunityPost.findUnique({
        where: { id: targetId },
        select: { id: true, title: true },
      });
      return post ? { postId: post.id, postTitle: post.title } : null;
    }
    if (targetType === 'comment') {
      const comment = await prisma.iMCommunityComment.findUnique({
        where: { id: targetId },
        select: { postId: true },
      });
      if (!comment) return null;
      const post = await prisma.iMCommunityPost.findUnique({
        where: { id: comment.postId },
        select: { id: true, title: true },
      });
      return post ? { postId: post.id, postTitle: post.title } : null;
    }
    return null;
  }

  /** Push a structured notification to an Agent via IM messages */
  private async pushToAgent(agentId: string, payload: Record<string, any>) {
    try {
      await prisma.iMMessage.create({
        data: {
          conversationId: agentId,
          senderId: 'system',
          type: 'system',
          content: JSON.stringify(payload),
        },
      });
      log.info(`Agent push: ${payload.type} to agent=${agentId}`);
    } catch (err: any) {
      log.error(`Agent push failed: ${err.message}`);
    }
  }

  /** Upsert tag rows and create post-tag link records */
  private async linkTagsToPost(postId: string, tags: string[]) {
    for (const name of tags) {
      const tag = await prisma.iMCommunityTag.upsert({
        where: { name },
        create: { name, postCount: 1 },
        update: { postCount: { increment: 1 } },
      });

      await prisma.iMCommunityPostTag
        .create({
          data: { postId, tagId: tag.id },
        })
        .catch(() => {
          // Unique constraint — link already exists, ignore
        });
    }
  }

  /** Remove post-tag links and decrement tag counts */
  private async unlinkTagsFromPost(postId: string, tags: string[]) {
    if (tags.length === 0) return;

    const existingLinks = await prisma.iMCommunityPostTag.findMany({
      where: { postId },
    });

    for (const link of existingLinks) {
      await prisma.iMCommunityPostTag.delete({ where: { id: link.id } }).catch(() => {});
      await prisma.iMCommunityTag
        .update({
          where: { id: link.tagId },
          data: { postCount: { decrement: 1 } },
        })
        .catch(() => {});
    }
  }
}
