"""Hermes memory plugin shim — install/uninstall helpers.

Renders a thin ``__init__.py`` into ``$HERMES_HOME/plugins/<name>/`` so
Hermes' memory plugin discovery (see hermes-agent/plugins/memory/__init__.py
``_is_memory_provider_dir`` and ``_load_provider_from_dir``) picks up
``PrismerDaemonMemoryProvider`` from the installed ``prismer`` PyPI
package.

Discovery contract notes:

  - Cheap text scan looks for the substring ``register_memory_provider``
    OR ``MemoryProvider`` in the plugin's ``__init__.py``. The template
    contains both, so the scan accepts the directory.
  - Hermes then calls ``register(ctx)`` if present and falls back to
    instantiating any ``MemoryProvider`` subclass it finds at module
    scope. The shim exports ``register`` (the canonical pattern, matching
    bundled providers like Honcho) and re-exports the provider class as
    ``MemoryProvider`` so the fallback path also works. We additionally
    expose ``register_memory_provider()`` as a free function so any
    third-party loader scanning for that exact symbol succeeds without
    needing the Hermes ``register(ctx)`` plugin context.
  - The plugin directory name == the value of ``memory.provider`` in
    Hermes' config (see ``find_provider_dir(name)``). We use
    ``prismer-daemon`` to match ``PrismerDaemonMemoryProvider.name``.

The shim does NOT vendor ``hermes_memory_provider.py`` — it imports
from the installed ``prismer`` package, so updating ``pip install -U
prismer`` automatically updates the provider. Re-running the installer
is only needed if the shim shape itself changes (rare).
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Tuple


# Plugin directory name. Matches PrismerDaemonMemoryProvider.name so
# Hermes' find_provider_dir(name) lookup resolves to this directory when
# memory.provider is set in config.yaml.
PLUGIN_NAME = "prismer-daemon"


# The shim source. Kept verbatim — re-running the installer overwrites.
#
# Both ``register_memory_provider`` (free function, free-form discovery)
# and ``MemoryProvider`` (class re-export, ABC-subclass discovery) are
# present so Hermes' two-path scan in ``_is_memory_provider_dir`` and
# ``_load_provider_from_dir`` accepts the directory under either path.
PLUGIN_TEMPLATE = '''\
"""Auto-generated Hermes memory plugin shim for Prismer.

Generated by ``prismer hermes install-memory-provider``. Do not edit;
re-run the installer to update.

This file bridges Hermes' MemoryProvider plugin discovery to the
``PrismerDaemonMemoryProvider`` class shipped in the ``prismer`` PyPI
package. The actual implementation lives there — this shim is only
the registration surface Hermes scans for.

To enable: set ``memory.provider: prismer-daemon`` in
``$HERMES_HOME/config.yaml``.
"""

from prismer.hermes_memory_provider import (
    MEMORY_LOAD_SCHEMA,
    MEMORY_SEARCH_SCHEMA,
    PrismerDaemonMemoryProvider,
)


def register(ctx) -> None:
    """Hermes plugin entry point (matches bundled provider pattern).

    Hermes' ``_load_provider_from_dir`` calls ``register(ctx)`` and
    captures the provider via ``ctx.register_memory_provider(provider)``.
    """
    ctx.register_memory_provider(PrismerDaemonMemoryProvider())


def register_memory_provider():
    """Free-function variant of the discovery hook.

    Returns a fresh ``PrismerDaemonMemoryProvider`` instance, mirroring
    the ``register(ctx)`` pattern (which calls
    ``ctx.register_memory_provider(PrismerDaemonMemoryProvider())``) and
    matching how bundled providers like Honcho's
    ``ctx.register_memory_provider(HonchoMemoryProvider())`` operate.
    Callers that look for the bare ``register_memory_provider`` symbol
    (instead of the ``register(ctx)`` Hermes plugin pattern) thus get a
    ready-to-use provider instance, not a class they still have to
    construct.
    """
    return PrismerDaemonMemoryProvider()


# Hermes also accepts module-level MemoryProvider subclass discovery as
# a fallback (see _load_provider_from_dir). Re-exporting the class under
# the ``MemoryProvider`` name lets that path succeed too.
MemoryProvider = PrismerDaemonMemoryProvider


__all__ = [
    "MEMORY_LOAD_SCHEMA",
    "MEMORY_SEARCH_SCHEMA",
    "MemoryProvider",
    "PrismerDaemonMemoryProvider",
    "register",
    "register_memory_provider",
]
'''


def resolve_hermes_home() -> Path:
    """Return ``$HERMES_HOME`` or the default ``~/.hermes``.

    Matches Hermes' own resolution order in ``hermes_constants.get_hermes_home``
    for the env-var path. We deliberately do NOT import that module — the
    Prismer SDK must not depend on hermes-agent being installed.
    """
    raw = os.environ.get("HERMES_HOME")
    if raw:
        return Path(raw).expanduser()
    return Path.home() / ".hermes"


def plugin_dir(hermes_home: Path) -> Path:
    """Return ``<hermes_home>/plugins/prismer-daemon/``."""
    return hermes_home / "plugins" / PLUGIN_NAME


def plugin_init_file(hermes_home: Path) -> Path:
    """Return the path to the plugin's ``__init__.py``."""
    return plugin_dir(hermes_home) / "__init__.py"


def render_template() -> str:
    """Return the shim source as a string. Pure — no I/O."""
    return PLUGIN_TEMPLATE


def install(hermes_home: Path) -> Tuple[Path, Path]:
    """Create the plugin directory and write the shim ``__init__.py``.

    Idempotent: re-running overwrites. Returns ``(plugin_dir, init_file)``.
    """
    pdir = plugin_dir(hermes_home)
    pdir.mkdir(parents=True, exist_ok=True)
    init_file = pdir / "__init__.py"
    init_file.write_text(render_template(), encoding="utf-8")
    return pdir, init_file


@dataclass
class UninstallResult:
    """Outcome of an ``uninstall(hermes_home)`` call.

    Attributes:
        existed: True if the plugin directory existed when uninstall ran.
            False means there was nothing to do (graceful no-op).
        init_removed: True if the installer-written ``__init__.py`` was
            removed (or was already absent). False is reserved for future
            failure cases; today we always succeed if ``existed`` is True.
        dir_removed: True if the now-empty plugin directory was also
            removed. False means the directory was kept because the user
            (or a third party) left other files inside.
        remaining_files: Names of files/dirs left behind in the plugin
            directory after removal. Empty when ``dir_removed`` is True.
    """

    existed: bool
    init_removed: bool = False
    dir_removed: bool = False
    remaining_files: List[str] = field(default_factory=list)

    @property
    def fully_removed(self) -> bool:
        """True iff the plugin directory is gone (init + dir both removed)."""
        return self.init_removed and self.dir_removed


def uninstall(hermes_home: Path) -> UninstallResult:
    """Remove the installer-written ``__init__.py`` from the plugin dir.

    This is intentionally NOT ``shutil.rmtree(plugin_dir)`` — that would
    blow away anything the user (or a third party) put in the directory,
    e.g. ``__init__.py.bak`` backups, custom notes, etc. Instead we:

      1. Remove only ``__init__.py`` (the file the installer wrote).
      2. If the plugin directory is now empty, remove the directory too
         (clean uninstall — what users expect in the common case).
      3. If other files remain, leave the directory in place and report
         them via ``remaining_files`` so the caller can warn the user.

    Graceful: returns an ``UninstallResult`` with ``existed=False`` if the
    plugin directory was never there. Never raises on missing paths.
    """
    pdir = plugin_dir(hermes_home)
    if not pdir.exists():
        return UninstallResult(existed=False)

    init_file = pdir / "__init__.py"
    init_removed = False
    if init_file.exists():
        init_file.unlink()
        init_removed = True
    else:
        # Directory exists but the installer file is already gone — treat
        # the file removal step as satisfied so we still attempt rmdir.
        init_removed = True

    remaining = sorted(p.name for p in pdir.iterdir())
    if not remaining:
        os.rmdir(pdir)
        return UninstallResult(
            existed=True,
            init_removed=init_removed,
            dir_removed=True,
            remaining_files=[],
        )

    return UninstallResult(
        existed=True,
        init_removed=init_removed,
        dir_removed=False,
        remaining_files=remaining,
    )
