"""Hermes memory provider backed by the Prismer daemon.

Bridges Hermes agent sessions to Prismer's daemon-side memory subsystem
(Line C). Implements the Hermes `MemoryProvider` ABC so an end user with
``memory.provider = prismer-daemon`` in their config gets:

  - ``INDEX.md`` injected into the system prompt at session start
    (via ``system_prompt_block()`` — preloaded once in ``initialize``)
  - **opt-in** workspace recall via ``prefetch(query)``. By default the
    provider treats this as a no-op (returns empty string) — agents call
    ``memory_search`` selectively when they actually need prior memory
    instead of paying the auto-injection tax on every turn. Set
    ``PRISMER_MEMORY_AUTO_PREFETCH=1`` to restore the legacy behavior
    (hybrid search + ``<memory-context>`` fence + ``recall_inject`` events).
    See doc 25 §3 支柱 1 (M-A) for the rationale.
  - ``memory_search`` + ``memory_load`` tools exposed to the model
    (``get_tool_schemas()``), backed by daemon RPC and emitting
    ``recall_pull`` events on each call
  - graceful no-op fallbacks when the daemon is offline (no exception
    bubbles into Hermes' main loop — that would kill the agent)

What this provider does NOT do (v0 scope):
  - ``queue_prefetch``: no background prefetch optimization yet
  - ``sync_turn``: no per-turn writes (aggressive; doc 19 I6 owns
    consolidation via the 4-stage subagent flow)
  - ``on_session_end``: no end-of-session reflection write
  - any cloud-side calls — the provider only talks to ``127.0.0.1:3210``;
    the daemon's outbox worker is responsible for cloud upload (C2)

Configuration (env-based, matches Prismer SDK pattern):

  PRISMER_DAEMON_URL    default ``http://127.0.0.1:3210``
  PRISMER_WORKSPACE_ID  required for the provider to be ``available``
  PRISMER_AGENT_IM_USER_ID  optional; used as ``actorImUserId`` on
                             observability events. Falls back to
                             ``"hermes-agent"``.
  PRISMER_MEMORY_AUTO_PREFETCH  optional; ``1``/``true`` re-enables the
                             pre-M-A auto-injection behavior in
                             ``prefetch()``. Default off — agents are
                             expected to call ``memory_search`` only
                             when prior memory genuinely helps.

Wire format: see ``daemon/memory/envelope.ts`` for the locked
``MemoryOutboxEnvelope`` zod union. Observability events POST to
``/local/memory/observability/emit``; the daemon validates the envelope
on the way in and dead-letters bad payloads on its side, so the provider
can fire-and-forget.
"""

from __future__ import annotations

import json
import logging
import os
import threading
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

# Memory-curation skill (doc 27 §3) — embedded text injected into the
# system_prompt_block so every Hermes session sees the asset-driven
# memory page guidance. Source: sdk/prismer-cloud/skill/memory-curation.md
# Drift detection lives on the TS side
# (runtime/test/skill-memory-curation-sync.test.ts); the Python copy is
# regenerated by scripts/regenerate-memory-curation-skill.cjs at the same
# time as the TS copies, so all three stay in lockstep.
from ._memory_curation_skill import (  # noqa: F401  (re-exported for downstream)
    MEMORY_CURATION_SKILL_NAME,
    MEMORY_CURATION_SKILL_TEXT,
)

try:
    import httpx
    _HTTPX_AVAILABLE = True
except ImportError:  # pragma: no cover — httpx is a top-level prismer dep
    _HTTPX_AVAILABLE = False

# Hermes ABC import — the provider only runs inside a Hermes process where
# this package is on the import path. When the prismer SDK is installed
# standalone (e.g. for unit testing this file in isolation), we fall back
# to an in-module stub that mirrors the abstract surface we override. The
# stub is byte-for-byte compatible with Hermes' real ABC for the methods
# we touch — see /Users/prismer/workspace/hermes-agent/agent/memory_provider.py
# (lines 42-280) for the source of truth.
try:
    from agent.memory_provider import MemoryProvider  # type: ignore[import-not-found]
    _HERMES_ABC_AVAILABLE = True
except ImportError:
    _HERMES_ABC_AVAILABLE = False

    class MemoryProvider:  # type: ignore[no-redef]
        """Stub ABC used only when the Hermes package isn't importable.

        Field-for-field equivalent of agent.memory_provider.MemoryProvider
        for the methods this provider overrides. Hermes' real ABC has more
        optional hooks (on_session_switch, on_pre_compress, on_delegation,
        on_memory_write, get_config_schema, save_config) — we don't override
        them, so the no-op defaults from the real ABC apply at runtime.
        """

        @property
        def name(self) -> str:  # noqa: D401
            raise NotImplementedError

        def is_available(self) -> bool:
            raise NotImplementedError

        def initialize(self, session_id: str, **kwargs: Any) -> None:
            raise NotImplementedError

        def system_prompt_block(self) -> str:
            return ""

        def prefetch(self, query: str, *, session_id: str = "") -> str:
            return ""

        def queue_prefetch(self, query: str, *, session_id: str = "") -> None:
            pass

        def sync_turn(
            self, user_content: str, assistant_content: str, *, session_id: str = "",
        ) -> None:
            pass

        def get_tool_schemas(self) -> List[Dict[str, Any]]:
            raise NotImplementedError

        def handle_tool_call(self, tool_name: str, args: Dict[str, Any], **kwargs: Any) -> str:
            raise NotImplementedError(
                f"Provider does not handle tool {tool_name}",
            )

        def shutdown(self) -> None:
            pass

        def on_session_end(self, messages: List[Dict[str, Any]]) -> None:
            pass

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_DAEMON_URL = "http://127.0.0.1:3210"

# doc 18 §C3 caps: 200 lines / 25 KB for INDEX.md preload.
_INDEX_MAX_LINES = 200
_INDEX_MAX_BYTES = 25 * 1024

# Default search budgets.
#
# Two distinct defaults — keep them apart, the call sites have different
# contracts:
#
#   _AUTO_INJECT_TOP_K  — used by ``prefetch()`` only when the legacy
#                         opt-in env (``PRISMER_MEMORY_AUTO_PREFETCH``)
#                         is set. Kept tight (3) because the legacy path
#                         pays this cost on every turn. Default behavior
#                         is no-op — see doc 25 §3 支柱 1.
#
#   _TOOL_DEFAULT_TOP_K — used by ``_tool_memory_search()`` when the LLM
#                         omits ``limit``. MUST match
#                         ``MEMORY_SEARCH_SCHEMA["parameters"]["properties"]["limit"]["default"]``
#                         (5). The schema is the model-facing contract; if
#                         the LLM plans for "default 5" but we silently
#                         return 3, recall is under-provisioned vs intent.
_AUTO_INJECT_TOP_K = 3
_TOOL_DEFAULT_TOP_K = 5
_DEFAULT_MAX_BYTES = 2 * 1024

# Env var that re-enables the legacy auto-injection behavior of ``prefetch()``.
# Default off (M-A): ``prefetch()`` returns "" without doing any work, and
# the agent is expected to call ``memory_search`` selectively. Truthy values
# accepted: "1", "true", "yes" (case-insensitive).
_AUTO_PREFETCH_ENV = "PRISMER_MEMORY_AUTO_PREFETCH"
_AUTO_PREFETCH_TRUTHY = {"1", "true", "yes"}


def _auto_prefetch_enabled() -> bool:
    """Return True if the legacy auto-injection prefetch is opted in via env."""
    return os.environ.get(_AUTO_PREFETCH_ENV, "").strip().lower() in _AUTO_PREFETCH_TRUTHY


# ---------------------------------------------------------------------------
# M-B fork SPI (doc 25 §3 支柱 2)
# ---------------------------------------------------------------------------

# Selector system prompt — kept BYTE-IDENTICAL to the daemon-side TS
# constant in
# `sdk/prismer-cloud/runtime/src/daemon/memory/fork/select-memories.ts`.
# Both files must be updated together; the selector's "be selective"
# framing is the load-bearing line and small-model behavior shifts when
# either copy drifts.
SELECT_MEMORIES_SYSTEM_PROMPT = "\n".join(
    [
        "You are selecting memories that will be useful to an AI agent as it processes a user query.",
        "You will be given the user's query and a list of available memory files with their filenames and descriptions.",
        "",
        "Return a list of filenames for the memories that will clearly be useful (up to 5).",
        "Only include memories that you are CERTAIN will be helpful based on their name and description.",
        "- If you are unsure if a memory will be useful, do NOT include it. Be selective and discerning.",
        "- If no memories in the list would clearly be useful, return an empty list.",
        "- If a list of recently-used tools is provided, do NOT select usage reference or API documentation",
        "  for those tools (the agent is already exercising them). DO still select memories containing",
        "  warnings, gotchas, or known issues — active use is exactly when those matter.",
        "",
        'Respond with a single JSON object: { "selected_memories": ["path1", "path2", ...] }',
        "Do NOT wrap the JSON in code fences. Do NOT include any commentary.",
    ]
)

# Cap on selector input — keeps a multi-thousand-page workspace tractable.
# Mirrors `MAX_MANIFEST_ENTRIES` in the TS select-memories module.
MAX_MANIFEST_ENTRIES = 200
MAX_SELECTED = 5

# Anthropic API target for the host-side LLM call. Hermes runs in a separate
# process from the daemon, so the daemon never holds the API key (option A
# from doc 25 §7 judgment 4).
_EXTRACT_SYSTEM_PROMPT = "\n".join(
    [
        # Mirrors EXTRACT_SYSTEM_PROMPT in
        # sdk/prismer-cloud/runtime/src/daemon/memory/dream/extract-runner.ts.
        # Keep both copies in lockstep — the conservative tone is load-bearing.
        "You are reviewing a finished agent session and proposing 0–3 short memory entries that would be useful to surface in future sessions.",
        "",
        "Be conservative. Most sessions do NOT warrant a memory write — only propose memories when:",
        "  - the user expressed a clear preference (style, tooling, naming convention)",
        "  - the user shared a project-level fact that future sessions will keep needing (deadlines, ownership, tracker references)",
        "  - the agent encountered a workaround or gotcha that would save time next time",
        "",
        "For each memory you propose, return a JSON object with:",
        '  - path: workspace-relative path under "memory/" (e.g. "memory/feedback/sdk-naming.md")',
        "  - title: short imperative title (≤80 chars)",
        "  - summary: 1–3 sentence body in markdown",
        "  - rationale: why future sessions benefit (1 sentence)",
        "  - confidence: float in [0,1] — your subjective certainty this is worth keeping",
        "",
        'Respond with a single JSON object: { "proposals": [...] }. Empty proposals[] is fine and preferred when nothing strong stands out. Do NOT wrap the JSON in code fences.',
    ]
)


def _parse_extract_output(raw_text: str) -> List[Dict[str, Any]]:
    """Mirror of TS-side parseExtractOutput. Returns 0..3 valid proposals."""
    text = raw_text.strip()
    if not text:
        return []
    if text.startswith("```"):
        text = text.lstrip("`")
        if text.lower().startswith("json"):
            text = text[4:]
        text = text.strip()
        if text.endswith("```"):
            text = text[:-3].strip()
    try:
        parsed = json.loads(text)
    except Exception:
        return []
    if not isinstance(parsed, dict):
        return []
    arr = parsed.get("proposals")
    if not isinstance(arr, list):
        return []
    out: List[Dict[str, Any]] = []
    for entry in arr:
        if not isinstance(entry, dict):
            continue
        path = entry.get("path")
        title = entry.get("title")
        summary = entry.get("summary")
        rationale = entry.get("rationale", "")
        confidence = entry.get("confidence", 0.5)
        if not isinstance(path, str) or not path.startswith("memory/"):
            continue
        if not isinstance(title, str) or not title.strip():
            continue
        if not isinstance(summary, str) or not summary.strip():
            continue
        if not isinstance(rationale, str):
            rationale = ""
        if not isinstance(confidence, (int, float)):
            confidence = 0.5
        confidence = max(0.0, min(1.0, float(confidence)))
        out.append(
            {
                "path": path,
                "title": title[:80],
                "summary": summary[:4000],
                "rationale": rationale[:500],
                "confidence": confidence,
            }
        )
        if len(out) >= 3:
            break
    return out


_ANTHROPIC_API_BASE = "https://api.anthropic.com"
_ANTHROPIC_API_VERSION = "2023-06-01"

# Env vars controlling fork_query.
_FORK_API_KEY_ENV = "PRISMER_MEMORY_FORK_API_KEY"  # falls back to ANTHROPIC_API_KEY
_FORK_MODEL_ENV = "PRISMER_MEMORY_FORK_MODEL"
_FORK_MODEL_DEFAULT = "claude-haiku-4-5-20251001"
# Per-call timeout for the selector. 256-token output × Haiku ≈ < 4s in p99.
_FORK_TIMEOUT = 8.0
# Manifest fetch timeout — daemon-local SQLite is fast.
_MANIFEST_TIMEOUT = 1.0
# Finalize fetch timeout.
_FINALIZE_TIMEOUT = 1.5

# Networking timeouts (seconds). Generous enough for SQLite-backed daemon
# RPC on cold cache, tight enough that a hung daemon doesn't stall the
# Hermes turn for long.
_HEALTH_TIMEOUT = 0.2
_SEARCH_TIMEOUT = 0.8
_LOAD_TIMEOUT = 1.5
_EMIT_TIMEOUT = 0.5

# Tool schemas — mirror phase-0 TS factory exactly. See
# sdk/prismer-cloud/runtime/src/adapters/memory-tools.ts (SharedToolSpec).
# Names and descriptions are FROZEN — adapter parity guarantees one tool
# surface across CC/Hermes/OpenClaw/Codex.

MEMORY_SEARCH_SCHEMA: Dict[str, Any] = {
    "name": "memory_search",
    # Selective wording per doc 25 §3 支柱 1 (M-A) — must stay in lockstep
    # with MEMORY_SEARCH_DESCRIPTION in
    # sdk/prismer-cloud/runtime/src/adapters/memory-tools.ts so all four host
    # adapters present an identical tool surface to the LLM.
    "description": (
        "Search workspace memory (prior decisions, user preferences, "
        "knowledge pages). Use this only when you have a specific question "
        "that you believe past memory would answer — not on every turn. "
        "Most queries do not need this. Returns 0–N ranked snippets with "
        "prismer:// URIs; empty results are normal."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "query": {
                "type": "string",
                "description": (
                    "Free-text search query. Whitespace-separated terms are "
                    "ANDed."
                ),
                "minLength": 1,
            },
            "limit": {
                "type": "integer",
                "description": "Max number of results (default 5, max 20).",
                "minimum": 1,
                "maximum": 20,
                "default": 5,
            },
            "pageType": {
                "type": "array",
                "description": "Optional filter on page kind.",
                "items": {
                    "type": "string",
                    "enum": ["hub", "leaf", "decision", "glossary", "archive"],
                },
            },
        },
        "required": ["query"],
    },
}

MEMORY_RECALL_SCHEMA: Dict[str, Any] = {
    "name": "memory_recall",
    # M-B (doc 25 §3 支柱 2): tool-driven entry point for fork-based recall.
    # Two-stage internally: daemon enumerates candidate pages (Stage 1),
    # provider runs the LLM selector via fork_query (Stage 2), daemon
    # resolves selected paths into RelevantMemory[] (Stage 3). Returns 0-5
    # entries — empty list is normal and preferred over noise.
    "description": (
        "Recall up to 5 memory pages relevant to a free-text question. "
        "Use this when you have a specific question that prior memory "
        "may answer but you are not sure which page to look at. The "
        "selector LLM is told to be selective — it will return an empty "
        "list when nothing clearly applies. Empty results are normal and "
        "you should proceed without recall context. Each result is a "
        "{ pageId, path, title, snippet, mtimeMs, uri }."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "query": {
                "type": "string",
                "description": (
                    "Natural-language question describing what prior "
                    "context might be useful. Whole sentences or "
                    "keywords both work."
                ),
                "minLength": 1,
            },
            "recentTools": {
                "type": "array",
                "description": (
                    "Optional list of tool names the agent has used in "
                    "this conversation. The selector will downweight "
                    "memory pages that are reference docs for these "
                    "tools (active use is its own context already)."
                ),
                "items": {"type": "string"},
            },
        },
        "required": ["query"],
    },
}


MEMORY_LOAD_SCHEMA: Dict[str, Any] = {
    "name": "memory_load",
    "description": (
        "Load a specific memory page by URI "
        "(prismer://workspace/<workspaceId>/memory/<path>) or by "
        "(workspaceId + path). Returns the full page content plus metadata."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "uri": {
                "type": "string",
                "description": (
                    "Full prismer:// URI (preferred). Mutually exclusive "
                    "with workspaceId+path."
                ),
                "pattern": "^prismer://",
            },
            "workspaceId": {
                "type": "string",
                "description": "Workspace identifier (used with `path`).",
            },
            "path": {
                "type": "string",
                "description": (
                    "Workspace-relative memory file path (used with "
                    "`workspaceId`)."
                ),
            },
        },
    },
}


# ---------------------------------------------------------------------------
# Provider
# ---------------------------------------------------------------------------

class PrismerDaemonMemoryProvider(MemoryProvider):
    """Hermes memory provider that bridges to the Prismer daemon.

    All daemon RPC calls are sync httpx; Hermes' provider methods are
    sync, so the sync client matches. On failure, methods log a warning
    and return safe defaults — never raise into Hermes' main loop.

    A single provider instance services one workspace per process. The
    workspace id is read from ``PRISMER_WORKSPACE_ID`` at construction.
    Multi-workspace support is post-MVP.
    """

    def __init__(self) -> None:
        self._daemon_url = os.environ.get("PRISMER_DAEMON_URL", DEFAULT_DAEMON_URL).rstrip("/")
        self._workspace_id = os.environ.get("PRISMER_WORKSPACE_ID", "")
        self._actor_im_user_id = os.environ.get("PRISMER_AGENT_IM_USER_ID", "hermes-agent")
        self._device_id = os.environ.get("PRISMER_DAEMON_ID", "hermes-provider")

        # Cached state
        self._session_id: str = ""
        self._turn_index: int = 0
        self._index_content: str = ""
        self._client: Optional["httpx.Client"] = None
        self._client_lock = threading.Lock()

    # -- Identity & availability --------------------------------------------

    @property
    def name(self) -> str:
        return "prismer-daemon"

    def is_available(self) -> bool:
        """Return True iff env is wired AND the daemon answers /healthz fast.

        The fast-fail probe (200ms timeout) is intentional — Hermes calls
        this during startup to decide whether to activate the provider; a
        long network stall would block agent boot.

        The probe routes through ``self._make_client()`` so that injected
        transports (test fixtures, prod proxy / CA bundle / mTLS) apply
        uniformly across the provider's lifecycle. The client is still
        ephemeral (closed after the probe) — only ``initialize()`` retains
        the persistent client.
        """
        if not _HTTPX_AVAILABLE:
            logger.debug("[PrismerDaemonMemory] httpx not importable — provider unavailable")
            return False
        if not self._workspace_id:
            logger.debug("[PrismerDaemonMemory] PRISMER_WORKSPACE_ID unset — provider unavailable")
            return False
        client = self._make_client()
        if client is None:
            return False
        try:
            with client as c:
                r = c.get(f"{self._daemon_url}/healthz", timeout=_HEALTH_TIMEOUT)
                return r.status_code == 200
        except Exception as e:
            logger.debug("[PrismerDaemonMemory] /healthz probe failed: %s", e)
            return False

    # -- Lifecycle ----------------------------------------------------------

    def initialize(self, session_id: str, **kwargs: Any) -> None:
        """Cache session metadata and preload INDEX.md.

        Called once at agent startup. Failure to fetch INDEX.md is
        non-fatal — provider continues with empty system_prompt_block.
        """
        self._session_id = session_id
        # Allow runtime override from kwargs if Hermes layer sets it.
        kw_actor = kwargs.get("agent_im_user_id") or kwargs.get("agent_identity")
        if kw_actor:
            self._actor_im_user_id = str(kw_actor)
        self._client = self._make_client()
        self._index_content = self._preload_index()

    def shutdown(self) -> None:
        """Close the persistent HTTP client. Safe to call multiple times."""
        with self._client_lock:
            if self._client is not None:
                try:
                    self._client.close()
                except Exception as e:  # pragma: no cover — defensive
                    logger.debug("[PrismerDaemonMemory] client close failed: %s", e)
                self._client = None

    # -- System prompt block + recall ---------------------------------------

    def system_prompt_block(self) -> str:
        """Return INDEX.md + memory-curation skill, both wrapped in headings.

        Two parts, joined with a blank line:

        1. ``## Workspace memory (INDEX)`` — the cached INDEX.md content,
           omitted when load failed (Hermes skips empty blocks anyway).
        2. ``## Memory curation skill`` — the asset-driven memory-page
           guidance from doc 27 §3. Always emitted because the skill text
           is bundled with this module — no daemon dependency.

        Even when INDEX is missing, the skill block alone teaches the
        agent when to write memory pages, so the asset-driven flow works
        on a brand-new workspace with zero existing memory.
        """
        parts: List[str] = []
        if self._index_content:
            parts.append(f"## Workspace memory (INDEX)\n\n{self._index_content}")
        parts.append(f"## Memory curation skill\n\n{MEMORY_CURATION_SKILL_TEXT}")
        return "\n\n".join(parts)

    def prefetch(self, query: str, *, session_id: str = "") -> str:
        """Optionally search workspace memory and return a ``<memory-context>`` fence.

        **Default behavior (M-A, doc 25 §3 支柱 1): no-op.** Returns ""
        without hitting the daemon. Per-turn auto-injection was retired
        because it spammed idle conversation with low-relevance hits,
        polluted the prompt cache key (token cost ↑↑ on long sessions),
        and gave the agent no agency to refuse bad recalls. Agents that
        actually need prior memory call ``memory_search`` selectively
        through the tool surface.

        **Legacy behavior** is preserved behind ``PRISMER_MEMORY_AUTO_PREFETCH=1``:
        when set, runs hybrid search and emits one ``recall_inject`` event
        per included result. Returns empty string on daemon error or zero
        results — never raises.

        Lifecycle precondition: ``initialize()`` must be called first per
        the Hermes ABC contract. If invoked before ``initialize()`` (no
        cached session id), this method logs a warning and returns ""
        rather than operating with undefined session state.
        """
        if not _auto_prefetch_enabled():
            # Default M-A path: no-op. Don't hit the daemon, don't emit
            # observability, don't allocate a fence. The whole point of
            # this default is zero per-turn cost.
            return ""
        if not self._session_id:
            logger.warning(
                "%s: prefetch() called before initialize() — caller must call initialize() first per Hermes ABC",
                self.name,
            )
            return ""
        if not query or not query.strip():
            return ""
        results = self._search(query, top_k=_AUTO_INJECT_TOP_K, max_bytes=_DEFAULT_MAX_BYTES)
        if not results:
            return ""

        # Build the <memory-context> fence — same shape as phase-1 hooks.ts
        # buildFence() so cloud + adapter-side unit tests can use the same
        # fixtures.
        body = "\n\n".join(
            f"## {r.get('path', '<unknown>')}\n{r.get('snippet', '')}"
            for r in results
        )
        fence = f"<memory-context>\n{body}\n</memory-context>"

        # Fire one recall_inject event per result. Failures here are
        # logged-only — the recall content already went into the prompt;
        # missing observability shouldn't break the agent turn.
        for r in results:
            self._emit_observability(
                event_type="recall_inject",
                page_id=r.get("pageId"),
                query=query,
                metrics={
                    "tokenCount": r.get("tokenCount", 0),
                    "relevanceScore": r.get("score", 0.0),
                    "topK": len(results),
                },
                metadata={
                    "sessionId": session_id or self._session_id,
                    "turnIndex": self._turn_index,
                },
            )

        return fence

    def queue_prefetch(self, query: str, *, session_id: str = "") -> None:
        """No-op for v0.

        Hermes' background-prefetch optimization (queue_prefetch fires
        after a turn so the next turn's prefetch() returns cached results
        without blocking) is post-MVP per doc 23 §10. The daemon's hybrid
        search is fast enough on local SQLite that synchronous prefetch
        is acceptable — we revisit if benchmarks show p95 latency issues.
        """

    def sync_turn(self, user_content: str, assistant_content: str, *, session_id: str = "") -> None:
        """No-op for v0.

        Per-turn writes back to workspace memory are aggressive — every
        turn would flood ``im_memory_files`` with raw conversation
        chunks. v0 ships only the read path. Real consolidation
        (deduped, distilled facts) is doc 19 I6's 4-stage subagent flow,
        dispatched separately. We track turn index for observability
        attribution but emit nothing here.
        """
        self._turn_index += 1

    def on_session_end(self, messages: List[Dict[str, Any]]) -> None:
        """M-C session-end fork extract (doc 25 §3 支柱 3).

        Walks the session transcript, asks the host LLM via
        ``fork_query`` to propose 0–3 short memory updates, and emits
        each accepted proposal to the daemon outbox as a
        ``memory.proposal`` envelope event. The daemon's outbox worker
        carries them to the cloud's ``/memory/sync/inbox``, which routes
        them into ``im_memory_proposals`` for the user to review in the
        Library Memory view.

        Failure modes return early without raising:
          - empty transcript
          - daemon RPC client unavailable
          - fork_query returns "" (no API key, network error)
          - selector LLM returned malformed JSON

        The agent-actor JWT problem (per outbox-worker.ts header note):
        these proposals carry ``actorImUserId = self._actor_im_user_id``,
        which Line A's sync inbox filters against ``JWT.subject``. The
        daemon's existing CloudClient uses the human-owner token, so
        agent-actor proposals stay in pending status until per-agent
        token issuance ships. That's acceptable for v0 — they're just
        held in the daemon outbox a bit longer.
        """
        if not _HTTPX_AVAILABLE or not messages:
            return
        if not self._session_id or not self._workspace_id:
            return
        # Build a compact transcript. Cap at ~4000 chars to keep the
        # extract LLM call cheap; older messages are discarded.
        transcript = self._compress_transcript(messages, max_chars=4000)
        if not transcript:
            return
        try:
            raw = self.fork_query(_EXTRACT_SYSTEM_PROMPT, transcript, max_tokens=1024)
        except Exception as err:
            logger.warning("[PrismerDaemonMemory] on_session_end fork_query failed: %s", err)
            return
        proposals = _parse_extract_output(raw)
        if not proposals:
            return
        # Emit each proposal as a memory.proposal envelope through the
        # existing /local/memory/observability/emit endpoint (it's a
        # pass-through to slot.outbox.enqueue with envelope schema
        # validation).
        client = self._get_client()
        if client is None:
            return
        for p in proposals:
            event_id = uuid.uuid4().hex[:26].upper()
            created_at = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
            envelope: Dict[str, Any] = {
                "eventId": event_id,
                "schemaVersion": 1,
                "eventType": "memory.proposal",
                "workspaceId": self._workspace_id,
                "actorImUserId": self._actor_im_user_id,
                "actorKind": "agent",
                "deviceId": self._device_id,
                "createdAt": created_at,
                "idempotencyKey": f"proposal:{self._session_id}:{p['path']}:{event_id[:8]}",
                "sessionId": self._session_id,
                "pagePath": p["path"],
                "baseVersion": 0,
                "operation": "create",
                "contentDiff": f"# {p['title']}\n\n{p['summary']}",
                "rationale": p.get("rationale", ""),
                "confidence": p["confidence"],
                "sourceRefs": [f"session:{self._session_id}"],
            }
            try:
                client.post(
                    f"{self._daemon_url}/local/memory/observability/emit",
                    json=envelope,
                    timeout=_EMIT_TIMEOUT,
                )
            except Exception as err:
                logger.debug("[PrismerDaemonMemory] proposal emit failed (%s): %s", p["path"], err)

    def _compress_transcript(self, messages: List[Dict[str, Any]], *, max_chars: int) -> str:
        """Render a Hermes message list into a short transcript string.

        Hermes messages are typically ``{ role, content }`` dicts;
        we accept lists of such dicts and project to ``ROLE: content``
        lines, truncating from the FRONT (older messages discarded
        first) to fit the budget. The fork extract LLM only needs
        recent decisions, not the full session.
        """
        lines: List[str] = []
        for m in messages:
            if not isinstance(m, dict):
                continue
            role = str(m.get("role") or "").strip().upper()
            content = m.get("content")
            if isinstance(content, list):
                # Some hosts return [{type:'text', text:'...'}].
                pieces: List[str] = []
                for blk in content:
                    if isinstance(blk, dict) and blk.get("type") == "text":
                        t = blk.get("text")
                        if isinstance(t, str):
                            pieces.append(t)
                content = "\n".join(pieces)
            if not isinstance(content, str):
                continue
            content = content.strip()
            if not content:
                continue
            lines.append(f"{role}: {content}")
        if not lines:
            return ""
        out = "\n".join(lines)
        # Truncate from the front so the most recent turns survive.
        if len(out) > max_chars:
            out = out[-max_chars:]
            # Snap to the nearest line boundary for readability.
            nl = out.find("\n")
            if nl > 0:
                out = out[nl + 1 :]
        return out

    # -- Tools --------------------------------------------------------------

    def get_tool_schemas(self) -> List[Dict[str, Any]]:
        """Return ``memory_search`` + ``memory_load`` + ``memory_recall`` tool schemas.

        Mirrors the phase-0 TS factory at
        ``sdk/prismer-cloud/runtime/src/adapters/hermes/memory-tools.ts``.
        Names + descriptions are frozen across all four host adapters
        (Claude Code, Hermes, OpenClaw, Codex) so an LLM running in any
        of them sees the same tool surface.

        ``memory_recall`` (M-B, doc 25 §3 支柱 2) added on top of the
        phase-0 surface — fork-driven 2-stage selector. Empty results
        are normal; agents proceed without recall context when the
        selector returns nothing.
        """
        return [MEMORY_SEARCH_SCHEMA, MEMORY_LOAD_SCHEMA, MEMORY_RECALL_SCHEMA]

    def handle_tool_call(self, tool_name: str, args: Dict[str, Any], **kwargs: Any) -> str:
        """Dispatch a tool call and return a JSON-encoded result.

        Per Hermes ABC, must return a JSON string (the model sees this
        as the tool result). Always emits a ``recall_pull`` event so the
        trace tab attributes the read to the agent.

        Lifecycle precondition: ``initialize()`` must be called first per
        the Hermes ABC contract. If invoked before ``initialize()`` (no
        cached session id), returns a ``provider_not_initialized`` error
        JSON rather than raising — raising would kill the Hermes agent
        loop, which violates the "no exception bubbles into Hermes' main
        loop" invariant.
        """
        if not self._session_id:
            logger.warning(
                "%s: handle_tool_call(%r) called before initialize() — caller must call initialize() first per Hermes ABC",
                self.name,
                tool_name,
            )
            return json.dumps({
                "error": "provider_not_initialized",
                "message": "PrismerDaemonMemoryProvider.initialize() must be called before tool dispatch",
            })
        if tool_name == "memory_search":
            return self._tool_memory_search(args)
        if tool_name == "memory_load":
            return self._tool_memory_load(args)
        if tool_name == "memory_recall":
            return self._tool_memory_recall(args)
        return json.dumps({
            "error": "unknown_tool",
            "message": f"PrismerDaemonMemoryProvider does not handle tool {tool_name!r}",
        })

    # -- Internals ----------------------------------------------------------

    def _make_client(self) -> Optional["httpx.Client"]:
        if not _HTTPX_AVAILABLE:
            return None
        # Default timeout is overridden per-call. Persistent client reuses
        # the TCP connection across calls (matters for high-frequency
        # observability emissions).
        return httpx.Client(timeout=_LOAD_TIMEOUT)

    def _get_client(self) -> Optional["httpx.Client"]:
        with self._client_lock:
            if self._client is None and _HTTPX_AVAILABLE:
                self._client = self._make_client()
            return self._client

    def _preload_index(self) -> str:
        """Fetch INDEX.md content via daemon RPC, cap at 200 lines / 25 KB.

        Returns "" when the page doesn't exist (404), the daemon errors,
        or content is empty.
        """
        client = self._get_client()
        if client is None:
            return ""
        uri = f"prismer://workspace/{self._workspace_id}/memory/INDEX.md"
        try:
            r = client.get(
                f"{self._daemon_url}/local/memory/load",
                params={"uri": uri},
                timeout=_LOAD_TIMEOUT,
            )
        except Exception as e:
            logger.warning("[PrismerDaemonMemory] INDEX.md preload network error: %s", e)
            return ""
        if r.status_code == 404:
            logger.debug("[PrismerDaemonMemory] no INDEX.md in workspace %s", self._workspace_id)
            return ""
        if r.status_code != 200:
            logger.warning(
                "[PrismerDaemonMemory] INDEX.md load returned HTTP %d", r.status_code,
            )
            return ""
        try:
            body = r.json()
        except Exception as e:
            logger.warning("[PrismerDaemonMemory] INDEX.md JSON decode failed: %s", e)
            return ""
        content = body.get("content")
        if not content or not isinstance(content, str):
            return ""
        return _truncate_to_budget(content, max_lines=_INDEX_MAX_LINES, max_bytes=_INDEX_MAX_BYTES)

    def _search(
        self,
        query: str,
        *,
        top_k: int = _AUTO_INJECT_TOP_K,
        max_bytes: int = _DEFAULT_MAX_BYTES,
        page_type: Optional[str] = None,
    ) -> List[Dict[str, Any]]:
        """Call ``GET /local/memory/search`` and return parsed results.

        Returns ``[]`` on any failure — never raises.

        ``page_type`` mirrors the canonical TS adapter's single-value
        ``pageType`` query param (see
        ``sdk/prismer-cloud/runtime/src/adapters/memory-tools.ts`` —
        daemon's ``/local/memory/search`` accepts one ``pageType`` per
        request; multi-value support is post-MVP). Pass ``None`` to omit
        the filter entirely.
        """
        client = self._get_client()
        if client is None:
            return []
        params: Dict[str, Any] = {
            "workspaceId": self._workspace_id,
            "q": query,
            "topK": top_k,
            "maxBytes": max_bytes,
        }
        if page_type:
            params["pageType"] = page_type
        try:
            r = client.get(
                f"{self._daemon_url}/local/memory/search",
                params=params,
                timeout=_SEARCH_TIMEOUT,
            )
        except Exception as e:
            logger.warning("[PrismerDaemonMemory] memory_search network error: %s", e)
            return []
        if r.status_code != 200:
            logger.warning("[PrismerDaemonMemory] memory_search HTTP %d", r.status_code)
            return []
        try:
            body = r.json()
        except Exception:
            return []
        results = body.get("results")
        if not isinstance(results, list):
            return []
        return results

    def _load_page(
        self,
        *,
        uri: Optional[str] = None,
        workspace_id: Optional[str] = None,
        path: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]:
        """Call ``GET /local/memory/load`` and return ``{ page, content }``.

        Returns ``None`` on 404 / network error / decode error.
        """
        client = self._get_client()
        if client is None:
            return None
        params: Dict[str, str] = {}
        if uri:
            params["uri"] = uri
        elif workspace_id and path:
            params["workspaceId"] = workspace_id
            params["path"] = path
        else:
            return None
        try:
            r = client.get(
                f"{self._daemon_url}/local/memory/load",
                params=params,
                timeout=_LOAD_TIMEOUT,
            )
        except Exception as e:
            logger.warning("[PrismerDaemonMemory] memory_load network error: %s", e)
            return None
        if r.status_code != 200:
            return None
        try:
            return r.json()
        except Exception:
            return None

    def _emit_observability(
        self,
        *,
        event_type: str,
        page_id: Optional[str] = None,
        query: Optional[str] = None,
        metrics: Optional[Dict[str, Any]] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> None:
        """POST a recall_inject / recall_pull / etc. event to the daemon.

        Fire-and-forget: a 200 ack from the daemon means the envelope was
        validated and persisted; a 4xx/5xx is logged but never raises.
        Idempotency keys are crafted so repeat emits dedupe at the outbox
        UNIQUE constraint level — see envelope.ts header comment.
        """
        client = self._get_client()
        if client is None:
            return
        event_id = uuid.uuid4().hex[:26].upper()  # ULID-ish ASCII; daemon only checks min(1)
        created_at = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
        # Idempotency keys mirror hooks.ts so the same wire format works on
        # both in-process (daemon hooks) and out-of-process (this provider)
        # emissions — observability dashboards see one event family.
        idempotency_key = (
            f"obs:{event_type}:{self._actor_im_user_id}:{created_at}:{event_id[:8]}"
        )
        envelope: Dict[str, Any] = {
            "eventId": event_id,
            "schemaVersion": 1,
            "eventType": event_type,
            "workspaceId": self._workspace_id,
            "actorImUserId": self._actor_im_user_id,
            "actorKind": "agent",
            "deviceId": self._device_id,
            "createdAt": created_at,
            "idempotencyKey": idempotency_key,
        }
        if page_id is not None:
            envelope["pageId"] = page_id
        if query is not None:
            envelope["query"] = query
        if metrics is not None:
            envelope["metricsJson"] = metrics
        if metadata is not None:
            envelope["metadataJson"] = metadata
        try:
            client.post(
                f"{self._daemon_url}/local/memory/observability/emit",
                json=envelope,
                timeout=_EMIT_TIMEOUT,
            )
        except Exception as e:
            # Don't surface — observability misses are tolerable; killing
            # an agent turn over an event emit is not.
            logger.debug("[PrismerDaemonMemory] observability emit failed (%s): %s", event_type, e)

    # -- Tool dispatch ------------------------------------------------------

    def _tool_memory_search(self, args: Dict[str, Any]) -> str:
        query = args.get("query") or ""
        if not query:
            return json.dumps({"error": "missing_query", "message": "memory_search requires `query`"})
        limit = int(args.get("limit") or _TOOL_DEFAULT_TOP_K)
        # Clamp per schema (max 20).
        limit = max(1, min(limit, 20))
        # Schema declares ``pageType`` as an array; daemon accepts a single
        # value per request — take the first (mirrors canonical TS adapter
        # at sdk/prismer-cloud/runtime/src/adapters/memory-tools.ts).
        page_type_arg = args.get("pageType")
        page_type: Optional[str] = None
        if isinstance(page_type_arg, list) and page_type_arg:
            first = page_type_arg[0]
            if isinstance(first, str) and first:
                page_type = first
        elif isinstance(page_type_arg, str) and page_type_arg:
            # Tolerate scalar string (some LLMs mis-serialize single-element
            # array filters as a bare string).
            page_type = page_type_arg
        results = self._search(
            query,
            top_k=limit,
            max_bytes=_DEFAULT_MAX_BYTES,
            page_type=page_type,
        )

        # Emit one recall_pull per result so the trace tab attributes the
        # read. We do this even when the agent triggered the tool call
        # (vs auto-injection in prefetch) — recall_pull is the
        # tool-initiated variant.
        for r in results:
            self._emit_observability(
                event_type="recall_pull",
                page_id=r.get("pageId"),
                query=query,
                metrics={
                    "tokenCount": r.get("tokenCount", 0),
                    "relevanceScore": r.get("score", 0.0),
                    "topK": len(results),
                },
                metadata={
                    "sessionId": self._session_id,
                    "turnIndex": self._turn_index,
                    "tool": "memory_search",
                },
            )
        return json.dumps({"query": query, "results": results})

    # ─── M-B fork-recall (doc 25 §3 支柱 2) ───────────────────────────────

    def fork_query(
        self,
        system: str,
        user: str,
        *,
        max_tokens: int = 256,
    ) -> str:
        """Run a one-shot LLM call with cache-safe parameters.

        Posts to the Anthropic API directly via httpx (already a top-level
        prismer dep). The host (Hermes) holds the API key, not the daemon
        — option A from doc 25 §7 judgment 4. ``cache_safe=True`` is
        implicit: callers pass the same ``system`` + ``model`` as the
        parent session would, and the API's prompt cache stickiness
        amortizes the selector cost across turns.

        Returns the assistant's text content, or "" on missing key /
        network error / non-OK response. Never raises — the fork-recall
        path treats failure as "selector chose nothing".

        Lifecycle precondition: caller must set the API key via
        ``PRISMER_MEMORY_FORK_API_KEY`` (preferred) or
        ``ANTHROPIC_API_KEY``. Without a key, returns "".
        """
        if not _HTTPX_AVAILABLE:
            logger.debug("[PrismerDaemonMemory] fork_query: httpx unavailable")
            return ""
        api_key = (
            os.environ.get(_FORK_API_KEY_ENV)
            or os.environ.get("ANTHROPIC_API_KEY")
            or ""
        ).strip()
        if not api_key:
            logger.debug("[PrismerDaemonMemory] fork_query: no API key configured")
            return ""
        model = os.environ.get(_FORK_MODEL_ENV, _FORK_MODEL_DEFAULT).strip() or _FORK_MODEL_DEFAULT
        body: Dict[str, Any] = {
            "model": model,
            "max_tokens": max_tokens,
            "system": system,
            "messages": [{"role": "user", "content": user}],
        }
        try:
            with httpx.Client(timeout=_FORK_TIMEOUT) as c:
                r = c.post(
                    f"{_ANTHROPIC_API_BASE}/v1/messages",
                    headers={
                        "x-api-key": api_key,
                        "anthropic-version": _ANTHROPIC_API_VERSION,
                        "content-type": "application/json",
                    },
                    json=body,
                )
        except Exception as e:
            logger.warning("[PrismerDaemonMemory] fork_query network error: %s", e)
            return ""
        if r.status_code != 200:
            logger.warning(
                "[PrismerDaemonMemory] fork_query HTTP %d: %s",
                r.status_code,
                r.text[:200],
            )
            return ""
        try:
            payload = r.json()
        except Exception as e:
            logger.warning("[PrismerDaemonMemory] fork_query JSON decode failed: %s", e)
            return ""
        # Anthropic's response shape: { content: [{ type: "text", text: "…" }, ...] }
        blocks = payload.get("content") or []
        for blk in blocks:
            if isinstance(blk, dict) and blk.get("type") == "text":
                txt = blk.get("text")
                if isinstance(txt, str):
                    return txt
        return ""

    def _fetch_manifest(
        self,
        query: str,
        limit: int = MAX_MANIFEST_ENTRIES,
    ) -> List[Dict[str, Any]]:
        """GET /local/memory/recall/manifest. Returns [] on error."""
        client = self._get_client()
        if client is None:
            return []
        params: Dict[str, Any] = {"workspaceId": self._workspace_id, "q": query, "limit": limit}
        try:
            r = client.get(
                f"{self._daemon_url}/local/memory/recall/manifest",
                params=params,
                timeout=_MANIFEST_TIMEOUT,
            )
        except Exception as e:
            logger.warning("[PrismerDaemonMemory] recall manifest network error: %s", e)
            return []
        if r.status_code != 200:
            logger.warning("[PrismerDaemonMemory] recall manifest HTTP %d", r.status_code)
            return []
        try:
            body = r.json()
        except Exception:
            return []
        entries = body.get("entries")
        return entries if isinstance(entries, list) else []

    def _finalize_recall(self, paths: List[str]) -> List[Dict[str, Any]]:
        """POST /local/memory/recall/finalize. Returns [] on error."""
        client = self._get_client()
        if client is None or not paths:
            return []
        try:
            r = client.post(
                f"{self._daemon_url}/local/memory/recall/finalize",
                json={"workspaceId": self._workspace_id, "paths": paths},
                timeout=_FINALIZE_TIMEOUT,
            )
        except Exception as e:
            logger.warning("[PrismerDaemonMemory] recall finalize network error: %s", e)
            return []
        if r.status_code != 200:
            logger.warning("[PrismerDaemonMemory] recall finalize HTTP %d", r.status_code)
            return []
        try:
            body = r.json()
        except Exception:
            return []
        results = body.get("results")
        return results if isinstance(results, list) else []

    @staticmethod
    def _format_manifest(entries: List[Dict[str, Any]]) -> str:
        """Format a manifest into the ``- path [title] — description`` block.

        Mirrors the TS-side ``formatManifest`` in
        ``daemon/memory/fork/select-memories.ts``. Both copies must
        produce identical output so the selector LLM sees a stable shape
        regardless of which host orchestrated it.
        """
        out: List[str] = []
        for e in entries[:MAX_MANIFEST_ENTRIES]:
            path = e.get("path") or ""
            if not path:
                continue
            title = e.get("title")
            desc = e.get("description") or "(no description)"
            if isinstance(desc, str) and len(desc) > 200:
                desc = desc[:199] + "…"
            title_part = f" [{title[:79] + '…' if isinstance(title, str) and len(title) > 80 else title}]" if title else ""
            out.append(f"- {path}{title_part} — {desc}")
        return "\n".join(out)

    @staticmethod
    def _parse_selector_output(raw_text: str, entries: List[Dict[str, Any]]) -> List[str]:
        """Parse JSON from the LLM, validate paths against the manifest.

        Mirrors the TS ``parseSelectorOutput`` — tolerates ```json fences,
        drops hallucinated paths, dedups, caps at MAX_SELECTED. Returns
        an empty list on any parse failure (never throws).
        """
        text = raw_text.strip()
        if not text:
            return []
        # Strip optional code-fence wrapper.
        if text.startswith("```"):
            text = text.lstrip("`")
            if text.lower().startswith("json"):
                text = text[4:]
            text = text.strip()
            if text.endswith("```"):
                text = text[:-3].strip()
        try:
            parsed = json.loads(text)
        except Exception:
            return []
        if not isinstance(parsed, dict):
            return []
        names = parsed.get("selected_memories")
        if not isinstance(names, list):
            return []
        valid_paths = {e.get("path") for e in entries if isinstance(e.get("path"), str)}
        out: List[str] = []
        for n in names:
            if not isinstance(n, str):
                continue
            if n not in valid_paths:
                continue
            if n in out:
                continue
            out.append(n)
            if len(out) >= MAX_SELECTED:
                break
        return out

    def _tool_memory_recall(self, args: Dict[str, Any]) -> str:
        """Handle a ``memory_recall`` tool call.

        Drives the 3-stage flow: manifest → fork_query → finalize. Empty
        result is a normal outcome — the selector is told to be selective
        and we never want to pretend recall succeeded when it didn't.
        Emits one ``recall_pull`` per finalized entry so the trace tab
        reflects fork-driven recalls just like agent-driven ones.
        """
        query = args.get("query") or ""
        if not isinstance(query, str) or not query.strip():
            return json.dumps({"error": "missing_query", "message": "memory_recall requires `query`"})
        recent_tools_raw = args.get("recentTools") if isinstance(args, dict) else None
        recent_tools: List[str] = []
        if isinstance(recent_tools_raw, list):
            recent_tools = [t for t in recent_tools_raw if isinstance(t, str)]

        # Stage 1 — manifest from daemon.
        entries = self._fetch_manifest(query)
        if not entries:
            return json.dumps({"query": query, "results": []})

        # Stage 2 — host LLM selector. fork_query() returns "" on no-key
        # or transport error; treat as "selector chose nothing".
        manifest_text = self._format_manifest(entries)
        tools_section = (
            f"\n\nRecently used tools: {', '.join(recent_tools)}" if recent_tools else ""
        )
        user_msg = f"Query: {query}\n\nAvailable memories:\n{manifest_text}{tools_section}"
        raw = self.fork_query(SELECT_MEMORIES_SYSTEM_PROMPT, user_msg, max_tokens=256)
        selected_paths = self._parse_selector_output(raw, entries)
        if not selected_paths:
            return json.dumps({"query": query, "results": []})

        # Stage 3 — daemon resolves selected paths to RelevantMemory[].
        results = self._finalize_recall(selected_paths)
        # Per-result observability so the trace tab attributes recall_pull
        # to the correct page even when fork drove the selection.
        for r in results:
            self._emit_observability(
                event_type="recall_pull",
                page_id=r.get("pageId"),
                query=query,
                metrics={"tokenCount": _estimate_tokens(r.get("snippet") or "")},
                metadata={
                    "sessionId": self._session_id,
                    "turnIndex": self._turn_index,
                    "tool": "memory_recall",
                    "forkLabel": "memory_recall",
                },
            )
        return json.dumps({"query": query, "results": results})

    def _tool_memory_load(self, args: Dict[str, Any]) -> str:
        uri = args.get("uri")
        ws = args.get("workspaceId")
        path = args.get("path")
        loaded = self._load_page(uri=uri, workspace_id=ws, path=path)
        if loaded is None:
            return json.dumps({"error": "not_found", "message": "memory_load: page not found"})
        page = loaded.get("page") or {}
        # Emit recall_pull. Page id from the response so we attribute to
        # the canonical id even when the caller passed a path.
        self._emit_observability(
            event_type="recall_pull",
            page_id=page.get("id"),
            query=None,
            metrics={"tokenCount": _estimate_tokens(loaded.get("content") or "")},
            metadata={
                "sessionId": self._session_id,
                "turnIndex": self._turn_index,
                "tool": "memory_load",
                "uri": uri,
                "path": path,
            },
        )
        return json.dumps(loaded)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _truncate_to_budget(content: str, *, max_lines: int, max_bytes: int) -> str:
    """Mirrors hooks.ts ``truncateToBudget`` — line cap then byte cap."""
    out = content
    lines = out.split("\n")
    if len(lines) > max_lines:
        out = "\n".join(lines[:max_lines])
    while len(out.encode("utf-8")) > max_bytes and out:
        cut = max(1, int(len(out) * 0.9))
        out = out[:cut]
    return out


def _estimate_tokens(s: str) -> int:
    """Rough char-to-token estimate matching hooks.ts ``estimateTokens``."""
    return -(-len(s) // 4)  # ceil(len/4)


# ---------------------------------------------------------------------------
# Plugin entry point — see plugins/memory/__init__.py for discovery
# ---------------------------------------------------------------------------

def register(ctx: Any) -> None:  # pragma: no cover — wiring tested via T3
    """Hermes plugin discovery hook.

    Called from ``plugins/memory/<name>/__init__.py`` when the user sets
    ``memory.provider = prismer-daemon``. T3 (separate task) ships the
    plugin shell that imports + registers this class.
    """
    ctx.register_memory_provider(PrismerDaemonMemoryProvider())
