/**
 * Frontend-only DTO shapes for /workspace.
 *
 * Mirrors the JSON envelopes returned by the IM router; we keep these on the
 * frontend so /app pages do NOT import from `src/im/**` (per CLAUDE.md / 03 plan).
 */

export interface WorkspaceDTO {
  id: string;
  ownerImUserId: string;
  name: string;
  slug: string;
  isDefault: boolean;
  metadata: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
}

export interface UserProfileDTO {
  id: string;
  username: string;
  displayName: string;
  role: 'human' | 'agent' | string;
  agentType?: string | null;
  avatarUrl?: string | null;
  primaryDid?: string | null;
  metadata?: Record<string, unknown>;
  createdAt?: string;
}

export interface ContactFriendDTO {
  userId: string;
  username: string;
  displayName: string;
  role: 'human' | 'agent' | string;
  avatarUrl?: string | null;
  isAgent: boolean;
  institution?: string;
  lastSeenAt?: string;
  remark?: string | null;
  addedAt: string;
}

export interface ContactRequestDTO {
  id: string;
  fromUserId: string;
  toUserId: string;
  reason?: string | null;
  source?: string | null;
  status: 'pending' | 'accepted' | 'rejected' | 'expired' | string;
  createdAt: string;
  fromUser?: {
    username: string;
    displayName: string;
    avatarUrl?: string | null;
  };
  toUser?: {
    username: string;
    displayName: string;
    avatarUrl?: string | null;
  };
}

export interface ConversationDTO {
  id: string;
  type: 'direct' | 'group' | string;
  title: string | null;
  displayTitle?: string | null;
  description: string | null;
  status: string;
  workspaceId: string | null;
  createdById: string;
  lastMessageAt: string | null;
  /** Caller's role on the participant row — undefined when not enriched. */
  myRole?: string;
  pinned?: boolean;
  pinnedAt?: string | null;
  muted?: boolean;
  unreadCount?: number;
  metadata?: string | Record<string, unknown>;
  participants?: Array<{
    userId: string;
    username: string;
    displayName: string;
    role: string;
    userRole?: string;
    agentType?: string | null;
  }>;
}

/**
 * AgentDTO mirrors `GET /api/im/agents` envelope: agent registry rows expose
 * `agentId` (IMAgentCard.id) + `userId` (IMUser.id, == agentImUserId in
 * AgentProfile speak), NOT a generic `id`. Matching profiles back to agents
 * keys off `userId`, since IMAgentProfile.agentImUserId references IMUser.id.
 */
export interface AgentDTO {
  agentId: string;
  userId: string;
  name: string;
  /**
   * IM-side slug handle (IMUser.username). Auto-generated by backend at create
   * time as `{role-slug}-{cuid4}`; user can rename via §30 B3.8 inline editor.
   * Lower-case, hyphen-separated, globally unique.
   */
  username?: string;
  description?: string | null;
  agentType?: string | null;
  capabilities?: string[];
  status?: string;
  load?: number;
  presence?: { status?: string; lastSeen?: number | null };
}

/**
 * Workspace runtime topology — Workspace → Device → Agent tree.
 *
 * Sourced from `GET /api/im/workspaces/:wsId/runtime` (Cloud 4 daemon heartbeat
 * feed). Wave-6 δ wires the LeftRail tree off this snapshot; flat AgentDTO
 * remains the source for dialogs that need full agent metadata.
 *
 * Note: server-side device shape has no top-level `status` — clients derive
 * `online` from `lastSeenAt` freshness (heartbeat window).
 */
export interface RuntimeAgentDTO {
  id: string; // == imUserId
  name: string;
  status: 'online' | 'busy' | 'idle' | 'offline';
  currentTaskId: string | null;
  version: string | null;
  lastHeartbeat: string | null;
}

/**
 * Wave-8 W5 — three-layer readiness model. The daemon "device" is the
 * execution surface; readiness collapses heartbeat freshness into one of:
 *   connected — heartbeat within ONLINE_WINDOW_MS (90s)
 *   stale     — heartbeat older than 90s but device row exists
 *   offline   — no heartbeat recorded yet
 */
export type RuntimeDaemonStatus = 'connected' | 'stale' | 'offline';

export interface RuntimeDeviceDTO {
  deviceId: string;
  name: string;
  lastSeenAt: string | null;
  agents: RuntimeAgentDTO[];
  daemonStatus?: RuntimeDaemonStatus;
}

export interface WorkspaceRuntimeDTO {
  workspaceId: string;
  devices: RuntimeDeviceDTO[];
}

export interface RuntimeInstallationEventDTO {
  at: string;
  kind: string;
  severity: 'info' | 'warn' | 'error' | string;
  message: string;
}

export interface WorkspaceSignalDTO {
  status: string | null;
  latencyMs: number | null;
  lastError: string | null;
  updatedAt: string | null;
}

export interface WorkspaceBridgeSnapshotDTO {
  hermes?: WorkspaceSignalDTO | null;
  provider?: WorkspaceSignalDTO | null;
  memory?: WorkspaceSignalDTO | null;
  board?: WorkspaceSignalDTO | null;
  goal?: WorkspaceSignalDTO | null;
}

/**
 * Wave-8 W5 — runtime card readiness states. Computed server-side so the UI
 * can render colored dots without re-deriving from raw `status` strings.
 *
 *   provisioning — controller creating pod / pulling image (status pending|warming|starting)
 *   running      — controller reports running|bound and DB row not stoppedAt
 *   failing      — status errored|failed
 *   stopped      — DB row stoppedAt set OR status stopped|stopping
 *   unknown      — fallback
 */
export type RuntimeContainerStatus = 'provisioning' | 'running' | 'failing' | 'stopped' | 'unknown';

export interface RuntimeHostedAgentSummary {
  declared: number;
  expected: number;
  verified: boolean;
}

/**
 * Wave-8 W11 — runtime backing kind. `docker` is the legacy local-daemon flow
 * provisioned via the existing "Managed k8s" entry button. `k8s` is the
 * wizard-provisioned isolated pod with explicit template + resource picks.
 * Optional + omitted on rows from older deployments — readers MUST default to
 * `'docker'` so unrecognised payloads stay backwards-compatible.
 */
export type RuntimeKind = 'docker' | 'k8s';

export interface RuntimeInstallationDTO {
  id: string;
  workspaceId: string;
  runtimeInstanceId: string;
  daemonId: string;
  podName: string;
  namespace: string;
  /** Wave-8 W11 — backing kind ("docker" | "k8s"). Missing on legacy rows. */
  runtimeKind?: RuntimeKind;
  /**
   * Migration 323 — §30 §2.6 device capacity model. Maximum number of
   * agents allowed to register against this device. Default 3 (Web base
   * subscription). Server-side enforcement at `POST /api/im/register`
   * returns HTTP 409 `{ error: { code: 'CAPACITY_EXCEEDED' }, meta: { used, max } }`
   * when the count reaches this ceiling.
   */
  maxAgents: number;
  phase: 'provisioning' | 'online' | 'degraded' | 'stopped' | 'failed' | string;
  desiredState: 'running' | 'stopped' | string;
  status: string;
  /** W5 readiness — container plane (DB row + controller phase). */
  containerStatus: RuntimeContainerStatus;
  /** W5 readiness — daemon plane (heartbeat freshness). */
  daemonStatus: RuntimeDaemonStatus;
  /** W5 readiness — hosted agents declared via `agent.host.declare` vs expected. */
  hostedAgentSummary: RuntimeHostedAgentSummary;
  image: string;
  imageTag: string;
  resources: {
    cpuRequest: string;
    cpuLimit: string;
    memoryRequest: string;
    memoryLimit: string;
  };
  gatewayUrl: string | null;
  startedAt: string | null;
  stoppedAt: string | null;
  createdAt: string;
  updatedAt: string;
  metrics: {
    ageMs: number;
    provisionLatencyMs: number | null;
    heartbeatAgeMs: number | null;
    hostedAgents: number;
    onlineHostedAgents: number;
  };
  observability: {
    statusFreshness: string;
    logsPath: string;
    startPath: string;
    stopPath: string;
    snapshotPath: string;
  };
  bridge?: WorkspaceBridgeSnapshotDTO | null;
  events: RuntimeInstallationEventDTO[];
  /**
   * Migration 322 — provisioning progress signals. `step` is the current
   * in-flight step name (or null when terminal); `history` is the
   * ordered append-only list of step transitions. Older cloud builds may
   * omit the field entirely — UI tolerates `undefined`.
   */
  provisioning?: {
    step: ProvisioningStep | null;
    history: ProvisioningHistoryEntry[];
  };
}

/** Canonical 7-step lifecycle, see `src/lib/provisioning-progress.ts`. */
export type ProvisioningStep =
  | 'container_create'
  | 'container_running'
  | 'daemon_healthy'
  | 'ws_connected'
  | 'host_declared'
  | 'adapter_installed'
  | 'ready';

export interface ProvisioningHistoryEntry {
  step: ProvisioningStep;
  status: 'in_progress' | 'ok' | 'error';
  startedAt: number;
  durationMs?: number;
  error?: string;
}

export interface RuntimeInstallAgentResultDTO {
  runtimeInstallationId: string;
  podName: string;
  result: {
    ok: true;
    daemonId: string;
    installedAgent: {
      imUserId: string;
      name: string;
      adapterName: string;
      profileId: string;
    };
    hostedAgents: Array<{ imUserId: string; name: string; adapterName: string }>;
  };
  profile: {
    id: string;
    agentImUserId: string;
    adapterName: string;
    name: string;
    version: number;
  };
}

export interface LocalDaemonHealthDTO {
  status: string;
  daemonId: string;
  cloudBaseUrl?: string;
  workspaceId?: string | null;
  pid: number;
  startedAt: number;
  wsConnected: boolean;
  hostedAgents?: Array<{ imUserId: string; name: string; adapterName: string }>;
}

export interface LocalDaemonInstallResultDTO {
  ok: true;
  daemonId: string;
  installedAgent: {
    imUserId: string;
    name: string;
    adapterName: string;
    profileId: string;
  };
  hostedAgents: Array<{ imUserId: string; name: string; adapterName: string }>;
}

export interface AgentProfileDTO {
  id: string;
  workspaceId: string;
  agentImUserId: string;
  adapterName: string;
  name: string;
  config: Record<string, unknown>;
  version: number;
  createdAt: string;
  updatedAt: string;
}

export interface WorkspaceFileDTO {
  id: string;
  workspaceId: string;
  path: string;
  assetId: string;
  contentHash?: string;
  version: number;
  parentVersionId: string | null;
  modifierImUserId: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
}

export interface AssetDTO {
  id: string;
  workspaceId: string;
  ownerImUserId: string;
  contentHash: string;
  storageUri: string;
  sizeBytes: number | null;
  mime: string | null;
  kind: string;
  sourceAgentImUserId: string | null;
  sourceTaskId: string | null;
  metadata: Record<string, unknown>;
  parentAssetId?: string | null;
  derivationKind?: string | null;
  ingestStatus?: string;
  ingestVersion?: number;
  ingestError?: string | null;
  assetIndexSeq?: number;
  cdnUrl?: string | null;
  previewAssetId?: string | null;
  folderPath?: string | null;
  filename?: string | null;
  sourceRef?: string | null;
  sourceKind?: string | null;
  sourceMetadata?: Record<string, unknown> | null;
  revision?: number;
  visibility?: string;
  aclJson?: Record<string, unknown> | null;
  /** Wave-54 B2: optional ≤500-char hint surfaced to other agents (and now in Library Files UI — D5). */
  description?: string | null;
  updatedAt?: string;
  createdAt: string;
  deletedAt?: string | null;
  memoryPages?: MemoryPageSummaryDTO[];
  derivedAssets?: AssetDTO[];
  parentAsset?: AssetDTO | null;
  previewAsset?: AssetDTO | null;
}

export interface MemoryPageSummaryDTO {
  id: string;
  workspaceId: string;
  path: string;
  title: string | null;
  pageType: string;
  sourceRef: string | null;
  sourceKind: string | null;
  sourceAssetId: string | null;
  version: number;
  stale: boolean;
  contentHash: string;
  updatedAt: string;
  archivedAt?: string | null;
  visibility?: string;
  inboundLinkCount?: number;
  outboundLinkCount?: number;
}

export interface MemoryPageDetailDTO extends MemoryPageSummaryDTO {
  /** Markdown body. Null when the GET was filtered with `?format=html`. */
  content: string | null;
  /**
   * HTML body. M-D (doc 25 §4): an INDEPENDENT source from `content`,
   * not a derivation. Null when the page never received an HTML write
   * and the backfill cron has not derived one yet, OR when the GET was
   * filtered with `?format=markdown`. The Library rich-text editor
   * writes to this via `PATCH /memory/pages/:id/html` (independent of
   * markdown writes).
   */
  contentHtml: string | null;
  /**
   * Render-pipeline version stamp:
   *   0    = user / agent-authored HTML (independent — backfill cron skips);
   *   >=1  = backfill-derived at markdown-render pipeline version N;
   *   null = no HTML version exists.
   */
  contentHtmlVersion: number | null;
  provenance: unknown[];
}

export interface MemoryLinkRowDTO {
  id: string;
  sourcePageId: string;
  targetPageId: string | null;
  sourceUri?: string | null;
  targetUri: string;
  relation: string;
  weight: number;
  broken: boolean;
  extractedFromVersion: number | null;
  updatedAt: string;
}

export interface KnowledgeLinkRowDTO {
  id: string;
  sourceType: string;
  sourceId: string;
  targetType: string;
  targetId: string;
  relation: string;
  weight: number;
  metadataJson?: Record<string, unknown> | null;
  updatedAt: string;
}

export interface MemoryPageLinksDTO {
  outbound: MemoryLinkRowDTO[];
  backlinks: MemoryLinkRowDTO[];
  knowledge: KnowledgeLinkRowDTO[];
}

export interface MemoryPageVersionRowDTO {
  id: string;
  pageId: string;
  version: number;
  parentVersion: number | null;
  contentHash: string;
  changeSummary: string | null;
  payloadJson: Record<string, unknown>;
  createdAt: string;
}

export interface MemorySearchResultDTO {
  pageId: string;
  workspaceId: string;
  path: string;
  title: string | null;
  pageType: string;
  visibility: string;
  stale: boolean;
  inboundLinkCount: number;
  updatedAt: string;
  snippet: string;
  score: number;
  components?: Record<string, number>;
}

export interface MemorySearchResponseDTO {
  memory: MemorySearchResultDTO[];
  files: unknown[];
  cursor: string | null;
  took_ms: number;
}

export interface MemoryGraphNodeDTO {
  pageId: string;
  path: string;
  title: string | null;
  pageType: string;
  visibility: string;
  stale: boolean;
  inboundCount: number;
}

export interface MemoryGraphEdgeDTO {
  sourcePageId: string;
  targetPageId: string;
  relation: string;
  broken: boolean;
}

export interface MemoryGraphResponseDTO {
  nodes: MemoryGraphNodeDTO[];
  edges: MemoryGraphEdgeDTO[];
  truncated: { totalNodes: number; shownNodes: number; totalEdges: number };
}

export interface MemoryHealthItemDTO {
  pageId: string;
  path: string;
  title: string | null;
  pageType: string;
  reason: string;
  metadataJson?: Record<string, unknown> | null;
}

export interface MemoryHealthResponseDTO {
  items: MemoryHealthItemDTO[];
  total: number;
}

export interface MemoryProposalDTO {
  id: string;
  workspaceId: string;
  pagePath: string;
  status: 'pending' | 'approved' | 'rejected' | 'expired';
  baseVersion: number;
  operation: 'create' | 'append' | 'replace_section' | 'archive';
  contentDiff: string;
  rationale: string | null;
  confidence: number;
  /**
   * Wire format is a JSON-encoded string from the IM router (Line A
   * proposal service stores it as TEXT and serializes verbatim). Callers
   * must parse before reading individual refs.
   */
  sourceRefs: string;
  sessionId: string | null;
  /**
   * Line A returns this as `proposingAgentId`. The platform-wide alias
   * `proposingAgentImUserId` is kept as a fallback for older payloads.
   */
  proposingAgentId: string;
  proposingAgentImUserId?: string;
  decidedByImUserId: string | null;
  decidedAt: string | null;
  rejectionReason: string | null;
  createdAt: string;
  expiresAt: string;
}

export interface RecallTraceEventDTO {
  id: string;
  eventType: string;
  actorImUserId: string;
  actorKind: string;
  pageId: string | null;
  query: string | null;
  metricsJson: Record<string, unknown> | null;
  metadataJson: Record<string, unknown> | null;
  createdAt: string;
}

export interface RecallTraceResponseDTO {
  events: RecallTraceEventDTO[];
  cursor: string | null;
}

/**
 * TaskDTO — superset of TaskInfo plus v1.8.2 enrichment fields
 * (`ownerId / ownerType / ownerName / assigneeType / assigneeName`).
 * All date fields arrive as ISO strings over the wire.
 */
export interface TaskDTO {
  id: string;
  title: string;
  description: string | null;
  capability: string | null;
  input?: Record<string, unknown>;
  contextUri?: string | null;
  workspaceId: string | null;
  conversationId: string | null;
  creatorId: string;
  assigneeId: string | null;
  status: string;
  progress: number | null;
  statusMessage: string | null;
  scheduleType?: string | null;
  scheduleCron?: string | null;
  intervalMs?: number | null;
  nextRunAt?: string | null;
  lastRunAt?: string | null;
  runCount?: number;
  maxRuns?: number | null;
  result?: unknown | null;
  resultUri?: string | null;
  error?: string | null;
  budget: number | null;
  cost: number;
  timeoutMs?: number;
  deadline: string | null;
  completedAt: string | null;
  maxRetries?: number;
  retryDelayMs?: number;
  retryCount?: number;
  createdAt: string;
  updatedAt: string;
  metadata: Record<string, unknown>;
  ownerId?: string;
  ownerType?: string | null;
  ownerName?: string | null;
  assigneeType?: string | null;
  assigneeName?: string | null;
  bridge?: WorkspaceSignalDTO | null;
  boardLane?: string | null;
  position?: number | null;
  terminalReason?: string | null;
}

export type WorkspaceTaskKind = 'work_item' | 'goal' | 'agent_run';

export interface WorkspaceTaskMetadata extends Record<string, unknown> {
  kind?: WorkspaceTaskKind | string;
  intent?: string;
  triggerKind?: string;
  triggerMessageId?: string;
  parentTaskId?: string;
  goalTaskId?: string;
  board?: Record<string, unknown>;
  bridge?: Record<string, unknown>;
}

function taskMetadata(task: TaskDTO): WorkspaceTaskMetadata {
  return task.metadata as WorkspaceTaskMetadata;
}

/**
 * Product semantics intentionally diverge from storage semantics:
 * `/api/im/tasks` is reused for both board items and execution runs, but a run
 * is not a Kanban card. This mirrors Multica's Issue vs AgentTask split.
 */
export function isAgentRunTask(task: TaskDTO): boolean {
  const meta = taskMetadata(task);
  if (meta.kind === 'agent_run') return true;
  // Legacy mention/session execution rows predate metadata.kind. Keep them
  // out of the board while old work-item rows without kind remain visible.
  if (meta.triggerKind === 'mention' || typeof meta.triggerMessageId === 'string') return true;
  if (task.capability === 'chat' && task.conversationId) return true;
  return false;
}

export function isBoardProjectionTask(task: TaskDTO): boolean {
  const meta = taskMetadata(task);
  if (meta.kind === 'work_item' || meta.kind === 'goal' || meta.intent === 'standing_objective') return true;
  if (meta.kind === 'agent_run') return false;
  return !isAgentRunTask(task);
}

export interface TaskLogDTO {
  id: string;
  taskId: string;
  actorId: string | null;
  action: string;
  message: string | null;
  metadata: Record<string, unknown>;
  createdAt: string;
}

export interface TaskDetailDTO {
  task: TaskDTO;
  logs: TaskLogDTO[];
  subtasks?: TaskDTO[];
  summary?: {
    total: number;
    completed: number;
    failed: number;
    pending: number;
    running: number;
    allDone: boolean;
  };
}

/**
 * Five-column kanban — see docs/54release/09-workspace-uiux.md §2.
 * Mirrors `multica` minus `blocked / cancelled`, intentionally narrow scope.
 */
export type KanbanColumnKey = 'backlog' | 'todo' | 'in_progress' | 'review' | 'completed' | 'failed' | 'cancelled';

export interface KanbanColumn {
  key: KanbanColumnKey;
  label: string;
  hint: string;
}

export const KANBAN_COLUMNS: KanbanColumn[] = [
  { key: 'backlog', label: '构思', hint: 'pending · unassigned' },
  { key: 'todo', label: '待执行', hint: 'pending · assigned' },
  { key: 'in_progress', label: '进行中', hint: 'assigned · running' },
  { key: 'review', label: '待确认', hint: 'awaiting approval' },
  { key: 'completed', label: '已完成', hint: 'approved · completed' },
  { key: 'failed', label: '已失败', hint: 'execution failed' },
  { key: 'cancelled', label: '回收站', hint: 'cancelled · archive' },
];

/**
 * Default columns shown on the board (回收站 / Cancelled is hidden behind a
 * toggle — callers that render the full board should pass through
 * `showRecycleBin` from the toggle state and filter the list before render).
 */
export const KANBAN_VISIBLE_COLUMNS: KanbanColumnKey[] = [
  'backlog',
  'todo',
  'in_progress',
  'review',
  'completed',
  'failed',
];

/**
 * Bucket a task into a kanban column. Returns `null` only for unknown
 * statuses — `pending+assigneeId` now lands in Todo (covers Pause-back state),
 * `failed` and `cancelled` each have their own column.
 */
export function bucketTask(task: TaskDTO): KanbanColumnKey | null {
  switch (task.status) {
    case 'pending':
      return task.assigneeId ? 'todo' : 'backlog';
    case 'assigned':
      return 'todo';
    case 'running':
    case 'in_progress':
      return 'in_progress';
    case 'review':
      return 'review';
    case 'completed':
      return 'completed';
    case 'failed':
      return 'failed';
    case 'cancelled':
      return 'cancelled';
    default:
      return null;
  }
}

export type GoalStatus = 'active' | 'paused' | 'completed';
export type GoalPriority = 'low' | 'medium' | 'high';

export interface GoalTaskMetadata {
  kind?: WorkspaceTaskKind | string;
  goal?: {
    status?: GoalStatus | string;
    priority?: GoalPriority | string;
    linkedTaskIds?: string[];
    linkedConversationIds?: string[];
    lastActivityAt?: string | null;
    [key: string]: unknown;
  };
  bridge?: Record<string, unknown>;
  [key: string]: unknown;
}

/**
 * 54release reuse-first goal shape.
 *
 * Goals are standing-objective TaskDTO projections over `/api/im/tasks`, not a
 * separate wire entity. Keep this alias narrow so UI code can name the product
 * concept without inventing `/goals` contracts.
 */
export type GoalTaskDTO = TaskDTO & {
  metadata: GoalTaskMetadata;
};

export function isGoalTask(task: TaskDTO): task is GoalTaskDTO {
  const meta = taskMetadata(task);
  return meta.kind === 'goal' || meta.intent === 'standing_objective';
}

export function goalTaskStatus(task: TaskDTO): GoalStatus {
  const raw = typeof task.metadata?.goal === 'object' && task.metadata.goal ? (task.metadata.goal as any).status : null;
  if (raw === 'paused' || raw === 'completed') return raw;
  if (task.status === 'completed') return 'completed';
  return 'active';
}

export function goalTaskPriority(task: TaskDTO): GoalPriority {
  const raw =
    typeof task.metadata?.goal === 'object' && task.metadata.goal ? (task.metadata.goal as any).priority : null;
  return raw === 'low' || raw === 'high' ? raw : 'medium';
}
