/**
 * @prismer/wire codegen — Generate language bindings from wire schema
 *
 * Outputs:
 *   dist/wire.schema.json       — JSON Schema 2020-12
 *   dist/PrismerWireDTO.swift   — Swift Codable flat DTO (via quicktype)
 *   dist/prismer_wire.py        — Python TypedDict / dataclasses (via quicktype)
 *
 * Per D15 (docs/version190/13-experiments.md §21): quicktype emits a flat struct
 * with all variant fields optional. This is expected and correct — the enum wrapper
 * is the lumin-swift team's responsibility, and the Python DTO is consumed by
 * prismer-adapter-hermes as-is.
 *
 * Run: npm run codegen
 */

import * as fs from 'fs';
import * as path from 'path';
import { zodToJsonSchema } from 'zod-to-json-schema';
import {
  InputData,
  JSONSchemaInput,
  jsonInputForTargetLanguage,
  quicktype,
} from 'quicktype-core';

// Import schemas from compiled dist (run `npm run build` before codegen)
import { ParaEventSchema, AgentDescriptorSchema, EncryptedEnvelopeSchema } from '../dist/index.js';

const DIST_DIR = path.resolve(process.cwd(), 'dist');

async function main(): Promise<void> {
  // Ensure dist directory exists
  if (!fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true });
  }

  console.log('[codegen] Generating wire.schema.json...');

  // Generate combined JSON Schema
  const combinedSchema = {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'PrismerWire',
    description: 'Prismer Agent Runtime ABI (PARA) v0.1 wire protocol schemas',
    version: '0.1.0',
    definitions: {
      ParaEvent: zodToJsonSchema(ParaEventSchema, { name: 'ParaEvent', $refStrategy: 'none' }),
      AgentDescriptor: zodToJsonSchema(AgentDescriptorSchema, { name: 'AgentDescriptor', $refStrategy: 'none' }),
      EncryptedEnvelope: zodToJsonSchema(EncryptedEnvelopeSchema, {
        name: 'EncryptedEnvelope',
        $refStrategy: 'none',
      }),
    },
    // Primary entry for quicktype — point to ParaEvent
    ...zodToJsonSchema(ParaEventSchema, { name: 'ParaEvent', $refStrategy: 'none' }),
  };

  const schemaPath = path.join(DIST_DIR, 'wire.schema.json');
  fs.writeFileSync(schemaPath, JSON.stringify(combinedSchema, null, 2), 'utf-8');
  const schemaLines = JSON.stringify(combinedSchema, null, 2).split('\n').length;
  console.log(`[codegen] wire.schema.json written (${schemaLines} lines)`);

  // Generate Swift DTO
  console.log('[codegen] Generating PrismerWireDTO.swift via quicktype...');
  const swiftPath = path.join(DIST_DIR, 'PrismerWireDTO.swift');
  try {
    const swiftContent = await generateQuicktype(combinedSchema, 'swift', 'PrismerWireDTO');
    fs.writeFileSync(swiftPath, swiftContent, 'utf-8');
    const swiftLines = swiftContent.split('\n').length;
    console.log(`[codegen] PrismerWireDTO.swift written (${swiftLines} lines)`);
  } catch (err) {
    console.error('[codegen] Swift generation failed:', err);
    // Write a stub file so the build doesn't completely fail
    const stub = `// PrismerWireDTO.swift — generated by @prismer/wire codegen\n// Generation error: ${String(err)}\n// Regenerate with: npm run codegen\n`;
    fs.writeFileSync(swiftPath, stub, 'utf-8');
    console.warn('[codegen] Wrote Swift stub file');
  }

  // Generate Python TypedDict
  console.log('[codegen] Generating prismer_wire.py via quicktype...');
  const pyPath = path.join(DIST_DIR, 'prismer_wire.py');
  try {
    const pyContent = await generateQuicktype(combinedSchema, 'python', 'prismer_wire');
    fs.writeFileSync(pyPath, pyContent, 'utf-8');
    const pyLines = pyContent.split('\n').length;
    console.log(`[codegen] prismer_wire.py written (${pyLines} lines)`);
  } catch (err) {
    console.error('[codegen] Python generation failed:', err);
    // Write a stub file
    const stub = `# prismer_wire.py — generated by @prismer/wire codegen\n# Generation error: ${String(err)}\n# Regenerate with: npm run codegen\n`;
    fs.writeFileSync(pyPath, stub, 'utf-8');
    console.warn('[codegen] Wrote Python stub file');
  }

  // ─── Sync to Hermes vendored copy ────────────────────────────────────────
  // The Hermes Python adapter vendors prismer_wire.py (zero runtime deps).
  // Auto-sync so developers don't ship stale copies after bumping the schema.
  // Also apply the Python 3.10+ dataclass field-order compat patch here so the
  // vendored copy is ready to import without further manual editing.
  try {
    const hermesWirePath = path.join(
      __dirname, '..', '..', 'adapters', 'hermes', 'src', 'prismer_adapter_hermes', 'wire.py'
    );
    if (fs.existsSync(path.dirname(hermesWirePath))) {
      const pyContent = fs.readFileSync(pyPath, 'utf-8');
      // Compute a simple hash of the generated content (SHA-256 of body) so CI
      // can detect drift if the vendored copy is hand-edited later.
      const hash = require('node:crypto').createHash('sha256').update(pyContent).digest('hex').slice(0, 16);
      const banner = [
        '# AUTO-GENERATED FROM @prismer/wire — DO NOT EDIT.',
        '# Regenerate by running `npm run codegen` in sdk/prismer-cloud/wire/',
        '# which will automatically sync this file.',
        '#',
        '# Python 3.10+ compat: quicktype emits bare Any fields without defaults',
        '# between Optional fields, which Python 3.10+ rejects. The field(default=None)',
        '# patch below resolves this at sync time.',
        `# WIRE_SCHEMA_SHA256 = "${hash}"`,
        '',
        'from dataclasses import dataclass, field',
        '',
      ].join('\n');
      // Patch A: transform `x: Any` (non-Optional bare Any) into
      // `x: Any = field(default=None)` so Python 3.10+ doesn't reject
      // no-default fields between fields-with-defaults.
      // Patch B: rewrite `return ClassName(arg1, arg2, ...)` from_dict
      // returns into kwargs form `ClassName(arg1=arg1, arg2=arg2, ...)`
      // so future quicktype field-order changes cannot silently misassign.
      const withDefaults = pyContent
        .replace(/^from dataclasses import dataclass\s*$/m, '')
        .replace(/^(\s{4}[a-z_]+):\s*Any\s*$/gm, '$1: Any = field(default=None)')
        .replace(/^(\s{4}[a-z_]+):\s*Optional\[[^\]]+\]\s*$/gm, '$1: Optional = field(default=None)');
      // Only rewrite `return ClassName(...)` where ClassName starts with an
      // UPPERCASE letter (dataclass constructor convention). This skips
      // helper-function returns like `return f(x)` / `return from_str(x)`
      // which take positional args that are NOT named 'x' / 'x' etc.
      const patched = withDefaults.replace(
        /return ([A-Z]\w*)\(([^)]+)\)/g,
        (match, className, argList) => {
          // Also require every "arg" to be a bare identifier (no `=`, no calls).
          const args = argList.split(',').map((s: string) => s.trim());
          const allBare = args.every((a: string) => /^[A-Za-z_][A-Za-z0-9_]*$/.test(a));
          if (!allBare) return match;
          const kwargs = args.map((a: string) => `${a}=${a}`).join(', ');
          return `return ${className}(${kwargs})`;
        },
      );
      fs.writeFileSync(hermesWirePath, banner + patched, 'utf-8');
      console.log(`[codegen] Synced wire.py → ${hermesWirePath} (sha256=${hash})`);
    }
  } catch (err) {
    console.warn(`[codegen] Hermes sync skipped: ${(err as Error).message}`);
  }

  console.log('[codegen] Done.');
  console.log(`[codegen] Output files:`);
  console.log(`  ${schemaPath}`);
  console.log(`  ${swiftPath}`);
  console.log(`  ${pyPath}`);
}

async function generateQuicktype(
  schema: object,
  lang: string,
  typeName: string
): Promise<string> {
  const schemaString = JSON.stringify(schema);

  const schemaInput = new JSONSchemaInput(undefined);
  await schemaInput.addSource({
    name: typeName,
    schema: schemaString,
  });

  const inputData = new InputData();
  inputData.addInput(schemaInput);

  const result = await quicktype({
    inputData,
    lang,
    rendererOptions: lang === 'swift'
      ? {
          'struct-or-class': 'struct',
          'access-level': 'public',
          'swift-5-support': 'true',
        }
      : lang === 'python'
      ? {
          'python-version': '3.7',
        }
      : {},
    inferMaps: false,
    inferEnums: true,
    inferDateTimes: false,
    inferIntegerStrings: false,
    combineClasses: false,
    allPropertiesOptional: false,
  });

  return result.lines.join('\n');
}

main().catch((err) => {
  console.error('[codegen] Fatal error:', err);
  process.exit(1);
});
