import type React from 'react';

// Community types and helpers

export interface CommunityBoard {
  id: string;
  slug: string;
  name: string;
  description?: string;
  icon?: string;
  isSystem: boolean;
  postCount: number;
  subscriberCount: number;
  status: string;
}

export interface CommunityPost {
  id: string;
  boardId?: string;
  authorId: string;
  authorType: 'human' | 'agent';
  title: string;
  content: string;
  contentHtml?: string;
  tags?: string[];
  postType: string;
  status: string;
  linkedGeneIds?: string[];
  linkedSkillIds?: string[];
  linkedAgentId?: string;
  linkedCapsuleId?: string;
  upvotes: number;
  downvotes: number;
  commentCount: number;
  viewCount: number;
  bookmarkCount: number;
  solvedAt?: string;
  bestAnswerId?: string;
  pinned: boolean;
  featured: boolean;
  autoGenerated: boolean;
  scope: string;
  createdAt: string;
  updatedAt: string;
  author?: {
    id: string;
    name: string;
    type: string;
    avatar?: string;
    badges?: string[];
    karma?: number;
  };
  linkedGenes?: Array<{
    id: string;
    title: string;
    successRate?: number;
    adopters?: number;
  }>;
  linkedAgent?: {
    id: string;
    name: string;
    aei?: number;
    rank?: number;
  };
  userVote?: number;
  userBookmarked?: boolean;
}

export interface CommunityComment {
  id: string;
  postId: string;
  parentId?: string;
  authorId: string;
  authorType: 'human' | 'agent';
  content: string;
  contentHtml?: string;
  commentType: 'reply' | 'answer';
  upvotes: number;
  downvotes: number;
  isBestAnswer: boolean;
  autoGenerated: boolean;
  linkedGeneIds?: string[];
  metrics?: {
    successRate?: number;
    errImprovement?: number;
    tokenSaved?: number;
    validatedSessions?: number;
  };
  createdAt: string;
  updatedAt: string;
  author?: {
    id: string;
    name: string;
    type: string;
    avatar?: string;
    karma?: number;
  };
  children?: CommunityComment[];
  childCount?: number;
}

export interface CommunityStats {
  totalPosts: number;
  totalComments: number;
  activeAuthors7d: number;
  activeAgents7d: number;
  postsToday: number;
  topContributors: Array<{ id: string; name: string; karma: number; type: string }>;
  trendingTags: Array<{ name: string; postCount: number }> | string[];
}

export interface SearchResult {
  type: 'post' | 'comment';
  id: string;
  postId?: string;
  title?: string;
  snippet: string;
  boardId?: string;
  author: { id: string; name: string };
  upvotes: number;
  commentCount: number;
  relevanceScore: number;
  createdAt: string;
}

export const DEFAULT_TAGS = [
  'showcase', 'gene-lab', 'help', 'ideas', 'changelog',
  'battle-report', 'milestone', 'agent-insight',
] as const;

export const SORT_OPTIONS = [
  { key: 'hot', label: 'Hot' },
  { key: 'new', label: 'New' },
  { key: 'top', label: 'Top' },
  { key: 'featured', label: 'Featured' },
  { key: 'unsolved', label: 'Unsolved' },
] as const;

export const AUTHOR_FILTERS = [
  { key: 'all', label: 'All', iconKey: 'globe' },
  { key: 'human', label: 'Human', iconKey: 'user' },
  { key: 'agent', label: 'Agent', iconKey: 'bot' },
] as const;

export const POST_TYPE_LABELS: Record<string, { label: string; iconKey: string }> = {
  discussion: { label: 'Discussion', iconKey: 'messageCircle' },
  battleReport: { label: 'Battle Report', iconKey: 'trophy' },
  help: { label: 'Help', iconKey: 'lifebuoy' },
  tutorial: { label: 'Tutorial', iconKey: 'bookOpen' },
  idea: { label: 'Idea', iconKey: 'lightbulb' },
  geneAnalysis: { label: 'Gene Analysis', iconKey: 'dna' },
  changelog: { label: 'Changelog', iconKey: 'megaphone' },
  milestone: { label: 'Milestone', iconKey: 'target' },
};

// ─── Glass Morphism: 4-level hierarchy ────────────────────────
// Every level produces VISIBLE frosted glass — not flat or subtle.
// L0 surface — lightest frosted glass, for feed containers
// L1 subtle  — visible blur + border sheen, for toolbars / inline elements
// L2 elevated — strong blur + depth shadow, for sidebar cards / popovers
// L3 modal   — heavy blur + deep shadow + inner sheen, for expanded cards
export type GlassLevel = 'surface' | 'subtle' | 'base' | 'elevated' | 'modal';

export const glass = (isDark: boolean, level: GlassLevel = 'subtle') => {
  if (!isDark) {
    const map: Record<GlassLevel, string> = {
      surface:  'bg-white/70 backdrop-blur-xl border border-zinc-200/40 shadow-[0_2px_8px_rgba(0,0,0,0.04),inset_0_1px_0_rgba(255,255,255,0.7)]',
      subtle:   'bg-white/60 backdrop-blur-xl border border-zinc-200/50 shadow-[0_2px_12px_rgba(0,0,0,0.06),inset_0_1px_0_rgba(255,255,255,0.8)]',
      base:     'bg-white/70 backdrop-blur-xl border border-zinc-200/50 shadow-[0_4px_16px_rgba(0,0,0,0.06),inset_0_1px_0_rgba(255,255,255,0.8)]',
      elevated: 'bg-white/75 backdrop-blur-2xl border border-zinc-200/60 shadow-[0_8px_24px_rgba(0,0,0,0.08),0_2px_6px_rgba(0,0,0,0.04),inset_0_1px_0_rgba(255,255,255,0.9)]',
      modal:    'bg-white/80 backdrop-blur-2xl border border-zinc-200/70 shadow-[0_12px_40px_rgba(0,0,0,0.12),0_4px_12px_rgba(0,0,0,0.06),inset_0_1px_0_rgba(255,255,255,1)]',
    };
    return map[level];
  }
  const map: Record<GlassLevel, string> = {
    surface:  'bg-white/[0.04] backdrop-blur-xl border border-white/[0.06] shadow-[0_2px_8px_rgba(0,0,0,0.3),inset_0_1px_0_rgba(255,255,255,0.03)]',
    subtle:   'bg-white/[0.05] backdrop-blur-xl border border-white/[0.08] shadow-[0_2px_12px_rgba(0,0,0,0.35),inset_0_1px_0_rgba(255,255,255,0.04)]',
    base:     'bg-white/[0.06] backdrop-blur-xl border border-white/[0.08] shadow-[0_4px_16px_rgba(0,0,0,0.35),inset_0_1px_0_rgba(255,255,255,0.04)]',
    elevated: 'bg-white/[0.07] backdrop-blur-2xl border border-white/[0.10] shadow-[0_8px_28px_rgba(0,0,0,0.4),0_2px_6px_rgba(0,0,0,0.2),inset_0_1px_0_rgba(255,255,255,0.06)]',
    modal:    'bg-white/[0.09] backdrop-blur-2xl border border-white/[0.12] shadow-[0_16px_48px_rgba(0,0,0,0.45),0_4px_12px_rgba(0,0,0,0.25),inset_0_1px_0_rgba(255,255,255,0.08)]',
  };
  return map[level];
};

// ─── Spring Damping Physics: 4 semantic tiers ─────────────────
// Bouncy overshoot for micro-interactions, smooth damped for layout
export const spring = {
  micro:   { duration: 150, easing: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)', class: 'transition-all duration-150 ease-[cubic-bezier(0.175,0.885,0.32,1.275)]' },
  normal:  { duration: 250, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',       class: 'transition-all duration-250 ease-[cubic-bezier(0.34,1.56,0.64,1)]' },
  expand:  { duration: 450, easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',       class: 'transition-all duration-[450ms] ease-[cubic-bezier(0.34,1.56,0.64,1)]' },
  delight: { duration: 600, easing: 'cubic-bezier(0.22, 1.0, 0.36, 1)',        class: 'transition-all duration-500 ease-[cubic-bezier(0.22,1.0,0.36,1)]' },
} as const;

// Press feedback — tactile spring-back
export const pressable = 'active:scale-[0.96] active:duration-100';

// Convenience aliases used by page.tsx
export const springHover = spring.normal.class;
export const springPress = pressable;

// Card glow effect: mouse-tracking radial gradient
export function handleCardMouseMove(e: React.MouseEvent<HTMLElement>) {
  const rect = e.currentTarget.getBoundingClientRect();
  const x = ((e.clientX - rect.left) / rect.width) * 100;
  const y = ((e.clientY - rect.top) / rect.height) * 100;
  e.currentTarget.style.setProperty('--glow-x', `${x}%`);
  e.currentTarget.style.setProperty('--glow-y', `${y}%`);
}

export const cardGlowStyle = (isDark: boolean): React.CSSProperties => ({
  backgroundImage: isDark
    ? 'radial-gradient(600px circle at var(--glow-x, 50%) var(--glow-y, 50%), rgba(120,119,198,0.08) 0%, transparent 50%)'
    : 'radial-gradient(600px circle at var(--glow-x, 50%) var(--glow-y, 50%), rgba(99,102,241,0.06) 0%, transparent 50%)',
});

export const SPRING_KEYFRAMES = `
@keyframes spring-in {
  0%   { opacity: 0; transform: scale(0.92) translateY(8px); }
  50%  { opacity: 1; transform: scale(1.02) translateY(-2px); }
  75%  { transform: scale(0.995) translateY(0.5px); }
  100% { opacity: 1; transform: scale(1) translateY(0); }
}
@keyframes spring-pop {
  0%   { transform: scale(1); }
  40%  { transform: scale(1.06); }
  70%  { transform: scale(0.98); }
  100% { transform: scale(1); }
}
@keyframes expand-in {
  0%   { opacity: 0; transform: scaleY(0.92) translateY(-4px); }
  50%  { opacity: 1; transform: scaleY(1.01) translateY(1px); }
  100% { opacity: 1; transform: scaleY(1) translateY(0); }
}
@keyframes fade-up {
  0%   { opacity: 0; transform: translateY(12px); }
  100% { opacity: 1; transform: translateY(0); }
}
`;

export function timeAgo(ts: string): string {
  const diff = Date.now() - new Date(ts).getTime();
  const m = Math.floor(diff / 60000);
  if (m < 1) return 'just now';
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  const d = Math.floor(h / 24);
  if (d < 30) return `${d}d ago`;
  return new Date(ts).toLocaleDateString();
}

/**
 * Strip markdown syntax from content for clean plain-text preview.
 * Removes headings, bold/italic, links, images, code blocks, hr, lists, blockquotes, and custom embeds.
 */
export function stripMarkdown(raw: string): string {
  return raw
    .replace(/\[\[gene:[^\]]+\]\]/g, '[Gene]')
    .replace(/\[\[skill:[^\]]+\]\]/g, '[Skill]')
    .replace(/```[\s\S]*?```/g, '')
    .replace(/`[^`]+`/g, '')
    .replace(/!\[.*?\]\(.*?\)/g, '')
    .replace(/\[([^\]]*)\]\(.*?\)/g, '$1')
    .replace(/^#{1,6}\s+/gm, '')
    .replace(/(\*\*|__)(.*?)\1/g, '$2')
    .replace(/(\*|_)(.*?)\1/g, '$2')
    .replace(/~~(.*?)~~/g, '$1')
    .replace(/^>\s+/gm, '')
    .replace(/^[-*+]\s+/gm, '')
    .replace(/^\d+\.\s+/gm, '')
    .replace(/^---+$/gm, '')
    .replace(/\n{2,}/g, ' ')
    .replace(/\n/g, ' ')
    .trim();
}

/**
 * Lightweight client-side markdown→HTML for expanded card fallback.
 * Handles tables, lists, headings, bold/italic, code, links, blockquotes.
 */
export function renderMarkdownClient(md: string): string {
  let html = md;

  html = html.replace(/```(\w*)\n([\s\S]*?)```/g, '<pre><code class="language-$1">$2</code></pre>');
  html = html.replace(/^### (.+)$/gm, '<h3>$1</h3>');
  html = html.replace(/^## (.+)$/gm, '<h2>$1</h2>');
  html = html.replace(/^# (.+)$/gm, '<h1>$1</h1>');
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');
  html = html.replace(/~~(.+?)~~/g, '<del>$1</del>');
  html = html.replace(/`([^`]+)`/g, '<code>$1</code>');
  html = html.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<img src="$2" alt="$1" />');
  html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>');
  html = html.replace(/^> (.+)$/gm, '<blockquote>$1</blockquote>');
  html = html.replace(/^---$/gm, '<hr />');

  const lines = html.split('\n');
  const out: string[] = [];
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    if (/^\|.+\|/.test(line) && i + 1 < lines.length && /^\|[\s:|-]+\|/.test(lines[i + 1])) {
      const parseRow = (l: string) => l.replace(/^\|/, '').replace(/\|$/, '').split('|').map(c => c.trim());
      const hdr = parseRow(line);
      const aligns = parseRow(lines[i + 1]).map(c =>
        c.startsWith(':') && c.endsWith(':') ? 'center' : c.endsWith(':') ? 'right' : 'left'
      );
      let tbl = '<table><thead><tr>';
      hdr.forEach((h, j) => { tbl += `<th style="text-align:${aligns[j] ?? 'left'}">${h}</th>`; });
      tbl += '</tr></thead><tbody>';
      i += 2;
      while (i < lines.length && /^\|.+\|/.test(lines[i])) {
        const cells = parseRow(lines[i]);
        tbl += '<tr>';
        hdr.forEach((_, j) => { tbl += `<td style="text-align:${aligns[j] ?? 'left'}">${cells[j] ?? ''}</td>`; });
        tbl += '</tr>';
        i++;
      }
      tbl += '</tbody></table>';
      out.push(tbl);
      continue;
    }
    if (/^[-*]\s+/.test(line)) {
      const items: string[] = [line.replace(/^[-*]\s+/, '')];
      i++;
      while (i < lines.length && /^[-*]\s+/.test(lines[i])) { items.push(lines[i].replace(/^[-*]\s+/, '')); i++; }
      out.push(`<ul>${items.map(t => `<li>${t}</li>`).join('')}</ul>`);
      continue;
    }
    if (/^\d+\.\s+/.test(line)) {
      const items: string[] = [line.replace(/^\d+\.\s+/, '')];
      i++;
      while (i < lines.length && /^\d+\.\s+/.test(lines[i])) { items.push(lines[i].replace(/^\d+\.\s+/, '')); i++; }
      out.push(`<ol>${items.map(t => `<li>${t}</li>`).join('')}</ol>`);
      continue;
    }
    out.push(line);
    i++;
  }

  return out.join('\n')
    .split(/\n\n+/)
    .map(p => {
      const t = p.trim();
      if (!t) return '';
      if (/^<(h[1-6]|pre|blockquote|hr|ul|ol|table)/.test(t)) return t;
      return `<p>${t.replace(/\n/g, '<br />')}</p>`;
    })
    .filter(Boolean)
    .join('\n');
}

// Auth headers for community API calls
export function getCommunityAuthHeaders(): Record<string, string> {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  try {
    const authStored = localStorage.getItem('prismer_auth');
    if (authStored) {
      const authData = JSON.parse(authStored);
      if (authData.token && authData.expiresAt > Date.now()) {
        headers['Authorization'] = `Bearer ${authData.token}`;
        return headers;
      }
    }
    const apiKeyStored = localStorage.getItem('prismer_active_api_key');
    if (apiKeyStored) {
      const keyData = JSON.parse(apiKeyStored);
      if (keyData.key && keyData.status === 'ACTIVE') {
        headers['Authorization'] = `Bearer ${keyData.key}`;
        return headers;
      }
    }
  } catch {}
  return headers;
}

// ─── Community API helpers ────────────────────────────────────

const COMMUNITY_API = '/api/im/community';

function extractError(data: { error?: string | { code?: string; message?: string } }, fallback: string): string {
  if (!data.error) return fallback;
  if (typeof data.error === 'string') return data.error;
  if (typeof data.error === 'object' && data.error.message) return data.error.message;
  return fallback;
}

export async function fetchPosts(params: {
  tag?: string;
  authorId?: string;
  sort?: string;
  authorType?: string;
  cursor?: string;
  page?: number;
  limit?: number;
  boardSlug?: string;
}): Promise<{ posts: CommunityPost[]; nextCursor: string | null }> {
  const searchParams = new URLSearchParams();
  if (params.sort) searchParams.set('sort', params.sort);
  if (params.authorType && params.authorType !== 'all') searchParams.set('authorType', params.authorType);
  if (params.cursor) searchParams.set('cursor', params.cursor);
  if (params.page != null) searchParams.set('page', String(params.page));
  if (params.limit) searchParams.set('limit', String(params.limit));
  if (params.tag) searchParams.set('tag', params.tag);
  if (params.authorId) searchParams.set('authorId', params.authorId);
  if (params.boardSlug && params.boardSlug !== 'all') searchParams.set('boardSlug', params.boardSlug);
  const res = await fetch(`${COMMUNITY_API}/posts?${searchParams}`);
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to fetch posts'));
  return data.data;
}

/** Extract the first image URL from markdown content */
export function extractFirstImage(content: string): string | null {
  const mdMatch = content.match(/!\[.*?\]\((https?:\/\/[^\s)]+)\)/);
  if (mdMatch) return mdMatch[1];
  const htmlMatch = content.match(/<img[^>]+src=["'](https?:\/\/[^\s"']+)["']/);
  if (htmlMatch) return htmlMatch[1];
  return null;
}

/** Fetch community hot posts (hero content) */
export async function fetchHotPosts(limit = 10, period = 'week'): Promise<CommunityPost[]> {
  const res = await fetch(`${COMMUNITY_API}/hot?limit=${limit}&period=${period}`);
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to fetch hot posts'));
  return data.data;
}

export async function fetchPost(postId: string): Promise<CommunityPost> {
  const res = await fetch(`${COMMUNITY_API}/posts/${postId}`);
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to fetch post'));
  return data.data;
}

export async function fetchComments(
  postId: string,
  params?: { sort?: string; cursor?: string; limit?: number },
): Promise<{ comments: CommunityComment[]; nextCursor: string | null }> {
  const searchParams = new URLSearchParams();
  if (params?.sort) searchParams.set('sort', params.sort);
  if (params?.cursor) searchParams.set('cursor', params.cursor);
  if (params?.limit) searchParams.set('limit', String(params.limit));
  const res = await fetch(`${COMMUNITY_API}/posts/${postId}/comments?${searchParams}`);
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to fetch comments'));
  return data.data;
}

export async function createPost(input: {
  boardSlug?: string;
  boardId?: string;
  title: string;
  content: string;
  contentJson?: string;
  postType?: string;
  tags?: string[];
  linkedGeneIds?: string[];
  linkedAgentId?: string;
}): Promise<CommunityPost> {
  const res = await fetch(`${COMMUNITY_API}/posts`, {
    method: 'POST',
    headers: getCommunityAuthHeaders(),
    body: JSON.stringify(input),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to create post'));
  return data.data;
}

export async function createComment(
  postId: string,
  input: { content: string; parentId?: string; commentType?: string },
): Promise<CommunityComment> {
  const res = await fetch(`${COMMUNITY_API}/posts/${postId}/comments`, {
    method: 'POST',
    headers: getCommunityAuthHeaders(),
    body: JSON.stringify(input),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to create comment'));
  return data.data;
}

export async function voteOnTarget(input: {
  targetType: 'post' | 'comment';
  targetId: string;
  value: 1 | -1 | 0;
}): Promise<{ upvotes: number; downvotes: number; userVote: number }> {
  const res = await fetch(`${COMMUNITY_API}/vote`, {
    method: 'POST',
    headers: getCommunityAuthHeaders(),
    body: JSON.stringify(input),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to vote'));
  return data.data;
}

export async function toggleBookmark(postId: string): Promise<{ bookmarked: boolean }> {
  const res = await fetch(`${COMMUNITY_API}/bookmark`, {
    method: 'POST',
    headers: getCommunityAuthHeaders(),
    body: JSON.stringify({ postId }),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to toggle bookmark'));
  return data.data;
}

export async function fetchCommunityStats(): Promise<CommunityStats> {
  const res = await fetch(`${COMMUNITY_API}/stats`);
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to fetch stats'));
  return data.data;
}

export async function searchCommunity(params: {
  q: string;
  boardSlug?: string;
  boardId?: string;
  sort?: string;
  limit?: number;
  cursor?: string;
}): Promise<{ results: SearchResult[]; nextCursor: string | null }> {
  const searchParams = new URLSearchParams({ q: params.q });
  if (params.boardSlug || params.boardId) searchParams.set('boardSlug', params.boardSlug || params.boardId!);
  if (params.sort) searchParams.set('sort', params.sort);
  if (params.limit) searchParams.set('limit', String(params.limit));
  if (params.cursor) searchParams.set('cursor', params.cursor);
  const res = await fetch(`${COMMUNITY_API}/search?${searchParams}`);
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to search'));
  return data.data;
}

export interface TrendingTag {
  id: string;
  name: string;
  postCount: number;
  trending: boolean;
}

export async function fetchTrendingTags(limit?: number): Promise<TrendingTag[]> {
  const searchParams = new URLSearchParams();
  if (limit) searchParams.set('limit', String(limit));
  const res = await fetch(`${COMMUNITY_API}/tags/trending?${searchParams}`);
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to fetch trending tags'));
  return data.data;
}

export async function searchTags(query: string, limit: number = 10): Promise<TrendingTag[]> {
  const searchParams = new URLSearchParams({ q: query, limit: String(limit) });
  try {
    const res = await fetch(`${COMMUNITY_API}/tags/search?${searchParams}`);
    const data = await res.json();
    if (data.ok) return data.data;
  } catch { /* fall through */ }
  const all = await fetchTrendingTags(50);
  const q = query.toLowerCase();
  return all.filter((t) => t.name.toLowerCase().includes(q)).slice(0, limit);
}

export async function renameTag(tagId: string, newName: string): Promise<{ id: string; name: string }> {
  const res = await fetch(`${COMMUNITY_API}/tags/${tagId}`, {
    method: 'PUT',
    headers: { ...getCommunityAuthHeaders(), 'Content-Type': 'application/json' },
    body: JSON.stringify({ name: newName }),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(data.error || 'Failed to rename tag');
  return data.data;
}

export async function mergeTagsApi(sourceTagId: string, targetTagId: string): Promise<{ id: string; name: string }> {
  const res = await fetch(`${COMMUNITY_API}/tags/merge`, {
    method: 'POST',
    headers: { ...getCommunityAuthHeaders(), 'Content-Type': 'application/json' },
    body: JSON.stringify({ sourceTagId, targetTagId }),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(data.error || 'Failed to merge tags');
  return data.data;
}

export async function deleteTagApi(tagId: string): Promise<{ deleted: boolean; name: string }> {
  const res = await fetch(`${COMMUNITY_API}/tags/${tagId}`, {
    method: 'DELETE',
    headers: getCommunityAuthHeaders(),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(data.error || 'Failed to delete tag');
  return data.data;
}

export async function updatePost(
  id: string,
  input: { title?: string; content?: string; tags?: string[]; linkedGeneIds?: string[] },
): Promise<CommunityPost> {
  const res = await fetch(`${COMMUNITY_API}/posts/${id}`, {
    method: 'PUT',
    headers: getCommunityAuthHeaders(),
    body: JSON.stringify(input),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to update post'));
  return data.data;
}

export async function deletePost(id: string): Promise<void> {
  const res = await fetch(`${COMMUNITY_API}/posts/${id}`, {
    method: 'DELETE',
    headers: getCommunityAuthHeaders(),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to delete post'));
}

export async function updateComment(id: string, input: { content: string }): Promise<CommunityComment> {
  const res = await fetch(`${COMMUNITY_API}/comments/${id}`, {
    method: 'PUT',
    headers: getCommunityAuthHeaders(),
    body: JSON.stringify(input),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to update comment'));
  return data.data;
}

export async function deleteComment(id: string): Promise<void> {
  const res = await fetch(`${COMMUNITY_API}/comments/${id}`, {
    method: 'DELETE',
    headers: getCommunityAuthHeaders(),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to delete comment'));
}

export async function markBestAnswer(commentId: string): Promise<void> {
  const res = await fetch(`${COMMUNITY_API}/comments/${commentId}/best-answer`, {
    method: 'POST',
    headers: getCommunityAuthHeaders(),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to mark best answer'));
}

export interface GeneAutocompleteResult {
  id: string;
  title: string;
  successRate?: number;
  adopters?: number;
}

export async function searchGenes(query: string, limit = 8): Promise<GeneAutocompleteResult[]> {
  const params = new URLSearchParams({ q: query, limit: String(limit) });
  try {
    const res = await fetch(`${COMMUNITY_API}/autocomplete/genes?${params}`);
    const data = await res.json();
    if (data.ok) return data.data;
  } catch { /* fall through */ }
  return [];
}

export async function adoptGene(geneId: string): Promise<void> {
  const res = await fetch('/api/im/evolution/genes/import', {
    method: 'POST',
    headers: getCommunityAuthHeaders(),
    body: JSON.stringify({ gene_id: geneId }),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to adopt gene'));
}

// ─── Bookmarks ────────────────────────────────────────────────

export async function fetchBookmarkedPosts(params?: {
  cursor?: string;
  limit?: number;
}): Promise<{ posts: CommunityPost[]; nextCursor: string | null }> {
  const searchParams = new URLSearchParams();
  if (params?.cursor) searchParams.set('cursor', params.cursor);
  if (params?.limit) searchParams.set('limit', String(params.limit));
  const res = await fetch(`${COMMUNITY_API}/bookmarks?${searchParams}`, {
    headers: getCommunityAuthHeaders(),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to fetch bookmarks'));
  return data.data;
}

// ─── Notifications ────────────────────────────────────────────

export interface CommunityNotification {
  id: string;
  type: 'reply' | 'vote' | 'best_answer' | 'mention' | 'follow';
  postId: string;
  postTitle: string;
  commentId?: string;
  actorId: string;
  actorName: string;
  read: boolean;
  createdAt: string;
}

export async function fetchNotifications(params?: {
  unread?: boolean;
  limit?: number;
  offset?: number;
}): Promise<{ notifications: CommunityNotification[]; total: number }> {
  const searchParams = new URLSearchParams();
  if (params?.unread) searchParams.set('unread', 'true');
  if (params?.limit != null) searchParams.set('limit', String(params.limit));
  if (params?.offset != null) searchParams.set('offset', String(params.offset));
  const res = await fetch(`${COMMUNITY_API}/notifications?${searchParams}`, {
    headers: getCommunityAuthHeaders(),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to fetch notifications'));
  const d = data.data as { items: CommunityNotification[]; total: number };
  return { notifications: d.items, total: d.total };
}

export async function markNotificationsRead(notificationId?: string): Promise<void> {
  const res = await fetch(`${COMMUNITY_API}/notifications/read`, {
    method: 'POST',
    headers: getCommunityAuthHeaders(),
    body: JSON.stringify(notificationId ? { notificationId } : {}),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to mark read'));
}

export async function fetchUnreadCount(): Promise<number> {
  try {
    const res = await fetch(`${COMMUNITY_API}/notifications/count`, {
      headers: getCommunityAuthHeaders(),
    });
    const data = await res.json();
    if (!data.ok) return 0;
    return data.data?.unread ?? 0;
  } catch {
    return 0;
  }
}

// ─── Boards API ────────────────────────────────────────────────

export async function fetchBoards(): Promise<CommunityBoard[]> {
  const res = await fetch(`${COMMUNITY_API}/boards`);
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to fetch boards'));
  return data.data;
}

export async function fetchBoard(slug: string): Promise<CommunityBoard> {
  const res = await fetch(`${COMMUNITY_API}/boards/${slug}`);
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to fetch board'));
  return data.data;
}

export async function createBoard(input: {
  slug: string;
  name: string;
  description?: string;
  icon?: string;
}): Promise<CommunityBoard> {
  const res = await fetch(`${COMMUNITY_API}/boards`, {
    method: 'POST',
    headers: getCommunityAuthHeaders(),
    body: JSON.stringify(input),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to create board'));
  return data.data;
}

export async function subscribeBoard(slug: string): Promise<{ subscribed: boolean }> {
  const res = await fetch(`${COMMUNITY_API}/boards/${slug}/subscribe`, {
    method: 'POST',
    headers: getCommunityAuthHeaders(),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to toggle subscription'));
  return data.data;
}

// ─── Follow API ────────────────────────────────────────────────

export async function followUser(followingId: string, followingType: 'user' | 'agent' | 'gene' = 'user'): Promise<{ followed: boolean }> {
  const res = await fetch(`${COMMUNITY_API}/follow`, {
    method: 'POST',
    headers: getCommunityAuthHeaders(),
    body: JSON.stringify({ followingId, followingType }),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to follow'));
  return data.data;
}

export async function checkIsFollowing(followingId: string, type = 'user'): Promise<boolean> {
  const res = await fetch(`${COMMUNITY_API}/is-following/${followingId}?type=${type}`, {
    headers: getCommunityAuthHeaders(),
  });
  const data = await res.json();
  if (!data.ok) return false;
  return data.data?.isFollowing ?? false;
}

// ─── Profile API ───────────────────────────────────────────────

export interface CommunityProfile {
  id: string;
  bio?: string;
  website?: string;
  postCount: number;
  commentCount: number;
  karmaTotal: number;
  followerCount: number;
  followingCount: number;
  lastActiveAt?: string;
  streakDays: number;
  user?: {
    id: string;
    username: string;
    displayName?: string;
    role: string;
    avatarUrl?: string;
    createdAt: string;
  };
  badges?: Array<{ badge: string; awardedAt: string }>;
}

export async function fetchProfile(userId: string): Promise<CommunityProfile> {
  const res = await fetch(`${COMMUNITY_API}/profile/${userId}`);
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to fetch profile'));
  return data.data;
}

export async function fetchMyCommunityProfile(): Promise<CommunityProfile | null> {
  const res = await fetch(`${COMMUNITY_API}/me/profile`, {
    headers: getCommunityAuthHeaders(),
  });
  if (res.status === 401) return null;
  const data = await res.json();
  if (!data.ok) return null;
  return data.data;
}

export async function updateProfile(input: { bio?: string; website?: string }): Promise<CommunityProfile> {
  const res = await fetch(`${COMMUNITY_API}/me/profile`, {
    method: 'PUT',
    headers: getCommunityAuthHeaders(),
    body: JSON.stringify(input),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to update profile'));
  return data.data;
}

export async function fetchActivityHeatmap(userId: string, weeks = 52): Promise<Record<string, number>> {
  const res = await fetch(`${COMMUNITY_API}/profile/${userId}/heatmap?weeks=${weeks}`);
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to fetch heatmap'));
  return data.data;
}

// ─── Drafts API ────────────────────────────────────────────────

export interface CommunityDraft {
  id: string;
  authorId: string;
  boardSlug?: string;
  title?: string;
  contentJson?: string;
  content?: string;
  createdAt: string;
  updatedAt: string;
  expiresAt: string;
}

export async function saveDraft(input: {
  draftId?: string;
  boardSlug?: string;
  title?: string;
  contentJson?: string;
  content?: string;
}): Promise<CommunityDraft> {
  const res = await fetch(`${COMMUNITY_API}/drafts`, {
    method: 'POST',
    headers: getCommunityAuthHeaders(),
    body: JSON.stringify(input),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to save draft'));
  return data.data;
}

export async function fetchDrafts(): Promise<CommunityDraft[]> {
  const res = await fetch(`${COMMUNITY_API}/drafts`, {
    headers: getCommunityAuthHeaders(),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to fetch drafts'));
  return data.data;
}

export async function deleteDraft(draftId: string): Promise<void> {
  const res = await fetch(`${COMMUNITY_API}/drafts/${draftId}`, {
    method: 'DELETE',
    headers: getCommunityAuthHeaders(),
  });
  const data = await res.json();
  if (!data.ok) throw new Error(extractError(data, 'Failed to delete draft'));
}

export function showToast(message: string, type: 'success' | 'error' = 'success') {
  const existing = document.getElementById('community-toast');
  if (existing) existing.remove();

  const toast = document.createElement('div');
  toast.id = 'community-toast';
  toast.textContent = message;
  toast.style.cssText = `
    position: fixed; bottom: 24px; left: 50%; transform: translateX(-50%);
    padding: 10px 20px; border-radius: 12px; font-size: 14px; z-index: 9999;
    backdrop-filter: blur(20px); transition: opacity 0.3s;
    ${type === 'error'
      ? 'background: rgba(239,68,68,0.15); color: #ef4444; border: 1px solid rgba(239,68,68,0.2);'
      : 'background: rgba(34,197,94,0.15); color: #22c55e; border: 1px solid rgba(34,197,94,0.2);'
    }
  `;
  document.body.appendChild(toast);
  setTimeout(() => { toast.style.opacity = '0'; setTimeout(() => toast.remove(), 300); }, 3000);
}
